table All_Measures
	lineageTag: e648f938-9a0a-4389-87b7-8939943c3f72

	measure CampaignOpenRate = DIVIDE([cUNIQUE OPENS],[cRECIPIENTS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CampaignMeasures
		lineageTag: b0117dd1-907e-4618-a0e9-be07a5968491

	measure CampaignClickRate = DIVIDE(SUM(campaign[Clicked Email count]),SUM(campaign[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CampaignMeasures
		lineageTag: d66dde23-46b6-4a38-89de-26aa72418350

	measure CampaignBounceRate = DIVIDE(SUM(campaign[Bounced Email count]),SUM(campaign[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CampaignMeasures
		lineageTag: eadb1dbd-62ed-4821-97d2-c06348219c17

	measure CampaignUnsubscribeRate = DIVIDE([CampaignUnsubscribe],[CampaignRecip])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CampaignMeasures
		lineageTag: e7041fdd-d4da-412c-adc7-490e097591e7

	measure FlowOpenRate = DIVIDE([FlowUnqOpens],[FlowRecip])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 6dedfd15-f1b2-4a5c-aecb-5b926a68cf6e

	measure FlowClickRate = DIVIDE(SUM(flow[Clicked Email count]),SUM(flow[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 8c27fc4d-6f71-4739-b051-9f4df5667759

	measure FlowBounceRate = DIVIDE(SUM(flow[Bounced Email count]),SUM(flow[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 0f47c63b-dd3d-4410-b9d7-822f86772909

	measure FlowUnsubRate = DIVIDE(SUM(flow[Unsubscribed count]),SUM(flow[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: a0297479-ac5d-4ace-9b7e-388024695ce4

	measure Revenue28DaysAgo = ```
			
			    CALCULATE(
			        SUM(daily[Revenue]),
			        FILTER(
			            ALL(dailytDynamicDates),
			            dailytDynamicDates[Date] = MAX(dailytDynamicDates[Date]) - 28
			        )
			    )
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: 28daysbeforedata
		lineageTag: 6306c2c3-45bc-4af4-a1f4-d0a0b7315275

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure UniqueEmailReceived28DaysAgo = ```
			
			    CALCULATE(
			        SUM(daily[Received Email Unique]),
			        FILTER(
			            ALL(dailytDynamicDates),
			            dailytDynamicDates[Date] = MAX(dailytDynamicDates[Date]) - 28
			        )
			    )
			```
		formatString: 0
		displayFolder: 28daysbeforedata
		lineageTag: b80a4044-9e84-4548-95b2-847173666727

	measure CampaignConversion = SUM(campaign[Placed Order count])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 1637631a-24f3-42f1-a52b-570dbf3182a3

	measure CampaignOpenedEmails = SUM(campaign[Opened Email count])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: f9e6be12-3b38-4cbc-85fa-2e9f27260d9f

	measure CampaignRecip = SUM(campaign[Received Email unique])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: dd9467c1-46d2-44dc-bf14-c2edab9b5d3f

	measure CampaignRevenue = SUM(campaign[Revenue])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: CampaignMeasures
		lineageTag: a7cf0674-a75c-4a75-b9df-8ac811e134e4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure CampaignTotalClicks = SUM(campaign[Clicked Email count])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 3c9bf748-01f1-4486-808c-3b87e07b1760

	measure CampaignUnqClicks = SUM(campaign[Clicked Email unique])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 7c0d387d-6cda-44d0-ace9-56e23884e4ba

	measure CampaignUnqOpens = SUM(campaign[Opened Email unique])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 7187bcd8-f400-4832-aa2c-3468ac1267b9

	measure FlowConversion = SUM(flow[Placed Order count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: e5f15dd9-e4b1-46fb-9acb-f05b47c0455e

	measure FlowOpenedEmails = SUM(flow[Opened Email count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 7fbf6cf9-25ff-4a3f-81ed-84fb9623bce2

	measure FlowRecip = SUM(flow[Received Email unique])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: e51e4a85-846a-4083-ad77-11efb886c81f

	measure FlowRevenue = SUM(flow[Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FlowMeasures
		lineageTag: 4d3dcc97-e345-4569-b366-4e93595369cf

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure FlowTotalClicks = SUM(flow[Clicked Email count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 58d83d87-5adc-4760-a517-2390e874652a

	measure FlowUnqClicks = SUM(flow[Clicked Email unique])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: ae488c6f-808c-4964-8bde-e0105dbc4f58

	measure FlowUnqOpens = SUM(flow[Opened Email unique])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 873cc092-e035-44b7-9ee2-82215b894170

	measure 'dCLICK TO RECIEVE RATE' = DIVIDE([dUNIQUE CLICKS],[dRECIPIENTS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: DCLKTORECVRATE
		lineageTag: 7627cacf-00a1-49bc-8959-cef9d6530133

	measure 'dCLICK TO OPEN RATE' = DIVIDE(SUM(daily[Clicked Email Unique]),SUM(daily[Opened Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: DCLKTOOPRATE
		lineageTag: 22032fd0-a0cc-476a-80da-2fe9c19c6360

	measure 'dCONVERSION RATE' = DIVIDE(All_Measures[dCONVERSIONS],All_Measures[dUNIQUE CLICKS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: DCONVRATE
		lineageTag: 2a1accd0-aca2-4356-9fd9-09bb18c0eb0c

	measure 'dUNSUBSCRIBE RATE' = DIVIDE(SUM(daily[Unsubscribed Count]),SUM(daily[Received Email Count]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: DUNSUBRATE
		lineageTag: 1f13fbd5-01de-411f-8099-6504c5f5d1e8

	measure dRECIPIENTS = SUM(daily[Received Email Unique])
		formatString: #,0
		displayFolder: DRECP
		lineageTag: 09d86e5c-024d-4fd7-a48a-60d8a682312f

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthOverMonth"
				}

		changedProperty = FormatString

	measure 'dUNIQUE OPENS' = SUM(daily[Opened Email Unique])
		formatString: #,0
		displayFolder: DUNQOP
		lineageTag: f86206a2-9387-40b3-91c5-0302ca35865a

	measure 'dMOM Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [dRECIPIENTS] 
			VAR PPRecipients = [dPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DRECP
		lineageTag: 03f578d3-76c5-44a8-92df-7434c418a2a3

	measure dPPRecipients = CALCULATE([dRECIPIENTS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DRECP
		lineageTag: 4288bc6e-26cd-47d2-b660-5088991804a9

	measure 'dColor PM Recipients' =
			
			VAR mom_growth = DIVIDE([dRECIPIENTS] - [dPPRecipients],[dPPRecipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DRECP
		lineageTag: c08517f6-1585-4ba3-9e9d-42de68d94481

	measure dPYRecipients = CALCULATE([dRECIPIENTS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DRECP
		lineageTag: f2442a0a-5230-42ba-a4c8-4b692329620d

	measure 'dYoY Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [dRECIPIENTS] 
			VAR PYRecipients = [dPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DRECP
		lineageTag: 4f579eec-c665-4a6a-b8cb-1ae68abac6c7

	measure 'dColor PY Recipients' =
			
			VAR yoy_growth = DIVIDE([dRECIPIENTS] - [dPYRecipients],[dPYRecipients])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DRECP
		lineageTag: cf7f3d37-78ed-47e0-b980-390a196f341f

	measure 'dMOM UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [dUNIQUE OPENS] 
			VAR PPUNQOP= [dPPUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNQOP
		lineageTag: 6b1ae206-5de6-4ff9-b680-ff420d5533a9

	measure dPPUnqOp = CALCULATE([dUNIQUE OPENS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DUNQOP
		lineageTag: 38010dab-0fcd-4259-8397-de5b971582fb

	measure dPYUnqOp = CALCULATE([dUNIQUE OPENS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DUNQOP
		lineageTag: 7c8e4d78-5fdd-4609-917b-82b5e58a51cd

	measure 'dYoY UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [dUNIQUE OPENS] 
			VAR PYUNQOP= [dPYUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-[dPYUnqOp],[dPYUnqOp])
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNQOP
		lineageTag: 57db0285-ab19-44db-bcbf-3ddb8f0c5948

	measure 'dColor PM UNQOP' =
			
			VAR mom_growth = DIVIDE([dUNIQUE OPENS] - [dPPUnqOp],[dPPUnqOp])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DUNQOP
		lineageTag: e1ba81f5-f648-4c80-a008-46ae51313fe8

	measure 'dColor PY UNQOP' =
			
			VAR yoy_growth = DIVIDE([dUNIQUE OPENS] - [dPYUnqOp],[dPYUnqOp])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DUNQOP
		lineageTag: 4110d93c-8ac8-43af-a166-9400a6c19c85

	measure 'dTOTAL OPENS' = SUM(daily[Opened Email Count])
		formatString: #,0
		displayFolder: DTOTALOP
		lineageTag: 94b393f0-3a2e-42b1-8089-43634700dd8e

	measure dPPTotalOpens = CALCULATE([dTOTAL OPENS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DTOTALOP
		lineageTag: fb04908a-54d4-4f45-aeba-909a38e43341

	measure dPYTotalOpens = CALCULATE([dTOTAL OPENS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DTOTALOP
		lineageTag: 5e72c357-a1fc-48df-b482-ad3f76887397

	measure 'dMOM TotalOpens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [dTOTAL OPENS] 
			VAR PPOpens = [dPPTotalOpens]
			VAR Growth = DIVIDE(CurrentOpens - PPOpens,PPOpens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALOP
		lineageTag: 14b22784-51e4-4517-971c-f24f7df3a51b

	measure 'dYoY TotalOpens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [dTOTAL OPENS] 
			VAR PYOpens = [dPYTotalOpens]
			VAR Growth = DIVIDE(CurrentOpens -PYOpens,PYOpens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALOP
		lineageTag: 6644e941-ca9c-4c98-a157-a30a8094e784

	measure 'dColor PM Opens' =
			
			VAR mom_growth = DIVIDE([dTOTAL OPENS] - [dPPTotalOpens],[dPPTotalOpens])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DTOTALOP
		lineageTag: 31625473-b136-41e5-b014-1ed555055101

	measure 'dColor PY Opens' =
			
			VAR yoy_growth = DIVIDE([dTOTAL OPENS] - [dPYTotalOpens],[dPYTotalOpens])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DTOTALOP
		lineageTag: 00f9c31c-49d7-4c03-993a-9fa265de3440

	measure 'dUNIQUE CLICKS' = SUM(daily[Clicked Email Unique])
		formatString: #,0
		displayFolder: DUNQCLICK
		lineageTag: a72ad406-bb88-457f-ba36-b57d23ee27f1

	measure dPPTotalUnqClick = CALCULATE([dUNIQUE CLICKS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DUNQCLICK
		lineageTag: 9d2a876d-dc0d-4b54-8655-ee3e6c87831c

	measure dPYTotalUnqClick = CALCULATE([dUNIQUE CLICKS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DUNQCLICK
		lineageTag: 6a421aac-d0dc-44ba-adfe-f1c0c90e1288

	measure 'dMOM TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [dUNIQUE CLICKS] 
			VAR PPClick = [dPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick,PPClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNQCLICK
		lineageTag: 8ac3fcd6-f35a-441f-8ebb-4a04e775af45

	measure 'dYOY TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [dUNIQUE CLICKS] 
			VAR PYClick = [dPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PYClick,PYClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNQCLICK
		lineageTag: 66ab36a5-71e2-48ed-b661-09a0fd7fc66c

	measure 'dColor PM UNQ Click' =
			
			VAR mom_click = DIVIDE([dUNIQUE CLICKS] - [dPPTotalUnqClick],[dPPTotalUnqClick])
			RETURN
			    IF(mom_click<0, "red","green")
		displayFolder: DUNQCLICK
		lineageTag: 966a6528-4f93-430a-a207-47a1170c22ef

	measure 'dColor PY UNQ Click' =
			
			VAR yoy_click = DIVIDE([dUNIQUE CLICKS] - [dPYTotalUnqClick],[dPYTotalUnqClick])
			RETURN
			    IF(yoy_click<0, "red","green")
		displayFolder: DUNQCLICK
		lineageTag: 48e69417-09c9-43dc-8db8-e4846682ed08

	measure 'dTOTAL CLICKS' = SUM(daily[Clicked Email Count])
		formatString: #,0
		displayFolder: DTOTALCLK
		lineageTag: c2bade98-7ab1-4801-97f5-ff56c0e9f958

	measure dPPTotalClicks = CALCULATE([dTOTAL CLICKS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DTOTALCLK
		lineageTag: 725fc9b4-4518-4d3f-93e2-892b09205563

	measure dPYTotalClicks = CALCULATE([dTOTAL CLICKS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DTOTALCLK
		lineageTag: ef3b7bb7-09d7-4005-ac5d-4ddfd2cd71d9

	measure 'dMOM TotalClicks Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentTotalClicks = [dTOTAL CLICKS] 
			VAR PPTotalClicks = [dPPTotalClicks]
			VAR Growth = DIVIDE(CurrentTotalClicks-PPTotalClicks,PPTotalClicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALCLK
		lineageTag: 8c971c65-e114-428c-9302-66f5c545380a

	measure 'dYOY TotalClicks Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentTotalClicks = [dTOTAL CLICKS] 
			VAR PYTotalClicks = [dPYTotalClicks]
			VAR Growth = DIVIDE(CurrentTotalClicks-PYTotalClicks,PYTotalClicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALCLK
		lineageTag: 699ab192-128d-47c8-9d72-d880c23e6539

	measure 'dColor PM TotalClicks' =
			
			VAR mom_growth = DIVIDE([dTOTAL CLICKS] - [dPPTotalClicks],[dPPTotalClicks])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DTOTALCLK
		lineageTag: 8cc28658-61e5-42b9-94fb-d62fe3acd3a2

	measure 'dColor PY TotalClicks' =
			
			VAR yoy_growth = DIVIDE([dTOTAL CLICKS] - [dPYTotalClicks],[dPYTotalClicks])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DTOTALCLK
		lineageTag: 9cedea2e-1df5-4115-bdb0-b972488d268a

	measure dPPClickThroughRate = CALCULATE([dCLICK TO OPEN RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: DCLKTOOPRATE
		lineageTag: 52e776f2-1d9a-4ac1-88c0-308e8ec63623

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure dPYClickThroughRate = CALCULATE([dCLICK TO OPEN RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: DCLKTOOPRATE
		lineageTag: 439af1d2-35aa-404c-8318-166a5f7caaaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'dMOM ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [dCLICK TO OPEN RATE] 
			VAR PPClickThroughRate = [dPPClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PPClickThroughRate,PPClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DCLKTOOPRATE
		lineageTag: 8dcd0d37-7f7e-480e-8f60-da59c3256ab5

	measure 'dYoY ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [dCLICK TO OPEN RATE] 
			VAR PYClickThroughRate = [dPYClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PYClickThroughRate,PYClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DCLKTOOPRATE
		lineageTag: 4cf26196-a3e6-463e-88e4-9029b78f4663

	measure 'dColor PM ClickThroughRate' =
			
			VAR mom_growth = DIVIDE([dCLICK TO OPEN RATE] - [dPPClickThroughRate],[dPPClickThroughRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DCLKTOOPRATE
		lineageTag: 89e4808a-bcdb-456d-acb9-c62ddca10a89

	measure 'dColor PY ClickThroughRate' =
			
			VAR yoy_growth = DIVIDE([dCLICK TO OPEN RATE] - [dPYClickThroughRate],[dPYClickThroughRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DCLKTOOPRATE
		lineageTag: 283b62d7-1dba-4ab7-8c7f-38389c3cf76a

	measure dPPDailyClickRate = CALCULATE([dCLICK TO RECIEVE RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: DCLKTORECVRATE
		lineageTag: d21752e8-b131-48f3-bedd-a4b85c6b695c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure dPYDailyClickRate = CALCULATE([dCLICK TO RECIEVE RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: DCLKTORECVRATE
		lineageTag: 214be2ed-819d-442c-b7ed-d67047bbf0b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'dMOM DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [dCLICK TO RECIEVE RATE] 
			VAR PPDailyClickRate = [dPPDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PPDailyClickRate,PPDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DCLKTORECVRATE
		lineageTag: 5ae09d3c-752e-44b0-a4c4-cf0161bd3dce

	measure 'dYOY DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [dCLICK TO RECIEVE RATE] 
			VAR PYDailyClickRate = [dPYDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PYDailyClickRate,PYDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DCLKTORECVRATE
		lineageTag: 1f7de5c4-9ff9-4aff-b845-5e0be6977ea4

	measure 'dColor PM DailyClickRAte' =
			
			VAR mom_growth = DIVIDE([dCLICK TO RECIEVE RATE] - [dPPDailyClickRate],[dPPDailyClickRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DCLKTORECVRATE
		lineageTag: ac8e7d8c-c8e7-4b32-839d-de0a1eb32bec

	measure 'dColor PY DailyClickRAte' =
			
			VAR yoy_growth = DIVIDE([dCLICK TO RECIEVE RATE] - [dPYDailyClickRate],[dPYDailyClickRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DCLKTORECVRATE
		lineageTag: 1f6b02c7-9eeb-46da-8db0-c4c6ca18e670

	measure dCONVERSIONS = SUM(daily[Placed Order Count])
		formatString: #,0
		displayFolder: DTOTALCONV
		lineageTag: 32939fc4-c1c1-4d41-acea-ffd33161d2ae

	measure dPPTotalConversions = CALCULATE([dCONVERSIONS],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DTOTALCONV
		lineageTag: 4e72e565-0ecb-4f29-8693-cce469a8ae5b

	measure dPYTotalConversions = CALCULATE([dCONVERSIONS],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DTOTALCONV
		lineageTag: e622d671-53b8-4ca8-9284-d2d5f99cf58d

	measure 'dMOM TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [dCONVERSIONS] 
			VAR PPConversions = [dPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PPConversions,PPConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALCONV
		lineageTag: fa1cb07c-443c-49eb-859c-40e0f8a458ca

	measure 'dYOY TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [dCONVERSIONS] 
			VAR PYConversions = [dPYTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PYConversions,PYConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALCONV
		lineageTag: aaf772f0-6bc0-416f-86e3-9daf61a5e430

	measure 'dColor PM Conversions' =
			
			VAR mom_growth = DIVIDE([dCONVERSIONS] - [dPPTotalConversions],[dPPTotalConversions])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DTOTALCONV
		lineageTag: f1783d4f-6687-4a5b-b0cd-5523849288d9

	measure 'dColor PY Conversions' =
			
			VAR yoy_growth = DIVIDE([dCONVERSIONS] - [dPYTotalConversions],[dPYTotalConversions])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DTOTALCONV
		lineageTag: 0841c729-7de6-486b-9342-0b9e219f53f3

	measure dPPTotalConversionsRate = CALCULATE([dCONVERSION RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: DCONVRATE
		lineageTag: 4954ffae-6f71-4d69-83c3-e3fdec880aa1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure dPYTotalConversionsRate = CALCULATE([dCONVERSION RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: DCONVRATE
		lineageTag: ac03a976-4645-4d91-94c2-d09b47629860

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'dMOM DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [dCONVERSION RATE] 
			VAR PPConversionsRate = [dPPTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PPConversionsRate,PPConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DCONVRATE
		lineageTag: c0592153-65ad-45a2-be0b-b2e6d3d0a90c

	measure 'dYOY DailyConversionRate Growth%' = ```
			
			    VAR up_arrow = UNICHAR(129137) 
			    VAR down_arrow = UNICHAR(129139) 
			    VAR CurrentConversionsRate = [dCONVERSION RATE] 
			    VAR PYConversionsRate = [dPYTotalConversionsRate]
			    VAR Growth = DIVIDE(CurrentConversionsRate -PYConversionsRate,PYConversionsRate)
			    RETURN 
			        IF(
			            Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			            ROUND(Growth*100,1)&"% "& up_arrow
			        )
			```
		displayFolder: DCONVRATE
		lineageTag: 9fbd7d04-d314-46b8-9517-b56931a87d3b

	measure 'dColor PM ConversionsRate' =
			
			VAR mom_growth = DIVIDE([dCONVERSION RATE] - [dPPTotalConversionsRate],[dPPTotalConversionsRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DCONVRATE
		lineageTag: fd206d19-7aa6-4752-b967-2a15c17f4a15

	measure 'dColor PY ConversionsRate' =
			
			VAR yoy_growth = DIVIDE([dCONVERSION RATE] - [dPYTotalConversionsRate],[dPYTotalConversionsRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DCONVRATE
		lineageTag: c3fe8a98-a7dd-435d-b439-893f38ccf1bd

	measure dREVENUE = SUM(daily[Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: DTOTALREV
		lineageTag: ef0d12ac-c1ea-4895-b562-62a9553be380

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure dPPTotalRevenue = CALCULATE([dREVENUE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		displayFolder: DTOTALREV
		lineageTag: 51bd2031-5078-46c5-a9b0-9d410c09c2b5

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure dPYTotalRevenue = CALCULATE([dREVENUE],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		displayFolder: DTOTALREV
		lineageTag: ec2b5e46-19fb-4a34-8daa-920cdea2e8c8

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure 'dMOM Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [dREVENUE] 
			VAR PPRevenue = [dPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PPRevenue,PPRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALREV
		lineageTag: 4a21e326-72bd-4f78-b2aa-9d0c18cf206a

	measure 'dYOY Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [dREVENUE] 
			VAR PYRevenue = [dPYTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PYRevenue,PYRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DTOTALREV
		lineageTag: b4ee3bab-230d-454b-8c8c-4a4b733658c4

	measure 'dColor PM Revenue' =
			
			VAR mom_growth = DIVIDE([dREVENUE] - [dPPTotalRevenue],[dPPTotalRevenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DTOTALREV
		lineageTag: aabcdf8b-db4b-4429-86ec-67524d1a6e23

	measure 'dColor PY Revenue' =
			
			VAR yoy_growth = DIVIDE([dREVENUE] - [dPYTotalRevenue],[dPYTotalRevenue])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DTOTALREV
		lineageTag: af4e5962-2ec4-46e7-9cb1-758f91123610

	measure dUNSUBSCRIBE = SUM(daily[Unsubscribed Count])
		formatString: #,0
		displayFolder: DUNSUB
		lineageTag: 78565cff-3adc-484e-9d89-ef06e597bfbb

	measure dPPTotalUnsub = CALCULATE([dUNSUBSCRIBE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: DUNSUB
		lineageTag: 170a1da4-a84b-48b8-b31b-a8ae949707e5

	measure dPYTotalUnsub = CALCULATE([dUNSUBSCRIBE],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: DUNSUB
		lineageTag: 2c4fd83b-824f-4430-8d5a-0de38837abb0

	measure 'dMOM Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [dUNSUBSCRIBE] 
			VAR PPUnsub = [dPPTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PPUnsub,PPUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNSUB
		lineageTag: 1af50e5b-c2e6-48ac-84a2-af6d21f20d2d

	measure 'dYOY Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [dUNSUBSCRIBE] 
			VAR PYUnsub = [dPYTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PYUnsub,PYUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNSUB
		lineageTag: 686016ef-b38a-4ebd-9e09-7e62fa44dc73

	measure 'dColor PM Unsub' =
			
			VAR mom_growth = DIVIDE([dUNSUBSCRIBE] - [dPPTotalUnsub],[dPPTotalUnsub])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DUNSUB
		lineageTag: e3a32f86-1b93-4477-9239-69f0900572cf

	measure 'dColor PY Unsub' =
			
			VAR yoy_growth = DIVIDE([dUNSUBSCRIBE] - [dPYTotalUnsub],[dPYTotalUnsub])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DUNSUB
		lineageTag: 3817ade6-6f94-444a-b350-354983ccd919

	measure dPPTotalUnsubRate = CALCULATE([dUNSUBSCRIBE RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: DUNSUBRATE
		lineageTag: b826404b-ef9e-4be0-be3a-31f1b9e932df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure dPYTotalUnsubRate = CALCULATE([dUNSUBSCRIBE RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: DUNSUBRATE
		lineageTag: 94af93d3-11c1-466d-a091-eb34e022acb2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'dMOM Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [dUNSUBSCRIBE RATE] 
			VAR PPUnsubRate = [dPPTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PPUnsubRate,PPUnsubRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNSUBRATE
		lineageTag: 77a47168-7321-43e8-801f-f3fe29068c78

	measure 'dYOY Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [dUNSUBSCRIBE RATE] 
			VAR PYUnsubRate = [dPYTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PYUnsubRate,PYUnsubRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: DUNSUBRATE
		lineageTag: a46f984a-f8a2-411d-8c34-7b29e59f6ea1

	measure 'dColor PM UnsubRate' =
			
			VAR mom_growth = DIVIDE([dUNSUBSCRIBE RATE] - [dPPTotalUnsubRate],[dPPTotalUnsubRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: DUNSUBRATE
		lineageTag: 2fdfa3f7-91d5-40d5-957e-5e4a0ad4d9ec

	measure 'dColor PY UnsubRate' =
			
			VAR yoy_growth = DIVIDE([dUNSUBSCRIBE RATE] - [dPYTotalUnsubRate],[dPYTotalUnsubRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: DUNSUBRATE
		lineageTag: 2cad7aff-d686-4a78-ba7c-0b70da1864a8

	measure dailystartofthisperiod = FIRSTDATE(DailyDimDate[Date])
		formatString: General Date
		displayFolder: dailyPreviousPeriodCalculations
		lineageTag: 6b01299b-1695-4fa2-a34d-1165fec55f67

	measure dailyendofthisperiod = LASTDATE(DailyDimDate[Date])
		formatString: General Date
		displayFolder: dailyPreviousPeriodCalculations
		lineageTag: 9b9f1d9f-6ad4-476e-a41b-0b36af7ec14a

	measure dailydaysinperiod = DATEDIFF([dailystartofthisperiod],[dailyendofthisperiod],DAY)
		formatString: 0
		displayFolder: dailyPreviousPeriodCalculations
		lineageTag: 9b5a0a95-3a40-4332-bf95-5f640705dfa6

	measure dailyendofpreviousperiod = [dailystartofthisperiod] - 1
		formatString: General Date
		displayFolder: dailyPreviousPeriodCalculations
		lineageTag: ae491f1a-82d5-4929-b541-308dc1d7b1e1

	measure dailystartofpreviousperiod = [dailyendofpreviousperiod]-[dailydaysinperiod]
		formatString: General Date
		displayFolder: dailyPreviousPeriodCalculations
		lineageTag: bc47ecbb-be01-49a2-b6e1-4e8dd8a188f3

	measure cRECIPIENTS = SUM(campaign[Received Email Unique])
		formatString: #,0
		displayFolder: CRECP
		lineageTag: 5cc16049-2b48-4e7e-b4f6-5dc40bdb9ec6

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'cUNIQUE OPENS' = SUM(campaign[Opened Email unique])
		formatString: #,0
		displayFolder: CUNQOP
		lineageTag: ed5a846e-ae25-40cb-af64-8ddcbd96ff1f

	measure 'cTOTAL OPENS' = SUM(campaign[Opened Email count])
		formatString: #,0
		displayFolder: CTOTALOP
		lineageTag: 9c6079b7-4b2f-4207-a621-ff22c7c62a6b

	measure 'cUNIQUE CLICKS' = SUM(campaign[Clicked Email unique])
		formatString: #,0
		displayFolder: CUNQCLICK
		lineageTag: 8479f4d1-b83a-4500-a240-79734a0101fc

	measure 'cTOTAL CLICKS' = SUM(campaign[Clicked Email count])
		formatString: #,0
		displayFolder: CTOTALCLK
		lineageTag: c9f6a9a7-60c7-4460-9514-29e911d7c328

	measure 'cCLICK TO OPEN RATE' = DIVIDE(SUM(campaign[Clicked Email unique]),SUM(campaign[Opened Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCLKTOOPRATE
		lineageTag: 19178c79-23db-4f28-89e7-186262b28229

	measure 'cCLICK TO RECIEVE RATE' = DIVIDE([cUNIQUE CLICKS],[cRECIPIENTS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCLKTORECVRATE
		lineageTag: 0e64bdd7-03d5-45f6-92ce-9724bf6dfdaa

	measure cCONVERSIONS = SUM(campaign[Placed Order count])
		formatString: #,0
		displayFolder: CTOTALCONV
		lineageTag: ed7c84fa-e7b1-4638-b1fb-78e35b721f64

	measure 'cCONVERSION RATE' = DIVIDE(All_Measures[cCONVERSIONS],All_Measures[cRECIPIENTS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCONVRATE
		lineageTag: 1eabdf58-f256-4a6e-a18e-8972e6fa676f

	measure cREVENUE = SUM(campaign[Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CTOTALREV
		lineageTag: c92ecd1b-0271-4f0d-b1c1-3f1448594252

	measure cUNSUBSCRIBE = SUM(campaign[Total Unsubscribes])
		formatString: #,0
		displayFolder: CUNSUB
		lineageTag: 62ab0bb2-9202-44c2-be96-89b00b77c19d

	measure 'cUNSUBSCRIBE RATE' = DIVIDE(SUM(campaign[Total Unsubscribes]),SUM(campaign[Received Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CUNSUBRATE
		lineageTag: 72d6c17a-c3fb-462f-8a4f-c3a5fa6221e9

	measure cPPRecipients = CALCULATE([cRECIPIENTS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CRECP
		lineageTag: ad4ab1c0-4322-4b1f-bc53-0025928429fe

	measure cPYRecipients =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cRECIPIENTS],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([cRECIPIENTS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CRECP
		lineageTag: 9757fdf8-4b5b-4982-8d57-9a51ba98dc52

	measure 'cMOM Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [cRECIPIENTS] 
			VAR PPRecipients = [cPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CRECP
		lineageTag: 3d3bb0a7-0aac-4b3e-9ca9-7ec310d1acfd

	measure 'cYoY Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [cRECIPIENTS] 
			VAR PYRecipients = [cPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CRECP
		lineageTag: a1743b8d-c3af-40fa-af5b-56166cc505be

	measure 'cColor PM Recipients' =
			
			VAR mom_growth = DIVIDE([cRECIPIENTS] - [cPPRecipients],[cPPRecipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CRECP
		lineageTag: 8f9f7508-2c79-4103-8ed7-82638a3a873f

	measure 'cColor PY Recipients' =
			
			VAR yoy_growth = DIVIDE([cRECIPIENTS] - [cPYRecipients],[cPYRecipients])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CRECP
		lineageTag: 8d7da18c-8614-46a9-81fd-70815993a995

	measure cPPUnqOp = CALCULATE([cUNIQUE OPENS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CUNQOP
		lineageTag: 50d5a290-fcc7-493e-a6d8-e44667871883

	measure cPYUnqOp = CALCULATE([cUNIQUE OPENS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CUNQOP
		lineageTag: 698ef9a9-1cda-48e0-af72-bc12e150f061

	measure 'cMOM UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [cUNIQUE OPENS] 
			VAR PPUNQOP= [cPPUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQOP
		lineageTag: 13ce7f88-095c-444c-867d-479d565ecf22

	measure 'cYoY UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [cUNIQUE OPENS] 
			VAR PYUNQOP= [cPYUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-[cPYUnqOp],[cPYUnqOp])
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQOP
		lineageTag: feefa765-eca7-4448-a816-c8d8e4c3e946

	measure 'cColor PM UNQOP' =
			
			VAR mom_growth = DIVIDE([cUNIQUE OPENS] - [cPPUnqOp],[cPPUnqOp])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CUNQOP
		lineageTag: ff6dafcb-e979-4cf8-ba7f-a73a09f26255

	measure 'cColor PY UNQOP' =
			
			VAR yoy_growth = DIVIDE([cUNIQUE OPENS] - [cPYUnqOp],[cPYUnqOp])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CUNQOP
		lineageTag: 92a71c05-9b20-4ddf-91c1-29ea1a68fd9b

	measure cPPTotalOpens = CALCULATE([cTOTAL OPENS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CTOTALOP
		lineageTag: 3bb476cf-5741-435b-b2b5-8909a8b5f242

	measure cPYTotalOpens = CALCULATE([cTOTAL OPENS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CTOTALOP
		lineageTag: 036fb915-d807-49fd-84bc-07c9f3570087

	measure 'cMOM TotalOpens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [cTOTAL OPENS] 
			VAR PPOpens = [cPPTotalOpens]
			VAR Growth = DIVIDE(CurrentOpens - PPOpens,PPOpens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALOP
		lineageTag: 489ec2ca-8f81-4aa6-b92c-3462d8b3eda7

	measure 'cYoY TotalOpens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [cTOTAL OPENS] 
			VAR PYOpens = [cPYTotalOpens]
			VAR Growth = DIVIDE(CurrentOpens -PYOpens,PYOpens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALOP
		lineageTag: 9753c248-69d5-4c69-bc86-7dae3518840f

	measure 'cColor PM Opens' =
			
			VAR mom_growth = DIVIDE([cTOTAL OPENS] - [cPPTotalOpens],[cPPTotalOpens])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CTOTALOP
		lineageTag: 297d4679-7f9e-4ea3-9985-f97c52c456de

	measure 'cColor PY Opens' =
			
			VAR yoy_growth = DIVIDE([cTOTAL OPENS] - [cPYTotalOpens],[cPYTotalOpens])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CTOTALOP
		lineageTag: f487a79c-0f8e-4ff6-bed2-5d0245395d2d

	measure cPPTotalUnqClick = CALCULATE([cUNIQUE CLICKS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CUNQCLICK
		lineageTag: 997d63a0-3804-40a5-8de8-88e0767890c9

	measure cPYTotalUnqClick = CALCULATE([cUNIQUE CLICKS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CUNQCLICK
		lineageTag: 0ab1396f-1ca4-4eae-a5be-9d2004551711

	measure 'cMOM TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [cUNIQUE CLICKS] 
			VAR PPClick = [cPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick,PPClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQCLICK
		lineageTag: 70ad0fdb-cfcf-4323-bfff-5188d9727a72

	measure 'cYOY TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [cUNIQUE CLICKS] 
			VAR PYClick = [cPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PYClick,PYClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQCLICK
		lineageTag: b940a1e3-83b4-4662-995f-b1e6fa9f87b5

	measure 'cColor PM UNQ Click' =
			
			VAR mom_click = DIVIDE([cUNIQUE CLICKS] - [cPPTotalUnqClick],[cPPTotalUnqClick])
			RETURN
			    IF(mom_click<0, "red","green")
		displayFolder: CUNQCLICK
		lineageTag: afa1d733-3311-4633-8543-573e5d056ea0

	measure 'cColor PY UNQ Click' =
			
			VAR yoy_click = DIVIDE([cUNIQUE CLICKS] - [cPYTotalUnqClick],[cPYTotalUnqClick])
			RETURN
			    IF(yoy_click<0, "red","green")
		displayFolder: CUNQCLICK
		lineageTag: ee248551-3b7e-41c7-b9f7-cf4be8fab259

	measure cPPTotalClicks = CALCULATE([cTOTAL CLICKS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CTOTALCLK
		lineageTag: 76e6ed1a-ea06-42ca-a932-1d9403772a2d

	measure cPYTotalClicks = CALCULATE([cTOTAL CLICKS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CTOTALCLK
		lineageTag: 547c11ff-aec8-4eba-be3c-bcd031982bb5

	measure 'cMOM TotalClicks Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentTotalClicks = [cTOTAL CLICKS] 
			VAR PPTotalClicks = [cPPTotalClicks]
			VAR Growth = DIVIDE(CurrentTotalClicks-PPTotalClicks,PPTotalClicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALCLK
		lineageTag: 3eb54277-f250-4caf-a612-0916819a388d

	measure 'cYOY TotalClicks Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentTotalClicks = [cTOTAL CLICKS] 
			VAR PYTotalClicks = [cPYTotalClicks]
			VAR Growth = DIVIDE(CurrentTotalClicks-PYTotalClicks,PYTotalClicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALCLK
		lineageTag: d4ef7e21-0bed-4f0b-8880-b20ce9f9f7b8

	measure 'cColor PM TotalClicks' =
			
			VAR mom_growth = DIVIDE([cTOTAL CLICKS] - [cPPTotalClicks],[cPPTotalClicks])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CTOTALCLK
		lineageTag: de671166-1cf2-43e2-b647-0cd9ae03afed

	measure 'cColor PY TotalClicks' =
			
			VAR yoy_growth = DIVIDE([cTOTAL CLICKS] - [cPYTotalClicks],[cPYTotalClicks])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CTOTALCLK
		lineageTag: 195c9e8a-e3e7-4af0-9b6a-78179f76af42

	measure cPPClickThroughRate = CALCULATE([cCLICK TO OPEN RATE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCLKTOOPRATE
		lineageTag: a95354f6-87b0-440f-8e52-b4adde806615

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cPYClickThroughRate = CALCULATE([cCLICK TO OPEN RATE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CCLKTOOPRATE
		lineageTag: 70aff234-2846-4a68-91ae-aad4030688e1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cMOM ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [cCLICK TO OPEN RATE] 
			VAR PPClickThroughRate = [cPPClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PPClickThroughRate,PPClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCLKTOOPRATE
		lineageTag: f07c959e-8692-43a3-a4c7-3bf366aa9a75

	measure 'cYoY ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [cCLICK TO OPEN RATE] 
			VAR PYClickThroughRate = [cPYClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PYClickThroughRate,PYClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCLKTOOPRATE
		lineageTag: 522fa90d-7094-4872-8096-cf63aabce143

	measure 'cColor PM ClickThroughRate' =
			
			VAR mom_growth = DIVIDE([cCLICK TO OPEN RATE] - [cPPClickThroughRate],[cPPClickThroughRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCLKTOOPRATE
		lineageTag: d2e9295f-1927-47d0-bf03-bc4b540631de

	measure 'cColor PY ClickThroughRate' =
			
			VAR yoy_growth = DIVIDE([cCLICK TO OPEN RATE] - [cPYClickThroughRate],[cPYClickThroughRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCLKTOOPRATE
		lineageTag: 3a103945-c85c-4464-b760-c7a040e84522

	measure cPPDailyClickRate = CALCULATE([cCLICK TO RECIEVE RATE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCLKTORECVRATE
		lineageTag: b086a935-1aee-481f-9b9a-4518f4005cac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cPYDailyClickRate =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cCLICK TO RECIEVE RATE],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([cCLICK TO RECIEVE RATE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCLKTORECVRATE
		lineageTag: 53da15f0-178e-4482-a20e-535b75c1b078

	measure 'cMOM DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [cCLICK TO RECIEVE RATE] 
			VAR PPDailyClickRate = [cPPDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PPDailyClickRate,PPDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCLKTORECVRATE
		lineageTag: 549126b8-13ff-4e89-84fd-582e4d89299b

	measure 'cYOY DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [cCLICK TO RECIEVE RATE] 
			VAR PYDailyClickRate = [cPYDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PYDailyClickRate,PYDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCLKTORECVRATE
		lineageTag: 741e24b0-0228-46f5-9ed3-e8bea278cb2c

	measure 'cColor PM DailyClickRAte' =
			
			VAR mom_growth = DIVIDE([cCLICK TO RECIEVE RATE] - [cPPDailyClickRate],[cPPDailyClickRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCLKTORECVRATE
		lineageTag: 939dffa5-2469-4ed6-a4cc-ec4e9a2d4a06

	measure 'cColor PY DailyClickRAte' =
			
			VAR yoy_growth = DIVIDE([cCLICK TO RECIEVE RATE] - [cPYDailyClickRate],[cPYDailyClickRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCLKTORECVRATE
		lineageTag: 43f52a0d-0929-424a-8e9b-018c9828f365

	measure cPPTotalConversions = CALCULATE([cCONVERSIONS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CTOTALCONV
		lineageTag: 25108339-f79a-4ee8-8d51-ed8235f4e2eb

		annotation PBI_FormatHint = {"isDecimal":true}

	measure cPYTotalConversions = CALCULATE([cCONVERSIONS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CTOTALCONV
		lineageTag: a42451c7-8570-48d6-a291-65173b581a33

	measure 'cMOM TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [cCONVERSIONS] 
			VAR PPConversions = [cPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PPConversions,PPConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALCONV
		lineageTag: 728cb643-5c75-480a-9dd2-adf76602ebbf

	measure 'cYOY TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [cCONVERSIONS] 
			VAR PYConversions = [cPYTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PYConversions,PYConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALCONV
		lineageTag: 231822b3-b126-4222-9804-eee10a96f36a

	measure 'cColor PM Conversions' =
			
			VAR mom_growth = DIVIDE([cCONVERSIONS] - [cPPTotalConversions],[cPPTotalConversions])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CTOTALCONV
		lineageTag: 6d317257-45b8-4877-8c42-5ae4ba08d3b7

	measure 'cColor PY Conversions' =
			
			VAR yoy_growth = DIVIDE([cCONVERSIONS] - [cPYTotalConversions],[cPYTotalConversions])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CTOTALCONV
		lineageTag: d0805dfd-f7cd-436b-90dd-cc7277278800

	measure cPPTotalConversionsRate = CALCULATE([cCONVERSION RATE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCONVRATE
		lineageTag: f139738f-5b1b-4604-8cea-6a0d9c9bc320

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cPYTotalConversionsRate =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cCONVERSION RATE],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([cCONVERSION RATE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCONVRATE
		lineageTag: 4576deb7-63c8-4e05-ac95-7778c943daab

	measure 'cMOM DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [cCONVERSION RATE] 
			VAR PPConversionsRate = [cPPTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PPConversionsRate,PPConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCONVRATE
		lineageTag: cc02bdbe-a687-42c4-ae1d-44ceab3cdcef

	measure 'cYOY DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [cCONVERSION RATE] 
			VAR PYConversionsRate = [cPYTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PYConversionsRate,PYConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCONVRATE
		lineageTag: 8e5ffdf6-8b55-4432-8e5d-aaaf6ebb67a3

	measure 'cColor PM ConversionsRate' =
			
			VAR mom_growth = DIVIDE([cCONVERSION RATE] - [cPPTotalConversionsRate],[cPPTotalConversionsRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCONVRATE
		lineageTag: a0e5040a-e620-40ba-a2f5-732dc8056fbb

	measure 'cColor PY ConversionsRate' =
			
			VAR yoy_growth = DIVIDE([cCONVERSION RATE] - [cPYTotalConversionsRate],[cPYTotalConversionsRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCONVRATE
		lineageTag: 7f166a44-2803-454a-a757-e1e34c8998c3

	measure cPPTotalRevenue = CALCULATE([cREVENUE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: "₹"\ #,0.###############;#,0.###############\ -"₹";"₹"\ #,0.###############
		displayFolder: CTOTALREV
		lineageTag: bf9eca86-8f66-47cc-baa3-5f4babcb19db

		annotation PBI_FormatHint = {"currencyCulture":"en-IN"}

	measure cPYTotalRevenue =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cREVENUE],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([cREVENUE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CTOTALREV
		lineageTag: 63bb17bd-243f-4fc2-9fe6-52864648d281

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'cMOM Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [cREVENUE] 
			VAR PPRevenue = [cPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PPRevenue,PPRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALREV
		lineageTag: a87b4af4-600b-4b6b-bbf8-36f80dc76111

	measure 'cYOY Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [cREVENUE] 
			VAR PYRevenue = [cPYTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PYRevenue,PYRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CTOTALREV
		lineageTag: 057d8ea0-83ae-41a2-a715-bde6007dee22

	measure 'cColor PM Revenue' =
			
			VAR mom_growth = DIVIDE([cREVENUE] - [cPPTotalRevenue],[cPPTotalRevenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CTOTALREV
		lineageTag: 588ce24f-6b09-465f-a989-1fc79cf215ea

	measure 'cColor PY Revenue' =
			
			VAR yoy_growth = DIVIDE([cREVENUE] - [cPYTotalRevenue],[cPYTotalRevenue])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CTOTALREV
		lineageTag: 06205e4a-30e0-4be6-909a-143fab6c1f2c

	measure cPPTotalUnsub = CALCULATE([cUNSUBSCRIBE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CUNSUB
		lineageTag: edbe3e3f-bd50-4842-af7a-6fb88dead46f

	measure cPYTotalUnsub = CALCULATE([cUNSUBSCRIBE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CUNSUB
		lineageTag: 6da3ef61-7b92-4832-8625-f997b454f49d

	measure 'cMOM Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [cUNSUBSCRIBE] 
			VAR PPUnsub = [cPPTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PPUnsub,PPUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNSUB
		lineageTag: 53f68ec1-cf8d-4279-bff5-1622e8509f69

	measure 'cYOY Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [cUNSUBSCRIBE] 
			VAR PYUnsub = [cPYTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PYUnsub,PYUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNSUB
		lineageTag: f44f32b1-5a37-4bb2-8299-70a6115f7a41

	measure 'cColor PM Unsub' =
			
			VAR mom_growth = DIVIDE([cUNSUBSCRIBE] - [cPPTotalUnsub],[cPPTotalUnsub])
			RETURN
			    IF(mom_growth<0, "green","red")
		displayFolder: CUNSUB
		lineageTag: 9f6089ec-3d57-486c-9702-36447b851134

	measure 'cColor PY Unsub' =
			
			VAR yoy_growth = DIVIDE([cUNSUBSCRIBE] - [cPYTotalUnsub],[cPYTotalUnsub])
			RETURN
			    IF(yoy_growth<0,  "green","red")
		displayFolder: CUNSUB
		lineageTag: 3b4377c9-cfbe-4c00-b703-9e9343fc4657

	measure cPPTotalUnsubRate = CALCULATE([cUNSUBSCRIBE RATE],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CUNSUBRATE
		lineageTag: 9e9857e1-add2-4533-b20d-790e6df7b1be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cPYTotalUnsubRate = CALCULATE([cUNSUBSCRIBE RATE],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CUNSUBRATE
		lineageTag: ee47367c-0c92-4e44-b096-d597fbc7c004

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cMOM Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [cUNSUBSCRIBE RATE] 
			VAR PPUnsubRate = [cPPTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PPUnsubRate,PPUnsubRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNSUBRATE
		lineageTag: 0f7a0e04-6109-4e31-b958-1bd116c49c89

	measure 'cYOY Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [cUNSUBSCRIBE RATE] 
			VAR PYUnsubRate = [cPYTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PYUnsubRate,PYUnsubRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNSUBRATE
		lineageTag: 498caf65-8447-408b-8b30-ab513bc95f48

	measure 'cColor PM UnsubRate' =
			
			VAR mom_growth = DIVIDE([cUNSUBSCRIBE RATE] - [cPPTotalUnsubRate],[cPPTotalUnsubRate])
			RETURN
			    IF(mom_growth<0,  "green","red")
		displayFolder: CUNSUBRATE
		lineageTag: b352dd46-b869-466d-9ecb-d571a530f6e4

	measure 'cColor PY UnsubRate' =
			
			VAR yoy_growth = DIVIDE([cUNSUBSCRIBE RATE] - [cPYTotalUnsubRate],[cPYTotalUnsubRate])
			RETURN
			    IF(yoy_growth<0,  "green","red")
		displayFolder: CUNSUBRATE
		lineageTag: 209863a9-59ed-4be3-a643-9ec8f38eb3dd

	measure campaignstartofthisperiod = FIRSTDATE(CampaignDimDate[Send Date])
		formatString: General Date
		displayFolder: campaignPreviousPeriodCalculations
		lineageTag: 00912ab0-3e4f-4e4f-be6b-b03c6b787449

	measure campaignendofthisperiod = LASTDATE(CampaignDimDate[Send Date])
		formatString: General Date
		displayFolder: campaignPreviousPeriodCalculations
		lineageTag: 0c5a54e7-80bd-4861-932b-3b3a6824858b

	measure campaigndaysinperiod = DATEDIFF([campaignstartofthisperiod],[campaignendofthisperiod],DAY)
		formatString: 0
		displayFolder: campaignPreviousPeriodCalculations
		lineageTag: c3ad1401-78d3-4fdb-bf94-29a8150c924a

	measure campaignendofpreviousperiod = [campaignstartofthisperiod] - 1
		formatString: General Date
		displayFolder: campaignPreviousPeriodCalculations
		lineageTag: 1feb6364-a79d-43fc-8e3c-2c6a29068555

	measure campaignstartofpreviousperiod = [campaignendofpreviousperiod]-[campaigndaysinperiod]
		formatString: General Date
		displayFolder: campaignPreviousPeriodCalculations
		lineageTag: 5a584554-d801-4293-a0e3-6747b7ca2e97

	measure 'Bounced Email' = SUM(campaign[Bounced Email count])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 99e3b218-ccc5-4126-a6a1-495837cd509e

	measure 'FlowTOTAL OPENS' = SUM(flow[Opened Email Count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 3b06e1c1-4e80-425c-b159-82d1e18f78c3

	measure 'FlowCLICK TO OPEN RATE' = DIVIDE(SUM(flow[Clicked Email Unique]),SUM(flow[Opened Email unique]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 695d68bd-f39e-44ce-a1f8-d45328095175

	measure 'FlowCLICK TO RECIEVE RATE' = DIVIDE([FlowUnqClicks],[FlowRecip])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: a88cb9d4-d04d-40b1-a0f3-e15886d82b33

	measure 'FlowCONVERSION RATE' = DIVIDE(All_Measures[FlowConversion],All_Measures[FlowRecip])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 353ab960-b4ae-4b65-a002-df93a9b1fb1a

	measure FlowUnsubscribed = SUM(flow[Unsubscribed Count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 8298c0c0-309c-4a74-8632-f6b7c725acbe

	measure 'FlowUnsubscribe rate' = DIVIDE([FlowUnsubscribed],[FlowRecip])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FlowMeasures
		lineageTag: 566f653b-d967-4bb2-8824-6fdc67262666

	measure 'FCurrent Week Revenue' = CALCULATE([FlowRevenue],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Flow Current Week
		lineageTag: e0405a9b-49c8-4a53-9c06-638fb12a806c

	measure 'FCurrent Week Recipients' = CALCULATE([FlowRecip],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 93299ec8-1f06-4b43-9e20-0ec549c4b70d

	measure 'FCurrent Week Total Opens' = CALCULATE([FlowTOTAL OPENS],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: f865492e-79f3-4f62-a602-101e8f49075a

	measure 'FCurrent Week Unique Opens' = CALCULATE([FlowUnqOpens],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 251360f1-77d3-4622-ae82-f8e6d57bdeec

	measure 'FCurrent Week Total Clicks' = CALCULATE([FlowTotalClicks],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: c598b2f4-71e2-453c-b68d-16477fdd7b16

	measure 'FCurrent Week Unique Clicks' = CALCULATE([FlowUnqClicks],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 6c6a0270-ef03-4dcf-926e-7804e47f4b42

	measure 'FCurrent Week Click Rate' = CALCULATE([FlowClickRate],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow Current Week
		lineageTag: 3da78fb6-f324-4552-900f-ac2c815031bf

	measure 'FCurrent Week Conversion' = CALCULATE([FlowConversion],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 319ceaaf-34e8-413f-b909-0af07b5f9028

	measure 'FCurrent Week Unsubscribed' = CALCULATE([FlowUnsubscribed],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: fd19e8f4-e5bf-4c19-9111-4a2b1c1f7737

	measure 'FCurrent Week Bounced Email' = CALCULATE(SUM(flow[Opened Email count]),FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 18940f34-2fd8-4cdf-b238-6055c738932e

	measure fPPRecipients = CALCULATE([FlowRecip],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: FRECP
		lineageTag: 59d39344-b6d4-4af7-9b64-f450ccbec21c

	measure fPYRecipients = CALCULATE([FlowRecip],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: FRECP
		lineageTag: 2d2309d0-1327-45ae-9753-c02e61916c8c

	measure 'fMOM Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowRecip] 
			VAR PPRecipients = [fPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FRECP
		lineageTag: e817518a-91e2-4494-b084-d3b68ac98c02

	measure 'fYoY Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowRecip] 
			VAR PYRecipients = [fPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FRECP
		lineageTag: db98d08f-4ea9-4f22-9aeb-c840c7e31fc2

	measure fPPUniqOpens = CALCULATE([FlowUnqOpens],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: FUNQOP
		lineageTag: 538c8829-363b-4640-8573-d837f016e272

	measure fPYUnqOpens = CALCULATE([FlowUnqOpens],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: FUNQOP
		lineageTag: e44e098a-9b08-40f9-84bb-de17cf549e12

	measure 'fMOM Unique Opens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowUnqOpens] 
			VAR PPRecipients = [fPPUniqOpens]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQOP
		lineageTag: c83d06fc-7e72-4921-942f-e51ca1696b63

	measure 'fYoY Unique Opens Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowUnqOpens] 
			VAR PYRecipients = [fPYUnqOpens]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQOP
		lineageTag: 21edcd0c-aeeb-4db0-90eb-1cbdcae6ba38

	measure fPPTotalUnqClick = CALCULATE([FlowUnqClicks],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: FUNQCLICKS
		lineageTag: 98e79b5b-bac9-477c-ba9f-8655446e2bbd

	measure fPYTotalUnqClick = CALCULATE([FlowUnqClicks],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: FUNQCLICKS
		lineageTag: 64b9e4ff-3283-4777-aa67-db26449a1532

	measure 'fMOM TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [FlowUnqClicks] 
			VAR PPClick = [fPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick,PPClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQCLICKS
		lineageTag: 8e4eafb1-c539-4e73-b21b-a9dee3e8f830

	measure 'fYOY TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [FlowUnqClicks] 
			VAR PYClick = [fPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PYClick,PYClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQCLICKS
		lineageTag: 3f1149e3-80a4-4d2a-8432-fe2740c50e88

	measure fPPFlowClickRate = CALCULATE([FlowCLICK TO RECIEVE RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: FCLKTORECVRATE
		lineageTag: c17677f6-ce51-40e0-83c6-e9ba97587993

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure fPYFlowClickRate = CALCULATE([FlowCLICK TO RECIEVE RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: FCLKTORECVRATE
		lineageTag: 08ce9b01-d884-427a-88ce-bc32467c8059

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'fMOM FlowClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [FlowCLICK TO RECIEVE RATE] 
			VAR PPDailyClickRate = [fPPFlowClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PPDailyClickRate,PPDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCLKTORECVRATE
		lineageTag: b2d7fee9-564a-4bbe-81ce-79de75768e59

	measure 'fYOY FlowClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [FlowCLICK TO RECIEVE RATE] 
			VAR PYDailyClickRate = [fPYFlowClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PYDailyClickRate,PYDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCLKTORECVRATE
		lineageTag: bb277ade-a542-4ea3-b2af-2cd69fac47b2

	measure fPPTotalConversions = CALCULATE([FlowConversion],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: FTOTALCONV
		lineageTag: 7970b782-a66d-4f45-b5e2-8027c0555f0a

	measure fPYTotalConversions = CALCULATE([FlowConversion],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: FTOTALCONV
		lineageTag: a9c382c7-0205-4f43-85b3-53c45a6d432e

	measure 'fMOM TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [FlowConversion] 
			VAR PPConversions = [fPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PPConversions,PPConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FTOTALCONV
		lineageTag: 6cb35092-7477-486a-a828-05f21cdf7b3e

	measure 'fYOY TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [FlowConversion] 
			VAR PYConversions = [fPYTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PYConversions,PYConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FTOTALCONV
		lineageTag: 27286f6a-59ab-4eb2-b889-e7ef7147235f

	measure fPPTotalConversionsRate = CALCULATE([FlowCONVERSION RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: FCONVRATE
		lineageTag: ac0b6ab4-9700-47ad-b5af-b06a7a2f0131

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure fPYTotalConversionsRate = CALCULATE([FlowCONVERSION RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: FCONVRATE
		lineageTag: 34fcc25b-433e-4882-b709-382ce04c66be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'fMOM DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [flowCONVERSION RATE] 
			VAR PPConversionsRate = [fPPTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PPConversionsRate,PPConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCONVRATE
		lineageTag: 29c7a450-1756-4ef9-931f-2bb85bbee71c

	measure 'fYOY DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [flowCONVERSION RATE] 
			VAR PYConversionsRate = [fPYTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PYConversionsRate,PYConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCONVRATE
		lineageTag: 537a3e79-c34f-467b-99d7-da3c3e8a16fc

	measure fPPTotalRevenue = CALCULATE([FlowRevenue],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: FTOTALREV
		lineageTag: 64c13d06-2dac-4120-82f7-8cf142b77ae7

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure fPYTotalRevenue = CALCULATE([flowREVENUE],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: FTOTALREV
		lineageTag: 39a49b6e-9b4b-43d5-a6f1-63faedbed971

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'fMOM Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [flowREVENUE] 
			VAR PPRevenue = [fPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PPRevenue,PPRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FTOTALREV
		lineageTag: 2ed4f201-6dae-4bcc-9217-b938bd1cf388

	measure 'fYOY Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [flowREVENUE] 
			VAR PYRevenue = [fPYTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PYRevenue,PYRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FTOTALREV
		lineageTag: e14ba76d-b53e-4907-9429-242d211c9863

	measure fPPTotalUnsub = CALCULATE([FlowUnsubscribed],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		formatString: 0
		displayFolder: FUNSUB
		lineageTag: 9fe3e5c7-4b8c-48a9-9733-754db9362458

	measure fPYTotalUnsub = CALCULATE([FlowUnsubscribed],DATEADD(DailyDimDate[Date],-1,YEAR))
		formatString: 0
		displayFolder: FUNSUB
		lineageTag: f5a798cf-38fa-4c0f-b2e0-51a53ee1f0eb

	measure 'fMOM Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [FlowUnsubscribed] 
			VAR PPUnsub = [fPPTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PPUnsub,PPUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNSUB
		lineageTag: 33cb71d5-b5e6-4cf6-bbc3-f00179100ca6

	measure 'fYOY Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [FlowUnsubscribed] 
			VAR PYUnsub = [fPYTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PYUnsub,PYUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNSUB
		lineageTag: e70c0c42-b71c-4ade-9ab6-cbcff39841ce

	measure 'fColor PM Recipients' =
			
			VAR mom_growth = DIVIDE([FlowRecip] - [fPPRecipients],[fPPRecipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FRECP
		lineageTag: e743782b-2747-4ee5-b2bc-bd1a0f5148dc

	measure 'fColor PY Recipients' =
			
			VAR yoy_growth = DIVIDE([FlowRecip] - [fPYRecipients],[fPYRecipients])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FRECP
		lineageTag: 7f146582-9693-48f4-bb46-f26f57eaaeb1

	measure 'fColor PM UNQOP' =
			
			VAR mom_growth = DIVIDE([FlowUnqOpens] - [fPPUniqOpens],[fPPUniqOpens])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FUNQOP
		lineageTag: 5bd1ec71-ab25-451f-8216-99cf3c65ebf7

	measure 'fColor PY UNQOP' =
			
			VAR yoy_growth = DIVIDE([FlowUnqOpens] - [fPYUnqOpens],[fPYUnqOpens])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FUNQOP
		lineageTag: b6d7ecb9-0df8-49c4-8656-6b5c795ec297

	measure 'fColor PM UNQ Click' =
			
			VAR mom_click = DIVIDE([FlowUnqClicks] - [fPPTotalUnqClick],[fPPTotalUnqClick])
			RETURN
			    IF(mom_click<0, "red","green")
		displayFolder: FUNQCLICKS
		lineageTag: d8f69f24-b1bf-4bf0-91f8-cd9b6c747ed4

	measure 'fColor PY UNQ Click' =
			
			VAR yoy_click = DIVIDE([FlowUnqClicks] - [fPYTotalUnqClick],[fPYTotalUnqClick])
			RETURN
			    IF(yoy_click<0, "red","green")
		displayFolder: FUNQCLICKS
		lineageTag: b4220241-f821-4300-89b0-008cbead6fee

	measure fPPClickThroughRate = CALCULATE([flowCLICK TO OPEN RATE],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: FCLKTOOPRATE
		lineageTag: 8db96858-db03-4a34-b2c9-ff41ac19e12c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure fPYClickThroughRate = CALCULATE([flowCLICK TO OPEN RATE],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: FCLKTOOPRATE
		lineageTag: 8d21b08e-4767-4911-ac0c-570bf76ae3e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'fColor PM ClickThroughRate' =
			
			VAR mom_growth = DIVIDE([flowCLICK TO OPEN RATE] - [fPPClickThroughRate],[fPPClickThroughRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FCLKTOOPRATE
		lineageTag: 4481197d-885f-4125-adc1-666745d432e7

	measure 'fColor PY ClickThroughRate' =
			
			VAR yoy_growth = DIVIDE([flowCLICK TO OPEN RATE] - [fPYClickThroughRate],[fPYClickThroughRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FCLKTOOPRATE
		lineageTag: 0f07165c-d9a9-439c-8395-e039702778e7

	measure 'fMOM ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [flowCLICK TO OPEN RATE] 
			VAR PPClickThroughRate = [fPPClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PPClickThroughRate,PPClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCLKTOOPRATE
		lineageTag: f38c1074-4470-4ffc-b50b-c4d3a59c20d1

	measure 'fYoY ClickThroughRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentClickThroughRate = [flowCLICK TO OPEN RATE] 
			VAR PYClickThroughRate = [fPYClickThroughRate]
			VAR Growth = DIVIDE(CurrentClickThroughRate-PYClickThroughRate,PYClickThroughRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FCLKTOOPRATE
		lineageTag: e2ef50d5-5629-4044-9341-6a1a782b5ae0

	measure 'fColor PM DailyClickRAte' =
			
			VAR mom_growth = DIVIDE([flowCLICK TO RECIEVE RATE] - [fPPFlowClickRate],[fPPFlowClickRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FCLKTORECVRATE
		lineageTag: 0144e4c1-2a5c-4711-9b70-c689f336d92a

	measure 'fColor PY DailyClickRAte' =
			
			VAR yoy_growth = DIVIDE([flowCLICK TO RECIEVE RATE] - [fPYFlowClickRate],[fPYflowClickRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FCLKTORECVRATE
		lineageTag: 08e48dc9-bb70-4c76-9b91-6a85c33f6ddd

	measure 'fColor PM Conversions' =
			
			VAR mom_growth = DIVIDE([FlowConversion] - [fPPTotalConversions],[fPPTotalConversions])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FTOTALCONV
		lineageTag: 2a95a413-a0ac-43cc-89ac-a91057bb1b31

	measure 'fColor PY Conversions' =
			
			VAR yoy_growth = DIVIDE([FlowConversion] - [fPYTotalConversions],[fPYTotalConversions])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FTOTALCONV
		lineageTag: e61beac6-461c-42c0-8bb6-f999de1c3163

	measure 'fColor PM ConversionsRate' =
			
			VAR mom_growth = DIVIDE([FlowCONVERSION RATE]- [fPPTotalConversionsRate],[fPPTotalConversionsRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FCONVRATE
		lineageTag: 5ab97c37-122d-4905-8b7e-33dd6023d949

	measure 'fColor PY ConversionsRate' =
			
			VAR yoy_growth = DIVIDE([FlowCONVERSION RATE] - [fPYTotalConversionsRate],[fPYTotalConversionsRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FCONVRATE
		lineageTag: aa2aa4c3-b4da-4034-af96-4238328a4804

	measure 'fColor PM Revenue' =
			
			VAR mom_growth = DIVIDE([FlowRevenue] - [fPPTotalRevenue],[fPPTotalRevenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FTOTALREV
		lineageTag: 17511a6d-3f77-4e58-8997-cabeb2899e49

	measure 'fColor PY Revenue' =
			
			VAR yoy_growth = DIVIDE([FlowRevenue] - [fPYTotalRevenue],[fPYTotalRevenue])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FTOTALREV
		lineageTag: 51d0f247-c7fe-44c1-857e-b22f8208e45b

	measure 'fColor PM Unsub' =
			
			VAR mom_growth = DIVIDE([FlowUnsubscribed] - [fPPTotalUnsub],[fPPTotalUnsub])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FUNSUB
		lineageTag: 122596b5-17cc-4450-9d09-f18ffe73192e

	measure 'fColor PY Unsub' =
			
			VAR yoy_growth = DIVIDE([FlowUnsubscribed] - [fPYTotalUnsub],[fPYTotalUnsub])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FUNSUB
		lineageTag: 803bf44f-ea34-4c08-b71c-84aa5cc062be

	measure 'FlowRev 4WA' = CALCULATE(AVERAGE(flow[Revenue]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FLow 4 Week Average
		lineageTag: 4cfb2309-d55c-4f54-8a09-d420ed2dda07

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'FlowRecip 4WA' = CALCULATE(AVERAGE(flow[Revenue]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: 86c49166-1caa-46e5-9e7a-d0a4f92c4ddc

	measure 'FlowBounce Email 4WA' = CALCULATE(AVERAGE(flow[Bounced Email count]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: ac15d2d8-e3e6-4ab6-97fb-a5b7c6e2c37a

	measure 'FlowTotal Opens 4WA' = CALCULATE(AVERAGE(flow[Opened Email count]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: f64c17c8-da54-4872-a38d-5a1b5ba08327

	measure 'FlowUnique Opens 4WA' = CALCULATE(AVERAGE(flow[Opened Email unique]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: b7d62786-a8ee-4362-8181-ec3666e11f91

	measure 'FlowUnique Clicks 4WA' = CALCULATE(AVERAGE(flow[Clicked Email unique]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: b7c28f39-833b-4740-b063-ed188ecd7f18

	measure 'FlowTotal Clicks 4WA' = CALCULATE(AVERAGE(flow[Clicked Email count]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: cdd05e77-022a-434a-a10a-65773386171f

	measure 'FlowUnsubscribed 4WA' = CALCULATE(AVERAGE(flow[Unsubscribed count]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: 137da3e8-03a9-47dc-98af-9b103f27c05c

	measure 'FlowClickRate 4WA' = CALCULATE(AVERAGE(DIVIDE(SUM(flow[Clicked Email count]),SUM(flow[Received Email unique]))),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		displayFolder: FLow 4 Week Average
		lineageTag: 6b99540a-2169-47ba-b47a-3bb1eec51a07

	measure 'FlowConversion 4WA' = CALCULATE(AVERAGE(flow[Placed Order count]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: d28ca7ee-e794-4006-8418-35fbe062218c

	measure 'Flow RecipMTD' = CALCULATE([FlowRecip],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 46382cfa-2350-4d46-a8ed-2f40010734af

	measure 'Flow UniqOpensMTD' = CALCULATE([FlowUnqOpens],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 3d8347eb-3e4e-46bb-a876-4bc750684811

	measure 'Flow UniqueClicksMTD' = CALCULATE([FlowUnqClicks],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: e13b1a58-c73c-4072-af67-34fea7d0e513

	measure 'Flow ConversionMTD' = CALCULATE([FlowConversion],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 338d7443-7e14-4d5a-8c94-aac3d4efc256

	measure 'Flow RevenueMTD' = CALCULATE([FlowRevenue],DATESMTD(DailyDimDate[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Flow MTD
		lineageTag: 7264bcd9-e2fc-4b63-898d-8e2ab1c7fa70

	measure 'Flow UnsubMTD' = CALCULATE([FlowUnsubscribed],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 7edf33da-6096-49b5-bbf1-2acc56b35747

	measure 'Flow ClickRateMTD' = CALCULATE([FlowClickRate],DATESMTD(DailyDimDate[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow MTD
		lineageTag: 81f3593a-b202-4131-b529-1b671f32455b

	measure 'Flow BouncedEmailMTD' = CALCULATE(SUM(flow[Bounced Email count]),DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 6f510975-9a1b-4d11-a8c0-bd1830f2bb51

	measure 'Campaign RevenueMTD' = CALCULATE([cREVENUE],DATESMTD(CampaignDimDate[Send Date]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Campaign MTD
		lineageTag: 6a9fc04d-565a-4a01-ae87-cf7e28a57d00

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Campaign RecipMTD' = CALCULATE([cRECIPIENTS],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 750a7759-9da5-491b-8193-711d73fab225

	measure 'Campaign UniqueOpenMTD' = CALCULATE([cUNIQUE OPENS],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: c460fbf3-5924-48d9-8b98-edd5699bf4cf

	measure 'Campaign UniqueClicksMTD' = CALCULATE([cUNIQUE CLICKS],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 1a692f3d-44ea-41e0-b593-fda1601a38f8

	measure 'Campaign ConversionMTD' = CALCULATE([cCONVERSIONS],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 4ae1592d-8604-482d-8ef6-7bfc8d005724

	measure 'Campaign unsubMTD' = CALCULATE([cUNSUBSCRIBE],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 922a5a72-8ddc-45e5-be27-a6c506f80b72

	measure 'Campaign BounceEmailMTD' = CALCULATE([Bounced Email],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 6f2e799c-5fd8-41c4-8259-5105c7067a2f

	measure 'GA Session' = CALCULATE(SUM('GA4 Retrospec'[sessions]))
		formatString: #,0
		displayFolder: GA Measure
		lineageTag: 99285c70-c8cf-464b-98e6-23fe51f0d842

	measure 'GA Session Email' = CALCULATE(SUM('GA4 Retrospec'[sessions]),FILTER('GA4 Retrospec','GA4 Retrospec'[sessionMedium] in {"Email","email"}))
		formatString: #,0
		displayFolder: GA Measure
		lineageTag: 8806e2ac-d42d-47d0-8546-38dc9e59be7d

	measure 'GA Rev %' = DIVIDE([Email Rev],[Site Rev])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GA Measure
		lineageTag: 4b021c71-c04a-4cbb-b863-7541d63eb2e0

	measure 'GA Session %' = DIVIDE([GA Session Email],[GA Session])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: GA Measure
		lineageTag: c65ad6f3-7e0a-4218-b87f-6e69772bab40

	measure 'CBounced Email 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(campaign[Bounced Email count]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: f7c2b327-3200-4c4d-9612-91dac081cffa

	measure 'CRevenue 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE(campaign[Revenue]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Campaign 4 WA
		lineageTag: dc38e3a9-f68d-4a44-bd3c-a4dd2ab5e760

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CUnique OpenEmail 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE(campaign[Opened Email unique]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: 255243af-7aba-4f43-a21a-e3c605c81bbf

	measure 'CUnique Clciks Email 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE(campaign[Clicked Email unique]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: 41efc115-67f0-4f6c-8585-c3eec8bdcda9

	measure 'CRecip 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE(campaign[Received Email unique]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: 9aefdeb6-6a15-4d47-8eb7-77cfa81eb8d4

	measure 'Cunscribed 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE(campaign[Total Unsubscribes]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: f26f957f-87c7-4bc5-a708-03f57921730a

	measure 'CConversion 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(campaign[Placed Order count]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: 3dc4b67b-97d9-4e55-b42f-15e2cedc149c

	measure 'CConversion Rate4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(DIVIDE(All_Measures[cCONVERSIONS],All_Measures[cUNIQUE CLICKS]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Campaign 4 WA
		lineageTag: d0b11139-caad-4bb8-b5c5-541762287f5a

	measure 'CClicktoreceive Rate 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(DIVIDE([cUNIQUE CLICKS],[cRECIPIENTS]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Campaign 4 WA
		lineageTag: 1cc382bf-2f15-4fb0-94f9-351d72f53f6e

	measure FlowBounceEmail = SUM(flow[Bounced Email count])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 06e90a6e-dbfa-46ae-9d29-07e179c13b64

	measure 'FBounced Email 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Bounced Email count]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: 40458b96-37c8-44fa-a6b1-910c961d927f

	measure 'FRecip 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Received Email unique]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: 4cd18be2-5377-4d12-b50c-b048b3254047

	measure 'FUnq Opens 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Opened Email unique]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: fc538160-8b7a-4b58-b86c-f9a3b8b136db

	measure 'FUniq Clicks 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Clicked Email unique]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		displayFolder: Flow 4 WA
		lineageTag: 11846356-15be-4292-ad22-37ac3c698b24

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'FRevenue 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Revenue]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Flow 4 WA
		lineageTag: 287ab52f-e596-4cee-b5a7-b5a6cf3a7a9b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'FUnsub 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Unsubscribed count]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: 35635e93-62b1-4c32-b71c-002553fd7f44

	measure 'FConversion 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM(flow[Placed Order count]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: eadb0c4d-e5b7-46e5-8f6a-f1ef9733ed08

	measure 'FClickRate 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return CALCULATE(DIVIDE([FlowUnqClicks],[FlowRecip]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow 4 WA
		lineageTag: 16aed1ed-4696-45a4-ac82-fe3c52d1c8c8

	measure 'FCConversionRate 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return CALCULATE(DIVIDE(All_Measures[FlowConversion],All_Measures[FlowUnqClicks]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow 4 WA
		lineageTag: 3a76d789-2048-43aa-b360-a6b8c3ebc2d6

	measure 'Site Rev' = SUM(OrderLine[Total Revenue])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: GA Measure
		lineageTag: c4af58d7-c224-4a0e-88b8-501c623de8c6

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Email Rev' = [cREVENUE] + [FlowRevenue]
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: GA Measure
		lineageTag: c8403971-2e84-4b1d-b1f7-152cff6ec11e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Last 7 Days' = CALCULATE(COUNT(list_last_7d[Email]))
		formatString: #,0
		lineageTag: 01fd359e-011d-45e9-88e3-159d0ac799fc

	measure Buyers = CALCULATE(COUNT(list_purchasers[Email]))
		formatString: #,0
		lineageTag: 73018554-0030-4d1a-a962-9048af5ffe04

	measure 'Non Buyers' = CALCULATE(COUNT(list_non_purchasers[Email]))
		formatString: #,0
		lineageTag: 751677c5-7b30-4843-bec9-0bcfac31eb58

	measure 'Total Growth' = [Buyers] + [Non Buyers]
		formatString: #,0
		lineageTag: 219ec061-d6f5-44f1-99c4-486ee96ce634

	measure 'CCNF Recp' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cRECIPIENTS],
			    "Flows",     [FlowRecip],
			    [cRECIPIENTS] + [FlowRecip]
			)
			
			```
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: f0a7930e-a704-4c44-85c9-6c73403f63ee

	measure 'CCNF Unique Opens' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cUNIQUE OPENS],
			    "Flows",     [FlowUnqOpens],
			    [cUNIQUE OPENS] + [FlowUnqOpens]
			)
			
			```
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: e484c3bb-f7ab-4ad1-bcc3-3a98a933573b

	measure 'CCNF Unique Clicks' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cUNIQUE CLICKS],
			    "Flows",     [FlowUnqClicks],
			    [cUNIQUE CLICKS] + [FlowUnqClicks]
			)
			
			```
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: 0d7a71a3-9732-4148-93b1-ff38557884b7

	measure 'CCNF Revenue' =
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cREVENUE],
			    "Flows",  [FlowRevenue],
			     [cREVENUE] + [FlowRevenue])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCNF Measures
		lineageTag: 9b244d0b-6387-4bcf-bb66-0d4ca5cd0a38

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CCNF Conversion' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cCONVERSIONS],
			    "Flows",     [FlowConversion],
			    [cCONVERSIONS] + [FlowConversion]
			)
			
			```
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: 665bc52e-12be-45b2-9ca7-f750fe96f95b

	measure 'CCNF Unsubscribe' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", [cUNSUBSCRIBE],
			    "Flows",     [FlowUnsubscribed],
			    [cUNSUBSCRIBE] + [FlowUnsubscribed]
			)
			
			```
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: 0be24c85-c40e-4153-8014-ca0a90219aa9

	measure 'CCNF Click to receive rate' = DIVIDE([CCNF Unique Clicks],[CCNF Recp])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF Measures
		lineageTag: 4fb229fe-1044-412b-82fc-f54abcbfaf83

	measure 'CCNF Conversion Rate' = ```
			DIVIDE([CCNF Conversion],[CCNF Recp])
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF Measures
		lineageTag: 69e7ad88-659b-49c6-bae6-5bb0dc5ae219

	measure 'CCNF Unsubscribed Rate' = ```
			DIVIDE([CCNF Unsubscribe],[CCNF Recp])
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF Measures
		lineageTag: 238c8c6d-f622-4829-be53-a150ae960948

	measure 'MTD Recip' = CALCULATE([CCNF Recp],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: a0e9411d-9f74-45c5-ac6d-bf48f48cb6ff

	measure 'MTD Revenue' = CALCULATE([CCNF Revenue],DATESMTD(DailyDimDate[Date]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCNF MTD
		lineageTag: 1795c508-ff95-4d67-a127-75b597b4924d

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'MTD Unique Clicks' = CALCULATE([CCNF Unique Clicks],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: 589f7e35-378c-4a19-add0-6f83f478e738

	measure 'MTD Unique Opens' = CALCULATE([CCNF Unique Opens],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: 2a4ba44a-b52d-450c-82b9-45ad8b9ce54f

	measure 'MTD Conversion' = CALCULATE([CCNF Conversion],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: cd790eff-87e2-45eb-b0c1-559dcdbc6836

	measure 'MTD Unsubscribed' = CALCULATE([CCNF Unsubscribe],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: 68fd6b5c-71bc-4bea-9739-38979d7de197

	measure 'CCNF Bounce Email' = [FlowBounceEmail] + CALCULATE(SUM(campaign[Bounced Email count]))
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: af5745fc-3853-4fa8-bb77-1789d46f8d46

	measure 'MTD Bounced Email' = CALCULATE([CCNF Bounce Email],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: 30c25656-5f24-4ab7-b9a6-9a8d4a62f46c

	measure 'CCNFBounced Email 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Bounce Email],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: d8a6c960-8dfe-435f-a593-034e9dfa6c63

	measure 'CCNFRevenue 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Revenue],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCNF 4 Week Average
		lineageTag: f1b05d50-538e-4414-b7c8-c3fb8b12c534

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'CCNFRecip 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Recp],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: 9231c6f9-4c67-4a6b-9722-29d48f52ae9d

	measure 'CCNFUnique Opens 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Unique Opens],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		displayFolder: CCNF 4 Week Average
		lineageTag: fe141716-61f0-4408-93e6-840803371314

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CCNF Unique Clicks 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Unique Clicks],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: 1adf9547-f368-4f57-be6d-a327b65aa2a9

	measure 'CCNFConversion 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Conversion],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: 0
		displayFolder: CCNF 4 Week Average
		lineageTag: fc3959ec-9570-4813-8dbb-e41e9819b87b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CCNFUnsubscribed 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Unsubscribe],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: 5bcf3a20-100a-4b8b-9d4f-53525de3bedf

	measure 'ccnfMOM Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Recp] 
			VAR PPRecipients = [ccnfPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Recip
		lineageTag: 8b456723-c592-4f6b-8698-d664972659c9

	measure ccnfPPRecipients = CALCULATE([CCNF Recp],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CCNF Recip
		lineageTag: dbc3b739-71ca-4eb3-a137-da647ed0d5f0

	measure ccnfPYRecipients =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Recp],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Recp],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: #,0
		displayFolder: CCNF Recip
		lineageTag: a6953da5-08c9-42c2-8cab-e684bf392323

	measure 'ccnfYoY Recipients Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Recp] 
			VAR PYRecipients = [ccnfPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Recip
		lineageTag: e525b13d-34a4-4382-9545-97892412cdbd

	measure 'ccnfColor PM Recipients' =
			
			VAR mom_growth = DIVIDE([CCNF Recp] - [ccnfPPRecipients],[ccnfPPRecipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Recip
		lineageTag: a5fe22ed-8eef-482f-bca7-7507ceeca040

	measure 'ccnfColor PY Recipients' =
			
			VAR yoy_growth = DIVIDE([CCNF Recp] - [ccnfPYRecipients],[ccnfPYRecipients])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Recip
		lineageTag: 5398cb75-207e-4919-9d2d-bbcdaddb87b8

	measure ccnfPPTotalRevenue = CALCULATE([CCNF Revenue],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCNF Revenue
		lineageTag: e5c68340-51fe-4ea9-91dd-cc227e109d22

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure ccnfPYTotalRevenue = ```
			
			// CALCULATE([CCNF Revenue],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Revenue],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: CCNF Revenue
		lineageTag: efd8cf99-0d93-4658-b3c7-130b950ba2f4

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ccnfMOM Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [CCNF Revenue]
			VAR PPRevenue = [ccnfPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PPRevenue,PPRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Revenue
		lineageTag: 5a41e656-26ac-42cf-8b39-32e4d8d1d232

	measure 'ccnfYOY Revenue Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [CCNF Revenue] 
			VAR PYRevenue = [ccnfPYTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PYRevenue,PYRevenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Revenue
		lineageTag: 51457127-423c-430f-a8ec-fccdc25042bb

	measure 'ccnfColor PM Revenue' =
			
			VAR mom_growth = DIVIDE([CCNF Revenue] - [ccnfPPTotalRevenue],[ccnfPPTotalRevenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Revenue
		lineageTag: bf25e5ad-dd68-4f21-a2d5-ca9140a9c3b5

	measure 'ccnfColor PY Revenue' =
			
			VAR yoy_growth = DIVIDE([CCNF Revenue] - [ccnfPYTotalRevenue],[ccnfPYTotalRevenue])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Revenue
		lineageTag: 7ca38925-d675-4cee-ad44-471a2c9a2aad

	measure ccnfPYTotalUnqClick =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Unique Clicks],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			//  CALCULATE([CCNF Unique Clicks],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CCNF Unique Clicks
		lineageTag: 1dd5c880-cf35-472b-ba38-f72a14a15d87

	measure ccnfPPTotalUnqClick = CALCULATE([CCNF Unique Clicks],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CCNF Unique Clicks
		lineageTag: 334bccd0-e649-45d1-8791-ce0ffe8d04fa

	measure 'ccnfMOM TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [CCNF Unique Clicks] 
			VAR PPClick = [ccnfPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick,PPClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Clicks
		lineageTag: fdd4299e-3386-42ea-82ea-cee588bc7a74

	measure 'ccnfYOY TotalUnqClick Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [CCNF Unique Clicks] 
			VAR PYClick = [ccnfPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PYClick,PYClick)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Clicks
		lineageTag: 7a177209-6ebd-48a4-975c-c5341f576b9b

	measure 'ccnfColor PM UNQ Click' =
			
			VAR mom_click = DIVIDE([CCNF Unique Clicks] - [ccnfPPTotalUnqClick],[ccnfPPTotalUnqClick])
			RETURN
			    IF(mom_click<0, "red","green")
		displayFolder: CCNF Unique Clicks
		lineageTag: 8a28303f-e170-465a-a385-093839bcca93

	measure 'ccnfColor PY UNQ Click' =
			
			VAR yoy_click = DIVIDE([CCNF Unique Clicks] - [ccnfPYTotalUnqClick],[ccnfPYTotalUnqClick])
			RETURN
			    IF(yoy_click<0, "red","green")
		displayFolder: CCNF Unique Clicks
		lineageTag: 1d45f7f8-82b5-4f13-9074-090d46964263

	measure ccnfPPUnqOp = CALCULATE([CCNF Unique Opens],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CCNF Unique Opens
		lineageTag: 1b2590ba-1dfd-4f55-9b6a-6bf0267c62da

	measure ccnfPYUnqOp =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Unique Opens],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Unique Opens],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CCNF Unique Opens
		lineageTag: 2afa11bc-472f-418f-9919-3b53e23115bd

	measure 'ccnfMOM UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Unique Opens]
			VAR PPUNQOP= [ccnfPPUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Opens
		lineageTag: e374edd0-2275-4143-96c7-f2cd30cc48d7

	measure 'ccnfYoY UnqOp Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Unique Opens] 
			VAR PYUNQOP= [ccnfPYUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Opens
		lineageTag: a374f854-6605-4601-a2fb-03acca1f741a

	measure 'ccnfColor PM UNQOP' =
			
			VAR mom_growth = DIVIDE([CCNF Unique Opens] - [ccnfPPUnqOp],[ccnfPPUnqOp])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Unique Opens
		lineageTag: 1818d6ec-866d-4e4e-af8e-ff547a858f05

	measure 'ccnfColor PY UNQOP' =
			
			VAR yoy_growth = DIVIDE([CCNF Unique Opens] - [ccnfPYUnqOp],[ccnfPYUnqOp])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Unique Opens
		lineageTag: fb85fa0e-db67-41b0-8a60-21cf54188908

	measure ccnfPPTotalConversions = CALCULATE([CCNF Conversion],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CCNF Conversion
		lineageTag: 6e6cdaaf-fcdd-440e-ba45-8b252929478f

	measure ccnfPYTotalConversions =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Conversion],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Conversion],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CCNF Conversion
		lineageTag: 4f99944c-5553-4d05-ae88-31461c7be417

	measure 'ccnfMOM TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [CCNF Conversion] 
			VAR PPConversions = [ccnfPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PPConversions,PPConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Conversion
		lineageTag: b52c779d-af87-4719-a191-3769b4d264e8

	measure 'ccnfYOY TotalConversions Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [CCNF Conversion] 
			VAR PYConversions = [ccnfPYTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PYConversions,PYConversions)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Conversion
		lineageTag: b094a40d-24b3-414c-827a-8177f8d341c4

	measure 'ccnfColor PM Conversions' =
			
			VAR mom_growth = DIVIDE([CCNF Conversion] - [ccnfPPTotalConversions],[ccnfPPTotalConversions])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Conversion
		lineageTag: 165c89d1-273c-4909-ba17-ee2eff63da1e

	measure 'ccnfColor PY Conversions' =
			
			VAR yoy_growth = DIVIDE([CCNF Conversion]- [ccnfPYTotalConversions],[ccnfPYTotalConversions])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Conversion
		lineageTag: 34c0a23e-8984-4c5c-8d20-64e8ac2d1e2b

	measure ccnfPPDailyClickRate = CALCULATE([CCNF Click to receive rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCNF Click to receive rate
		lineageTag: e366d95e-0135-4398-9d46-b07d29c1245b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ccnfPYDailyClickRate =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Click to receive rate],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			
			// CALCULATE([CCNF Click to receive rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CCNF Click to receive rate
		lineageTag: 1fd9ed83-89c5-474f-b35c-6af33ef799a3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ccnfMOM DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [CCNF Click to receive rate] 
			VAR PPDailyClickRate = [ccnfPPDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PPDailyClickRate,PPDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Click to receive rate
		lineageTag: 998041fc-e790-4f25-bd77-d7766853a546

	measure 'ccnfYOY DailyClickRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentDailyClickRate = [CCNF Click to receive rate] 
			VAR PYDailyClickRate = [ccnfPYDailyClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate -PYDailyClickRate,PYDailyClickRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Click to receive rate
		lineageTag: 7b05d22a-e529-4349-9390-c5323d2443cd

	measure 'ccnfColor PM DailyClickRAte' =
			
			VAR mom_growth = DIVIDE([CCNF Click to receive rate] - [ccnfPPDailyClickRate],[ccnfPPDailyClickRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Click to receive rate
		lineageTag: 58aa78f1-eabc-4a52-b16f-bb7702dfe96a

	measure 'ccnfColor PY DailyClickRAte' =
			
			VAR yoy_growth = DIVIDE([CCNF Click to receive rate] - [ccnfPYDailyClickRate],[ccnfPYDailyClickRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Click to receive rate
		lineageTag: 04002994-47ef-4b61-b079-a486ae91a850

	measure ccnfPPTotalConversionsRate = CALCULATE([CCNF Conversion Rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCNF Conversion Rate
		lineageTag: 4dc67377-291d-469e-abe7-ff7a9d5b6934

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ccnfPYTotalConversionsRate =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Conversion Rate],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Conversion Rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CCNF Conversion Rate
		lineageTag: 20b6fb70-df7a-4ccf-a40e-bb869f7bf3b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ccnfMOM DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [CCNF Conversion Rate] 
			VAR PPConversionsRate = [ccnfPPTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PPConversionsRate,PPConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Conversion Rate
		lineageTag: 4f740dca-91d0-4249-8005-d367cea469b6

	measure 'ccnfYOY DailyConversionRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [CCNF Conversion Rate]
			VAR PYConversionsRate = [ccnfPYTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate - PYConversionsRate,PYConversionsRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Conversion Rate
		lineageTag: 0ce0f832-d877-468a-b289-0587bfecec71

	measure 'ccnfColor PM ConversionsRate' =
			
			VAR mom_growth = DIVIDE([CCNF Conversion Rate] - [ccnfPPTotalConversionsRate],[ccnfPPTotalConversionsRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Conversion Rate
		lineageTag: 2c7e5b2b-71d4-44a8-874b-75f86a1f2cea

	measure 'ccnfColor PY ConversionsRate' =
			
			VAR yoy_growth = DIVIDE([CCNF Conversion Rate] - [ccnfPYTotalConversionsRate],[ccnfPYTotalConversionsRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Conversion Rate
		lineageTag: d63bae62-fd18-41a6-b53a-8475fcaa80c8

	measure ccnfPPTotalUnsub = CALCULATE([CCNF Unsubscribe],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: CCNF Unsubscribed
		lineageTag: 50dfc8e2-1f2c-42f4-97ea-46801b6cfe9d

	measure ccnfPYTotalUnsub =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Unsubscribe],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Unsubscribe],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: CCNF Unsubscribed
		lineageTag: 1e576bcf-ffb1-4f4b-8f63-b98063653d1f

	measure 'ccnfMOM Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [CCNF Unsubscribe] 
			VAR PPUnsub = [ccnfPPTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PPUnsub,PPUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unsubscribed
		lineageTag: f00b42a3-e52c-4e81-a9eb-fc1054230ddd

	measure 'ccnfYOY Unsub Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [CCNF Unsubscribe] 
			VAR PYUnsub = [ccnfPYTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PYUnsub,PYUnsub)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unsubscribed
		lineageTag: 726cc591-1a1b-46ac-b3e7-3e52cb615213

	measure 'ccnfColor PM Unsub' =
			
			VAR mom_growth = DIVIDE([CCNF Unsubscribe] - [ccnfPPTotalUnsub],[ccnfPPTotalUnsub])
			RETURN
			    IF(mom_growth<0,  "green","red")
		displayFolder: CCNF Unsubscribed
		lineageTag: b9b003ff-b69a-4ed2-8283-4e1887f2b457

	measure 'ccnfColor PY Unsub' =
			
			VAR yoy_growth = DIVIDE([CCNF Unsubscribe] - [ccnfPYTotalUnsub],[ccnfPYTotalUnsub])
			RETURN
			    IF(yoy_growth<0,  "green","red")
		displayFolder: CCNF Unsubscribed
		lineageTag: 2ec0e7be-cbd1-499c-8fed-19b3709cb2c8

	measure ccnfPPTotalUnsubRate = CALCULATE([CCNF Unsubscribed Rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 4411183b-b932-45d2-ae25-bfbf6d55106f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure ccnfPYTotalUnsubRate =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF Unsubscribed Rate],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF Unsubscribed Rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 40ddd5ba-e069-43c8-9372-f2117106da7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ccnfMOM Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [CCNF Conversion Rate] 
			VAR PPUnsubRate = [ccnfPPTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PPUnsubRate,PPUnsubRate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 2751a651-de94-4a1a-9253-5df6b2e4f890

	measure 'ccnfYOY Unsub Rate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [CCNF Unsubscribed Rate] 
			VAR PYUnsubRate = [ccnfPYTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PYUnsubRate,PYUnsubRate)
			VAR Change = CurrentUnsubRate -PYUnsubRate
			RETURN 
			IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 0bd08449-fe74-45b3-8de7-a3d351bec28a

	measure 'ccnfColor PM UnsubRate' =
			
			VAR mom_growth = DIVIDE([CCNF Unsubscribed Rate] - [ccnfPPTotalUnsubRate],[ccnfPPTotalUnsubRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 5d4a22f7-4fdc-4862-a10a-d08c8a4e4cbd

	measure 'ccnfColor PY UnsubRate' =
			
			VAR yoy_growth = DIVIDE([CCNF Unsubscribed Rate] - [ccnfPYTotalUnsubRate],[ccnfPYTotalUnsubRate])
			RETURN
			    IF(yoy_growth<0,  "green","red")
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 9e9ad990-fd1b-40da-9c60-c9af2ce3de8c

	measure cAOV = DIVIDE([cREVENUE],[cCONVERSIONS])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCONVRATE
		lineageTag: 2540c234-0fea-4344-ae71-6f7055f25727

	measure FlowAOV = DIVIDE([FlowRevenue],[FlowConversion])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FlowMeasures
		lineageTag: 3f3f0445-4c24-4b76-890d-c8f17d0bf24b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure CampaignAOV = DIVIDE([CampaignRevenue],[CampaignConversion])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CampaignMeasures
		lineageTag: dbb80c40-5a2f-4563-af9b-723a74ceeb26

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure CCNFAOV = DIVIDE([CCNF Revenue],[CCNF Conversion])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCNF Measures
		lineageTag: aa2caa65-dd44-413c-904c-e054e3dd8cff

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure cPYUnqOpRt = CALCULATE([Open Rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CUNQOP
		lineageTag: 473f0205-77fd-478c-b6b3-1383b1d2e468

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cMOM UnqOprate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [Open Rate] 
			VAR PPUNQOPR= [cPPUnqOprate]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOPR,PPUNQOPR)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQOP
		lineageTag: 39960249-557a-41de-bbb2-34d16af8196f

	measure cPPUnqOprate = CALCULATE([Open Rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CUNQOP
		lineageTag: 63e80fe5-964e-4a47-8b12-d5de38bc27b8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cYoY UnqOpRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [Open Rate]
			VAR PYUNQOP= [cPYUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-[cPYUnqOpRt],[cPYUnqOpRt])
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CUNQOP
		lineageTag: 82821471-1305-4031-9018-95f9742fa7de

	measure 'cColor PM UNQOPRT' =
			
			VAR mom_growth = DIVIDE([Open Rate] - [cPPUnqOprate],[cPPUnqOprate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CUNQOP
		lineageTag: 9c3b4f1f-a5fd-4c44-82ad-7600f828a680

	measure 'cColor PY UNQOPRT' =
			
			VAR yoy_growth = DIVIDE([Open Rate] - [cPYUnqOpRt],[cPYUnqOpRt])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CUNQOP
		lineageTag: ab53c2f0-38fb-49e9-a453-c6e1a002dd4c

	measure 'Open Rate' = DIVIDE([cUNIQUE OPENS],[cRECIPIENTS])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CUNQOP
		lineageTag: 4b736f22-d18b-488c-913e-4949521251f7

	measure 'fMOM OpensRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowOpenRate] 
			VAR PPRecipients = [fPPUniqOpenRate]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQOP
		lineageTag: b56d1cde-b03e-45dc-841b-cf494ff5d91b

	measure fPPUniqOpenRate = CALCULATE([FlowOpenRate],DATESBETWEEN(DailyDimDate[Date],[dailystartofpreviousperiod],[dailyendofpreviousperiod]))
		displayFolder: FUNQOP
		lineageTag: daaf3b04-cfda-4cac-833c-620fe793a032

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'fYoY OpenRate Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [FlowOpenRate] 
			VAR PYRecipients = [fPYUnqOpenRate]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: FUNQOP
		lineageTag: 4451b9a6-d0e4-452a-b154-743b2301aae3

	measure fPYUnqOpenRate = CALCULATE([FlowOpenRate],DATEADD(DailyDimDate[Date],-1,YEAR))
		displayFolder: FUNQOP
		lineageTag: 3c439817-d1c4-4099-b2cc-8a4f2011b172

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'fColor PM UNQOPRT' =
			
			VAR mom_growth = DIVIDE([FlowOpenRate] - [fPPUniqOpenRate],[fPPUniqOpenRate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: FUNQOP
		lineageTag: 1463fd34-b228-44ac-98bb-903a8115ac9a

	measure 'fColor PY UNQOPRT' =
			
			VAR yoy_growth = DIVIDE([FlowOpenRate] - [fPYUnqOpenRate],[fPYUnqOpenRate])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: FUNQOP
		lineageTag: c6ba843f-cf3c-46fb-a8ac-c72e8a89af25

	measure 'CCNF OpenRate' = ```
			
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", DIVIDE([cUNIQUE OPENS], [cRECIPIENTS]),
			    "Flows",     DIVIDE([FlowUnqOpens], [FlowRecip]),
			    DIVIDE(
			        [cUNIQUE OPENS] + [FlowUnqOpens],
			        [cRECIPIENTS] + [FlowRecip]
			    )
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF Measures
		lineageTag: 01f8e935-a051-4d8d-b157-bb70f02d5b1f

	measure 'ccnfMOM OpRt Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PPUNQOP= [ccnfPPUnqOpRt]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Opens
		lineageTag: f0d68123-6690-46d3-875a-3524e3917920

	measure ccnfPPUnqOpRt = CALCULATE([CCNF OpenRate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: CCNF Unique Opens
		lineageTag: d548f995-f937-4593-894e-bb3c06ec069d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ccnfYoY OpRt Growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PYUNQOP= [ccnfPYUnqOpRt]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: CCNF Unique Opens
		lineageTag: bc6d7899-6f52-496d-8d10-1b9b41f7cd64

	measure ccnfPYUnqOpRt =
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [CCNF OpenRate],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE([CCNF OpenRate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: CCNF Unique Opens
		lineageTag: aeef4354-bccb-4858-a669-ccf38dc6b1ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ccnfColor PM UNQOPRT' =
			
			VAR mom_growth = DIVIDE([CCNF OpenRate] - [ccnfPPUnqOpRt],[ccnfPPUnqOpRt])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: CCNF Unique Opens
		lineageTag: 647c90e2-ed29-417d-a414-1529f5579511

	measure 'ccnfColor PY UNQOPRT' =
			
			VAR yoy_growth = DIVIDE([CCNF OpenRate] - [ccnfPYUnqOpRt],[ccnfPYUnqOpRt])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: CCNF Unique Opens
		lineageTag: 48e42993-77be-4a1a-93b5-d7633da568f4

	measure cform_submission = SUM(form[form_submissions])
		formatString: #,0
		displayFolder: Form
		lineageTag: d2741125-5f4d-4d65-a7e6-27f067463ada

	measure cform_views = SUM(form[form_views])
		formatString: #,0
		displayFolder: Form
		lineageTag: 32ccd633-67c9-4d46-81a7-2c53df7ed185

	measure cPPform_submission = CALCULATE([cform_submission],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Form
		lineageTag: 573bd3b1-2a0b-454d-ae48-4c594ba1a41a

	measure cPPform_views = CALCULATE([cform_views],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Form
		lineageTag: 0a5d209d-2da7-4869-b563-2671441178fb

	measure cPYform_submission = CALCULATE([cform_submission],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Form
		lineageTag: 0d607c7a-4956-4387-a5d3-d491ef0912e8

	measure cPYform_views = CALCULATE([cform_views],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Form
		lineageTag: 544aff12-e1e1-448b-b073-68f92be7de10

	measure 'cMOM form submission growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_form_submission = [cform_submission] 
			VAR PP_form_submission = [cPPform_submission]
			VAR Growth = DIVIDE(current_form_submission -PP_form_submission,PP_form_submission)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: 4095c136-8024-4752-a1b5-9824f6efb254

	measure 'cMOM form views growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_form_views = [cform_views] 
			VAR PP_form_views = [cPPform_views]
			VAR Growth = DIVIDE(current_form_views -PP_form_views,PP_form_views)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: 09695258-071d-4e82-be91-89a73971bc02

	measure 'cYOY form submission growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_form_submission = [cform_submission] 
			VAR PY_form_submission = [cPYform_submission]
			VAR Growth = DIVIDE(current_form_submission -PY_form_submission,PY_form_submission)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: ca886546-10fd-4040-9f14-8814b8d34882

	measure 'cYOY form views growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_form_views = [cform_views] 
			VAR PY_form_views = [cPYform_views]
			VAR Growth = DIVIDE(current_form_views -PY_form_views,PY_form_views)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: 3910ce1d-6aa2-4a2d-bfd1-28f17f521d02

	measure csubmit_rate_form = DIVIDE([cform_submission],[cform_views])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Form
		lineageTag: 6845b108-0dc3-4277-9a2c-25abe985c01b

	measure cPPsubmit_rate_form = CALCULATE([csubmit_rate_form],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Form
		lineageTag: 176dd768-2149-4e5e-bd11-470b4c54427a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure cPYsubmit_rate_form = CALCULATE([csubmit_rate_form],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Form
		lineageTag: 2bd8e9f7-d85a-4ca2-b4c2-953678b394df

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cMOM submit rate form growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_submit_rate_form = [csubmit_rate_form] 
			VAR PP_submit_rate_form = [cPPsubmit_rate_form]
			VAR Growth = DIVIDE(current_submit_rate_form -PP_submit_rate_form,PP_submit_rate_form)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: 5f244c1d-c0bd-4238-b3e4-26de83a1ff99

	measure 'cYOY submit rate form growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_submit_rate_form = [csubmit_rate_form] 
			VAR PY_submit_rate_form = [cPYsubmit_rate_form]
			VAR Growth = DIVIDE(current_submit_rate_form -PY_submit_rate_form,PY_submit_rate_form)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Form
		lineageTag: 9d36d2a4-024e-4fcf-9bef-5a3d231657cf

	measure 'cColor PM form views' =
			
			VAR mom_growth = DIVIDE([cform_views] - [cPPform_views],[cPPform_views])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: a1249481-4d99-48aa-93a4-cf19d7cb1cea

	measure 'cColor PM form submission' =
			
			VAR mom_growth = DIVIDE([cform_submission] - [cPPform_submission],[cPPform_submission])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: 9b38b5ec-ff34-445c-8d9b-735de8f3db9a

	measure 'cColor PM submit rate form' =
			
			VAR mom_growth = DIVIDE([csubmit_rate_form] - [cPPsubmit_rate_form],[cPPsubmit_rate_form])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: edd3f4a2-101b-49c1-84e4-a0b80462dc6d

	measure 'cColor PY form submission' =
			
			VAR mom_growth = DIVIDE([cform_submission] - [cPYform_submission],[cPYform_submission])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: 9c27749f-59b3-4895-801f-35b9e46e21b4

	measure 'cColor PY form views' =
			
			VAR mom_growth = DIVIDE([cform_views] - [cPYform_views],[cPYform_views])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: d26cc9e5-03f0-4843-8919-357ac1ffba19

	measure 'cColor PY submit rate form' =
			
			VAR mom_growth = DIVIDE([csubmit_rate_form] - [cPYsubmit_rate_form],[cPYsubmit_rate_form])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Form
		lineageTag: 81cf9189-e6d1-4dea-904f-3870778ad4a0

	measure 'Campaign OpenRateMTD' = DIVIDE([Campaign UniqueOpenMTD],[Campaign RecipMTD])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Campaign MTD
		lineageTag: ef66e646-9649-4358-a72e-c62f25c5b505

	measure 'COpenRate 4WA' = DIVIDE([CUnique OpenEmail 4WA],[CRecip 4WA])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Campaign 4 WA
		lineageTag: e268e0fd-379f-4329-9ebb-86e6ccb30bea

	measure 'FlowOpen Rate 4WA' = DIVIDE([FlowUnique Opens 4WA],[FlowRecip 4WA])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: FLow 4 Week Average
		lineageTag: ae2a0ee2-e6dd-4896-b1ff-c5b151d34c91

	measure 'FCurrent Week Open Rate' = DIVIDE([FCurrent Week Unique Opens],[FCurrent Week Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow Current Week
		lineageTag: ba11140e-11a7-4b11-8b9d-082ae9cc6749

	measure 'FOpen Rate 4WA' = DIVIDE([FUnq Opens 4WA],[FRecip 4WA])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow 4 WA
		lineageTag: a37b76fc-d3b6-4272-841a-92b5b1b7bdfe

	measure 'CCNFOpen Rate 4WA' = DIVIDE([CCNFUnique Opens 4WA],[CCNFRecip 4WA])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF 4 Week Average
		lineageTag: 503ccbff-9dc5-4535-bffc-0e66b09eefda

	measure 'No of Campaigns' = CALCULATE(DISTINCTCOUNT(campaign[Campaign Name]),FILTER(campaign,[cRECIPIENTS] > 0))
		formatString: 0
		displayFolder: CampaignMeasures
		lineageTag: 3b7d96e8-a66a-432a-99b7-39bee245afb0

	measure 'FM Total Opens' = SUM('flow message'[Total Opens])
		formatString: 0
		displayFolder: Flow message Measures
		lineageTag: 99dd3755-eb2a-434b-a531-d0f4b6fbc464

	measure 'FM Recipients' = SUM('flow message'[Total Recipients])
		formatString: #,0
		displayFolder: Flow message Measures
		lineageTag: 305f7e07-17e5-4261-97bf-cd783e7eaf9c

	measure 'FM Total Clicks' = SUM('flow message'[Total Clicks])
		formatString: 0
		displayFolder: Flow message Measures
		lineageTag: e2566b67-4b61-461e-845e-b74ffe42d4c0

	measure 'FM Unique Clicks' = SUM('flow message'[Unique Clicks])
		formatString: #,0
		displayFolder: Flow message Measures
		lineageTag: 139e95a0-1989-455c-ae0c-291c64d5565f

	measure 'FM Unique Opens' = SUM('flow message'[Unique Opens])
		formatString: #,0
		displayFolder: Flow message Measures
		lineageTag: dcba2319-cef7-4570-b348-a5ae366cd2ae

	measure 'FM Unique Unsubscribes' = SUM('flow message'[Unique Unsubscribes])
		formatString: 0
		displayFolder: Flow message Measures
		lineageTag: 2ee568db-7db0-4351-a7ee-61dde8d9c28f

	measure 'FM Unsubscribed' = SUM('flow message'[Total Unsubscribes])
		formatString: 0
		displayFolder: Flow message Measures
		lineageTag: c4b36418-b4d6-4282-9b3b-716fffdfd52e

	measure 'FM Revenue' = SUM('flow message'[Total Placed Order Value])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Flow message Measures
		lineageTag: cdffd8cb-3091-46ea-97e5-95d202b64d7a

	measure 'FM Orders' = SUM('flow message'[Total Placed Order])
		formatString: #,0
		displayFolder: Flow message Measures
		lineageTag: c1b3cbca-731c-4d3d-8db9-25219004a0e5

	measure 'FM Conv. Rate' = DIVIDE([FM Orders] , [FM Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow message Measures
		lineageTag: 5b88deba-5b7d-4329-9460-a2587792002a

	measure 'FM Avg. Order Value' = DIVIDE([FM Revenue] , [FM Orders])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Flow message Measures
		lineageTag: 5a74a6e9-cd55-4524-88e2-e27c0240eea4

	measure 'FM Open Rate' = DIVIDE([FM Unique Opens] , [FM Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow message Measures
		lineageTag: 28a0df25-1def-4b2c-8094-8a1f601564bd

	measure 'FM Click Rate' = DIVIDE([FM Total Clicks], [FM Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow message Measures
		lineageTag: fbeeef38-297c-40af-90d3-2d6f031e2d14

	measure 'FlowNo of Flows' = CALCULATE(DISTINCTCOUNT(flow[Flow Name]),FILTER(flow,[FlowRecip] > 0))
		formatString: 0
		displayFolder: FlowMeasures
		lineageTag: 28c784fb-954e-4ff3-a19e-d44857cd70ff

	measure 'CCNF No of Mailings' = [No of Campaigns] + [FlowNo of Flows]
		formatString: 0
		displayFolder: CCNF Measures
		lineageTag: 16d1a412-e196-4008-8614-e0224e437e3e

	measure cSMS_Revenue = SUM('SMS Campaigns'[Total Placed Order Value])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: SMS Campaigns
		lineageTag: b6f4e055-2ccd-41fa-8ad4-ce2d9d286251

	measure cSMS_Recipients = SUM('SMS Campaigns'[Total Recipients])
		formatString: #,0
		displayFolder: SMS Campaigns
		lineageTag: 131d7398-e5b7-407c-8f99-f28049a104dc

	measure cSMS_Unique_Clicks = SUM('SMS Campaigns'[Unique Clicks])
		formatString: #,0
		displayFolder: SMS Campaigns
		lineageTag: 0c1eaec1-46e3-4e13-b2cc-74661b1b8ce1

	measure cSMS_Orders = SUM('SMS Campaigns'[Total Placed Order])
		formatString: #,0
		displayFolder: SMS Campaigns
		lineageTag: 7227ea3d-cc40-4d9d-8dd2-b28f4d37f124

	measure cSMS_Unsubscribe = SUM('SMS Campaigns'[Total Unsubscribes])
		formatString: #,0
		displayFolder: SMS Campaigns
		lineageTag: 4dab9648-c131-47b2-82f3-56995469b6f2

	measure cSMS_Click_rate = DIVIDE([cSMS_Unique_Clicks],[cSMS_Recipients])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: SMS Campaigns
		lineageTag: da3203bf-0b5a-42ca-9658-61fbed81a9a3

	measure cSMS_Conversion_rate = DIVIDE([cSMS_Orders],[cSMS_Recipients])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: SMS Campaigns
		lineageTag: 5d8a1f27-0c9d-4a75-9bc2-ac60fe38e6f2

	measure cSMS_Unsubscribe_rate = DIVIDE([cSMS_Unsubscribe],[cSMS_Recipients])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		displayFolder: SMS Campaigns
		lineageTag: 3c8e3768-0d78-4853-85f0-7c72e98b0452

	measure 'cPPSMS Click rate' = CALCULATE([cSMS_Click_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: SMS Campaigns
		lineageTag: e7785c8e-2f45-43f9-803c-47ef7a5c4a19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSMS Conversion rate' = CALCULATE([cSMS_Conversion_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: SMS Campaigns
		lineageTag: d3a307d9-b837-4032-b8d4-d75235b44154

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSMS Orders' = CALCULATE([cSMS_Orders],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: 7ddb1161-5b54-4fa9-a1e7-a19706e810ad

	measure 'cPPSMS Recipients' = CALCULATE([cSMS_Recipients],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: f55e2612-7258-41ea-8394-9c6cdcec8aa0

	measure 'cPPSMS Revenue' = CALCULATE([cSMS_Revenue],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: SMS Campaigns
		lineageTag: 78505b17-555a-407f-bf72-d1645a0dda05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSMS Unique clicks' = CALCULATE([cSMS_Unique_Clicks],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: ac0e0946-e42d-44d9-a28b-16df2bf6530c

	measure 'cPPSMS Unsubscribe rate' = CALCULATE([cSMS_Unsubscribe_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: SMS Campaigns
		lineageTag: ef836d0b-21d2-4be5-9c98-adacfa230c9d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSMS Unsubscribe' = CALCULATE([cSMS_Unsubscribe],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: fda30f4e-6656-4157-91b2-0dcf03ed93b7

	measure 'cPYSMS Click rate' = CALCULATE([cSMS_Click_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: SMS Campaigns
		lineageTag: 2a2a8e89-a696-4a77-8e05-c6b909bc281a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSMS Conversion rate' = CALCULATE([cSMS_Conversion_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: SMS Campaigns
		lineageTag: a12dba79-044d-43d7-92e8-2d4b23356bcf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSMS Orders' = CALCULATE([cSMS_Orders],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: 15c2a515-f56f-41f3-8c39-10cee429bdb2

	measure 'cPYSMS Recipients' = CALCULATE([cSMS_Recipients],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: d9fdad42-3ec3-4e73-804c-0d2a1b75190e

	measure 'cPYSMS Revenue' = CALCULATE([cSMS_Revenue],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: SMS Campaigns
		lineageTag: c23668d0-15dd-4009-b4e6-742c778397a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSMS Unique Clicks' = CALCULATE([cSMS_Unique_Clicks],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: 7ede012d-e0cb-445a-bfbf-c93069a8a35c

	measure 'cPYSMS Unsubscribe rate' = CALCULATE([cSMS_Unsubscribe_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: SMS Campaigns
		lineageTag: d81480d8-56c3-4a7e-964f-4c09e03e0d28

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSMS Unsubscribe' = CALCULATE([cSMS_Unsubscribe],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: ef8b6176-cac9-4999-8fdb-ee0ece057e84

	measure 'cMOM SMS Click_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Click_rate = [cSMS_Click_rate] 
			VAR PP_Click_rate = [cPPSMS Click rate]
			VAR Growth = DIVIDE(current_Click_rate -PP_Click_rate,PP_Click_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 8d6b83e8-6d75-4770-b283-6bf77f870ad4

	measure 'cMOM SMS Conversion_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Conversion_rate = [cSMS_Conversion_rate] 
			VAR PP_Conversion_rate = [cPPSMS Conversion rate]
			VAR Growth = DIVIDE(current_Conversion_rate - PP_Conversion_rate,PP_Conversion_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 62a7eed7-6be8-4a3f-aa0b-0f9ec0fa4eed

	measure 'cMOM SMS Orders growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Orders = [cSMS_Orders] 
			VAR PP_Orders = [cPPSMS Orders]
			VAR Growth = DIVIDE(current_Orders - PP_Orders,PP_Orders)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: ded3802a-e797-4a00-accc-54e4592edb4a

	measure 'cMOM SMS Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [cSMS_Recipients] 
			VAR PP_Recipients = [cPPSMS Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 4a79d32b-572c-4b86-8b2c-9577ef59d810

	measure 'cMOM SMS Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Revenue = [cSMS_Revenue] 
			VAR PP_Revenue = [cPPSMS Revenue]
			VAR Growth = DIVIDE(current_Revenue -PP_Revenue,PP_Revenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 0f7391a7-65da-434b-b494-f82c5d2bed3f

	measure 'cMOM SMS Unique_Clicks growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Clicks = [cSMS_Unique_Clicks]
			VAR PP_Unique_Clicks = [cPPSMS Unique clicks]
			VAR Growth = DIVIDE(current_Unique_Clicks - PP_Unique_Clicks,PP_Unique_Clicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 78ed5ef0-a9ab-459f-889a-1ddd24af1919

	measure 'cMOM SMS Unsubscribe_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe_rate = [cSMS_Unsubscribe_rate] 
			VAR PP_Unsubscribe_rate = [cPPSMS Unsubscribe rate]
			VAR Growth = DIVIDE(current_Unsubscribe_rate - PP_Unsubscribe_rate,PP_Unsubscribe_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: d7cf37a1-26f1-489d-98a7-c2c10fae8e33

	measure 'cMOM SMS Unsubscribe growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe = [cSMS_Unsubscribe]
			VAR PP_Unsubscribe = [cPPSMS Unsubscribe]
			VAR Growth = DIVIDE(current_Unsubscribe - PP_Unsubscribe,PP_Unsubscribe)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: c5234cbc-69bf-4b79-b1bc-ce2e927b0da3

	measure 'cYOY SMS Click_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Click_rate = [cSMS_Click_rate] 
			VAR PY_Click_rate = [cPYSMS Click rate]
			VAR Growth = DIVIDE(current_Click_rate - PY_Click_rate,PY_Click_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 41d90268-77e5-419f-9656-b774abbc0a2e

	measure 'cYOY SMS Conversion_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Conversion_rate = [cSMS_Conversion_rate] 
			VAR PY_Conversion_rate = [cPYSMS Conversion rate]
			VAR Growth = DIVIDE(current_Conversion_rate - PY_Conversion_rate,PY_Conversion_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 0bb448e9-4dec-4971-afda-46bdc54c9045

	measure 'cYOY SMS Orders growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Orders = [cSMS_Orders] 
			VAR PY_Orders = [cPYSMS Orders]
			VAR Growth = DIVIDE(current_Orders - PY_Orders,PY_Orders)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 4f4f7bda-5b66-4b0f-98aa-7958078cbad6

	measure 'cYOY SMS Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [cSMS_Recipients] 
			VAR PY_Recipients = [cPYSMS Recipients]
			VAR Growth = DIVIDE(current_Recipients - PY_Recipients,PY_Recipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: bfac4698-c0b2-4489-a14a-35b3e317cc6e

	measure 'cYOY SMS Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Revenue = [cSMS_Revenue] 
			VAR PY_Revenue = [cPYSMS Revenue]
			VAR Growth = DIVIDE(current_Revenue - PY_Revenue,PY_Revenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 7f04ff29-fcfb-465d-a62c-a7dd87576a4e

	measure 'cYOY SMS Unique_Clicks growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Clicks = [cSMS_Unique_Clicks]
			VAR PY_Unique_Clicks = [cPYSMS Unique clicks]
			VAR Growth = DIVIDE(current_Unique_Clicks - PY_Unique_Clicks,PY_Unique_Clicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: d6dba175-f384-4e22-b10c-41188a6be383

	measure 'cYOY SMS Unsubscribe growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe = [cSMS_Unsubscribe]
			VAR PY_Unsubscribe = [cPYSMS Unsubscribe]
			VAR Growth = DIVIDE(current_Unsubscribe - PY_Unsubscribe,PY_Unsubscribe)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: eb624f90-2a97-4e1c-8378-c0b6558e0e9d

	measure 'cYOY SMS Unsubscribe_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe_rate = [cSMS_Unsubscribe_rate] 
			VAR PY_Unsubscribe_rate = [cPYSMS Unsubscribe rate]
			VAR Growth = DIVIDE(current_Unsubscribe_rate - PY_Unsubscribe_rate,PY_Unsubscribe_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: d6bdd10f-14f5-4bde-832a-d7d413ac684d

	measure 'cColor PM SMS Click rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Click_rate] - [cPPSMS Click rate],[cPPSMS Click rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 274ddb06-7683-4c7a-a8c8-82a66fba82c6

	measure 'cColor PM SMS Conversion rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Conversion_rate] - [cPPSMS Conversion rate],[cPPSMS Conversion rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: ff3b1b8e-0c85-46c4-9186-397d603dbcde

	measure 'cColor PM SMS Orders' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Orders] - [cPPSMS Orders],[cPPSMS Orders])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 78a4f492-83a2-4afa-9667-1573da9d2736

	measure 'cColor PM SMS Recipients' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Recipients] - [cPPSMS Recipients],[cPPSMS Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 05ac9402-c7b5-467b-9ed1-3cc3161d9081

	measure 'cColor PM SMS Revenue' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Revenue] - [cPPSMS Revenue],[cPPSMS Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 4245c919-47ad-495c-88bc-62974405222a

	measure 'cColor PM SMS Unique clicks' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unique_Clicks] - [cPPSMS Unique clicks],[cPPSMS Unique clicks])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 8de485d9-228e-4c3b-86b4-7f7055ae4b4e

	measure 'cColor PM SMS Unsubscribe' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unsubscribe] - [cPPSMS Unsubscribe],[cPPSMS Unsubscribe])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 324fa8b7-091c-45aa-bf73-474dea67e85c

	measure 'cColor PM SMS Unsubscribe rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unsubscribe_rate] - [cPPSMS Unsubscribe rate],[cPPSMS Unsubscribe rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 5a157e0c-154a-464b-adc9-eaaaec2525a8

	measure 'cColor PY SMS Click rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Click_rate] - [cPYSMS Click rate],[cPYSMS Click rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 9f605c0b-6212-4ff6-84bf-e3db2e091800

	measure 'cColor PY SMS Conversion rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Conversion_rate] - [cPYSMS Conversion rate],[cPYSMS Conversion rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: bf9b72fa-b659-4946-b9c3-2ce5dc6e32bb

	measure 'cColor PY SMS Orders' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Orders] - [cPYSMS Orders],[cPYSMS Orders])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: c6e3ca72-32b5-4890-ae0a-daa4a6b0a2b3

	measure 'cColor PY SMS Recipients' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Recipients] - [cPYSMS Recipients],[cPYSMS Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 2422d463-9c2e-4186-8f62-d4ecf735cdc2

	measure 'cColor PY SMS Revenue' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Revenue] - [cPYSMS Revenue],[cPYSMS Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: f3aa385e-7965-4c26-80f4-ab9202396634

	measure 'cColor PY SMS Unique clicks' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unique_Clicks] - [cPYSMS Unique clicks],[cPYSMS Unique clicks])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 84b6ae04-3927-43a2-bae2-6d3ebbbd3f0c

	measure 'cColor PY SMS Unsubscribe' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unsubscribe] - [cPYSMS Unsubscribe],[cPYSMS Unsubscribe])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: c3542307-3384-49a4-a0a0-7cb01b9bd486

	measure 'cColor PY SMS Unsubscribe rate' = ```
			
			VAR mom_growth = DIVIDE([cSMS_Unsubscribe_rate] - [cPYSMS Unsubscribe rate],[cPYSMS Unsubscribe rate])
			RETURN
			    IF(mom_growth<0, "red","green")
			
			```
		displayFolder: SMS Campaigns
		lineageTag: 5601b818-d790-44df-903f-4127bf10da11

	measure cSMS_Failed_to_Deliver_SMS = SUM('SMS Campaigns'[Failed to Deliver SMS])
		formatString: #,0
		displayFolder: SMS Campaigns
		lineageTag: 23285277-19e1-4ebf-a127-fe51cd01f638

	measure 'cPPSMS Failed to Deliver SMS' = CALCULATE([cSMS_Failed_to_Deliver_SMS],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: b0e58b2a-3f5a-4064-8e5a-a5ac1488bc38

	measure 'cPYSMS Failed to Deliver SMS' = CALCULATE([cSMS_Failed_to_Deliver_SMS],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: SMS Campaigns
		lineageTag: 64528290-7cb0-4f7f-ad90-1964f1846257

	measure 'cMOM SMS Failed to Deliver SMS growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Failed_to_Deliver_SMS = [cSMS_Failed_to_Deliver_SMS] 
			VAR PP_Failed_to_Deliver_SMS = [cPPSMS Failed to Deliver SMS]
			VAR Growth = DIVIDE(current_Failed_to_Deliver_SMS - PP_Failed_to_Deliver_SMS,PP_Failed_to_Deliver_SMS)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: e1fbd067-90bb-48e0-8d88-d4434fea7f44

	measure 'cYOY SMS Failed to Deliver SMS growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Failed_to_Deliver_SMS = [cSMS_Failed_to_Deliver_SMS] 
			VAR PY_Failed_to_Deliver_SMS = [cPYSMS Failed to Deliver SMS]
			VAR Growth = DIVIDE(current_Failed_to_Deliver_SMS - PY_Failed_to_Deliver_SMS,PY_Failed_to_Deliver_SMS)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: SMS Campaigns
		lineageTag: 069d4ce8-1133-4ee5-b944-20eedf389dc5

	measure 'cColor PM SMS Failed to Deliver SMS' =
			
			VAR mom_growth = DIVIDE([cSMS_Failed_to_Deliver_SMS] - [cPPSMS Failed to Deliver SMS],[cPPSMS Failed to Deliver SMS])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: SMS Campaigns
		lineageTag: ecf3e774-4780-4f6f-92e0-6aac2df725aa

	measure 'cColor PY SMS Failed to Deliver SMS' =
			
			VAR yoy_growth = DIVIDE([cSMS_Failed_to_Deliver_SMS] - [cPYSMS Failed to Deliver SMS],[cPYSMS Failed to Deliver SMS])
			RETURN
			    IF(yoy_growth<0, "red","green")
		displayFolder: SMS Campaigns
		lineageTag: 1adb312e-8ae8-43d2-a471-a0288d7edfb6

	measure cSG_Recipients = SUM('Segment Data'[Total Recipients])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: 7e873f6c-c658-48b2-b9f1-772766bf46bf

	measure cSG_Unique_Clicks = SUM('Segment Data'[Unique Clicks])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: d336e0df-ed06-437f-8eea-51606ce58803

	measure cSG_Unique_Opens = SUM('Segment Data'[Unique Opens])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: caf82a62-ef43-4831-9198-4978e38ee64f

	measure cSG_Email_Bounces = SUM('Segment Data'[Bounces])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: 08297ef6-26a2-4aa8-a546-976978d0c214

	measure cSG_Unique_Unsubscribes = SUM('Segment Data'[Unique Unsubscribes])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: 459f4f5b-fdff-4d91-af5a-2707e670d410

	measure cSG_Spam_Complaints = SUM('Segment Data'[Spam Complaints])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: d3eb778c-ceb7-40ef-9b5b-aae6dda4391c

	measure cSG_Orders = SUM('Segment Data'[Total Placed Order])
		formatString: #,0
		displayFolder: Segment Data
		lineageTag: 369885bd-c0ac-4332-a31b-4e08bfb679af

	measure cSG_Revenue = SUM('Segment Data'[Total Placed Order Value])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Segment Data
		lineageTag: a2b00701-c91c-431b-9fa7-907c2ef50d8b

	measure cSG_Unsubscribe_rate = DIVIDE([cSG_Unique_Unsubscribes],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: 743ecf06-8937-4324-b93d-32e56ea6d542

	measure cSG_Click_rate = DIVIDE([cSG_Unique_Clicks],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: dd0a3517-b491-449b-9dac-628ce515823d

	measure cSG_Open_rate = DIVIDE([cSG_Unique_Opens],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: 8c870c24-dabe-4534-8fc1-74a5fea4f40b

	measure cSG_Spam_complaints_rate = DIVIDE([cSG_Spam_Complaints],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: 50ca3b46-0b81-4038-bd48-58c6a2a9bc16

	measure cSG_Email_bounces_rate = DIVIDE([cSG_Email_Bounces],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: 11f2bfc8-3cfb-4ab3-bebf-a14fbc4db028

	measure cSG_Conversion_rate = DIVIDE([cSG_Orders],[cSG_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data
		lineageTag: b1858259-5094-43cb-b774-6197110027c3

	measure 'cPPSG Recipients' = CALCULATE([cSG_Recipients],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 5c215157-cfee-40df-b3ce-b5a614c975ed

	measure 'cPPSG Click_rate' = CALCULATE([cSG_Click_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: 20fa3767-852d-4e23-b551-ce0194406ce4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Conversion_rate' = CALCULATE([cSG_Conversion_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: 3e11300b-5fdb-4c53-bd27-4395f9a147b0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Email_Bounces' = CALCULATE([cSG_Email_Bounces],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 1477b5c7-76ba-4131-ad2a-d13b94504b24

	measure 'cPPSG Email_bounces_rate' = CALCULATE([cSG_Email_bounces_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: 7a429ff4-4e0f-4dfd-b23f-388af013b583

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Open_rate' = CALCULATE([cSG_Open_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: 5d18c53d-f74b-46c7-a0eb-74f90693671d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Orders' = CALCULATE([cSG_Orders],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: f8c18dc5-7f29-4494-8461-13a820589193

	measure 'cPPSG Revenue' = CALCULATE([cSG_Revenue],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: b27f6443-0ad5-40c6-9b2e-cece391c849f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Spam_Complaints' = CALCULATE([cSG_Spam_Complaints],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: beed6da4-54d0-486b-9155-5579e0a4fdfa

	measure 'cPPSG Spam_complaints_rate' = CALCULATE([cSG_Spam_complaints_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: abe2f658-228a-41a7-b1a9-315bbb9b06bd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPPSG Unique_Clicks' = CALCULATE([cSG_Unique_Clicks],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 399d1c94-896e-4aeb-b566-251e458d761e

	measure 'cPPSG Unique_Opens' = CALCULATE([cSG_Unique_Opens],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: f56a1a11-3b89-4fc2-9b5f-e5fa38ecaa13

	measure 'cPPSG Unique_Unsubscribes' = CALCULATE([cSG_Unique_Unsubscribes],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 764c7a7a-3e52-45fa-b2bc-bc2541c51e03

	measure 'cPPSG Unsubscribe_rate' = CALCULATE([cSG_Unsubscribe_rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Segment Data
		lineageTag: 5b335215-8692-489e-af6b-551e7f1fccd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Click_rate' = CALCULATE([cSG_Click_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: fc202236-17c0-4894-a9cc-38755c305b32

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Conversion_rate' = CALCULATE([cSG_Conversion_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: cbd0d932-2f3d-42ef-8f85-634246e0be5a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Email_Bounces' = CALCULATE([cSG_Email_Bounces],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: ce159732-bf26-4a0a-8c33-b8498cb555fc

	measure 'cPYSG Email_bounces_rate' = CALCULATE([cSG_Email_bounces_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: 5ff3ea73-c74b-4676-8292-141867ddb550

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Open_rate' = CALCULATE([cSG_Open_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: 94f6f976-88f0-43a2-9a16-deecbb72dbee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Orders' = CALCULATE([cSG_Orders],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 46f60aef-23ef-41c8-9931-dfc5d49b62fd

	measure 'cPYSG Recipients' = CALCULATE([cSG_Recipients],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 963127f3-4922-4d47-a38b-e49a8c8f9982

	measure 'cPYSG Revenue' = CALCULATE([cSG_Revenue],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: cfc7ffbc-03e7-4886-bbf3-5089441c280e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Spam_Complaints' = CALCULATE([cSG_Spam_Complaints],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 8c7c5dae-a828-47d4-900c-aaf4b3a1d925

	measure 'cPYSG Unique_Clicks' = CALCULATE([cSG_Unique_Clicks],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: c3d63aac-aa74-40e3-92a2-57f6058f2c02

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Spam_complaints_rate' = CALCULATE([cSG_Spam_complaints_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: 12a013b3-11d9-4a2b-8395-166d6394cdaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cPYSG Unique_Opens' = CALCULATE([cSG_Unique_Opens],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: 865335b4-970e-4c30-abe2-d68a0bee722c

	measure 'cPYSG Unique_Unsubscribes' = CALCULATE([cSG_Unique_Unsubscribes],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Segment Data
		lineageTag: e61f0503-33ca-49d9-9b2b-2f28054c2623

	measure 'cPYSG Unsubscribe_rate' = CALCULATE([cSG_Unsubscribe_rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Segment Data
		lineageTag: 7b8675d3-a3df-40b0-b8dd-2e5e691fc482

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'cMOM SG Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [cSG_Recipients] 
			VAR PP_Recipients = [cPPSG Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 171455c4-6c2d-4d2c-9133-d42ecffbf254

	measure 'cMOM SG Click_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Click_rate = [cSG_Click_rate] 
			VAR PP_Click_rate = [cPPSG Click_rate]
			VAR Growth = DIVIDE(current_Click_rate - PP_Click_rate,PP_Click_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 547e8c53-6082-40db-899c-a1ec442d1474

	measure 'cMOM SG Conversion_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Conversion_rate = [cSG_Conversion_rate]
			VAR PP_Conversion_rate = [cPPSG Conversion_rate]
			VAR Growth = DIVIDE(current_Conversion_rate - PP_Conversion_rate,PP_Conversion_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 41d423e2-7d3d-4c31-9f00-25426a154de6

	measure 'cMOM SG Email_Bounces growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Email_Bounces = [cSG_Email_Bounces]
			VAR PP_Email_Bounces = [cPPSG Email_Bounces]
			VAR Growth = DIVIDE(current_Email_Bounces - PP_Email_Bounces,PP_Email_Bounces)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: a1279940-b225-458a-b5b5-12fe648465b4

	measure 'cMOM SG Email_bounces_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Email_bounces_rate = [cSG_Email_bounces_rate]
			VAR PP_Email_bounces_rate = [cPPSG Email_bounces_rate]
			VAR Growth = DIVIDE(current_Email_bounces_rate - PP_Email_bounces_rate,PP_Email_bounces_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: d61898eb-c72e-4fbe-920a-46c50c51d56e

	measure 'cMOM SG Open_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Open_rate = [cSG_Open_rate]
			VAR PP_Open_rate = [cPPSG Open_rate]
			VAR Growth = DIVIDE(current_Open_rate - PP_Open_rate,PP_Open_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: ddf5ce4c-11ce-4df5-b6d9-57cd0789bfc0

	measure 'cMOM SG Orders growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Orders = [cSG_Orders]
			VAR PP_Orders = [cPPSG Orders]
			VAR Growth = DIVIDE(current_Orders - PP_Orders,PP_Orders)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: a202aedd-f25a-4267-ac91-1fd81220d3b5

	measure 'cMOM SG Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Revenue = [cSG_Revenue]
			VAR PP_Revenue = [cPPSG Revenue]
			VAR Growth = DIVIDE(current_Revenue - PP_Revenue,PP_Revenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 47c0c6c7-d976-4fae-abf4-8ce3d7cf4cca

	measure 'cMOM SG Spam_Complaints growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Spam_Complaints = [cSG_Spam_Complaints]
			VAR PP_Spam_Complaints = [cPPSG Spam_Complaints]
			VAR Growth = DIVIDE(current_Spam_Complaints - PP_Spam_Complaints,PP_Spam_Complaints)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: b46a9e89-68b3-4b50-9563-6cf86facf356

	measure 'cMOM SG Spam_complaints_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Spam_complaints_rate = [cSG_Spam_complaints_rate]
			VAR PP_Spam_complaints_rate = [cPPSG Spam_complaints_rate]
			VAR Growth = DIVIDE(current_Spam_complaints_rate - PP_Spam_complaints_rate,PP_Spam_complaints_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 657a8527-f015-46ca-b9a1-34e14a0291c1

	measure 'cMOM SG Unique_Clicks growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Clicks = [cSG_Unique_Clicks]
			VAR PP_Unique_Clicks = [cPPSG Unique_Clicks]
			VAR Growth = DIVIDE(current_Unique_Clicks - PP_Unique_Clicks,PP_Unique_Clicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 7f998023-2620-4ecf-b428-8fe9fd98c6da

	measure 'cMOM SG Unique_Opens growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Opens = [cSG_Unique_Opens]
			VAR PP_Unique_Opens = [cPPSG Unique_Opens]
			VAR Growth = DIVIDE(current_Unique_Opens - PP_Unique_Opens,PP_Unique_Opens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: f25cc945-456e-493e-aef4-fdfd3e487b6c

	measure 'cMOM SG Unique_Unsubscribes growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Unsubscribes = [cSG_Unique_Unsubscribes]
			VAR PP_Unique_Unsubscribes = [cPPSG Unique_Unsubscribes]
			VAR Growth = DIVIDE(current_Unique_Unsubscribes - PP_Unique_Unsubscribes,PP_Unique_Unsubscribes)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: eb3da28a-a9b2-43f7-bb91-42faa7a42fe0

	measure 'cMOM SG Unsubscribe_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe_rate = [cSG_Unsubscribe_rate]
			VAR PP_Unsubscribe_rate = [cPPSG Unsubscribe_rate]
			VAR Growth = DIVIDE(current_Unsubscribe_rate - PP_Unsubscribe_rate,PP_Unsubscribe_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: ce33afcc-6f38-471b-9f4b-60196d30d4a4

	measure 'cYOY SG Click_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Click_rate = [cSG_Click_rate] 
			VAR PY_Click_rate = [cPYSG Click_rate]
			VAR Growth = DIVIDE(current_Click_rate - PY_Click_rate,PY_Click_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: ecd6c1da-d27b-4cdf-8ba9-94080665675f

	measure 'cYOY SG Conversion_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Conversion_rate = [cSG_Conversion_rate]
			VAR PY_Conversion_rate = [cPYSG Conversion_rate]
			VAR Growth = DIVIDE(current_Conversion_rate - PY_Conversion_rate,PY_Conversion_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 5b50eff1-1b44-441b-87f4-86f6247fc7d4

	measure 'cYOY SG Email_Bounces growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Email_Bounces = [cSG_Email_Bounces]
			VAR PY_Email_Bounces = [cPYSG Email_Bounces]
			VAR Growth = DIVIDE(current_Email_Bounces - PY_Email_Bounces,PY_Email_Bounces)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 7cdad112-d7e6-417f-be43-8a5b6f47ee11

	measure 'cYOY SG Email_bounces_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Email_bounces_rate = [cSG_Email_bounces_rate]
			VAR PY_Email_bounces_rate = [cPYSG Email_bounces_rate]
			VAR Growth = DIVIDE(current_Email_bounces_rate - PY_Email_bounces_rate,PY_Email_bounces_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 35aef287-19ac-4c4b-b199-306f6dd20693

	measure 'cYOY SG Open_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Open_rate = [cSG_Open_rate]
			VAR PY_Open_rate = [cPYSG Open_rate]
			VAR Growth = DIVIDE(current_Open_rate - PY_Open_rate,PY_Open_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: f855c3fe-9d7a-4e1e-a493-ba1df0e25af3

	measure 'cYOY SG Orders growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Orders = [cSG_Orders]
			VAR PY_Orders = [cPYSG Orders]
			VAR Growth = DIVIDE(current_Orders - PY_Orders,PY_Orders)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: a430c4c3-12e1-42cd-86ce-80795925e2cd

	measure 'cYOY SG Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [cSG_Recipients] 
			VAR PY_Recipients = [cPYSG Recipients]
			VAR Growth = DIVIDE(current_Recipients - PY_Recipients,PY_Recipients)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 224d9cce-5361-4136-a4c3-caa14cd9d9c6

	measure 'cYOY SG Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Revenue = [cSG_Revenue]
			VAR PY_Revenue = [cPYSG Revenue]
			VAR Growth = DIVIDE(current_Revenue - PY_Revenue,PY_Revenue)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 2b7a6912-3b8b-4666-bc9c-101dafe8c197

	measure 'cYOY SG Spam_Complaints growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Spam_Complaints = [cSG_Spam_Complaints]
			VAR PY_Spam_Complaints = [cPYSG Spam_Complaints]
			VAR Growth = DIVIDE(current_Spam_Complaints - PY_Spam_Complaints,PY_Spam_Complaints)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: e4704013-a9c2-4af3-832e-269bcc368435

	measure 'cYOY SG Spam_complaints_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Spam_complaints_rate = [cSG_Spam_complaints_rate]
			VAR PY_Spam_complaints_rate = [cPYSG Spam_complaints_rate]
			VAR Growth = DIVIDE(current_Spam_complaints_rate - PY_Spam_complaints_rate,PY_Spam_complaints_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: dac4c08c-4655-4d30-8eb5-60b722802ef1

	measure 'cYOY SG Unique_Clicks growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Clicks = [cSG_Unique_Clicks]
			VAR PY_Unique_Clicks = [cPYSG Unique_Clicks]
			VAR Growth = DIVIDE(current_Unique_Clicks - PY_Unique_Clicks,PY_Unique_Clicks)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: bd68c46c-4d78-4a98-853d-87c9992837e5

	measure 'cYOY SG Unique_Opens growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Opens = [cSG_Unique_Opens]
			VAR PY_Unique_Opens = [cPYSG Unique_Opens]
			VAR Growth = DIVIDE(current_Unique_Opens - PY_Unique_Opens,PY_Unique_Opens)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 5964993d-7097-4e33-90a2-aaa791d86c67

	measure 'cYOY SG Unique_Unsubscribes growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unique_Unsubscribes = [cSG_Unique_Unsubscribes]
			VAR PY_Unique_Unsubscribes = [cPYSG Unique_Unsubscribes]
			VAR Growth = DIVIDE(current_Unique_Unsubscribes - PY_Unique_Unsubscribes,PY_Unique_Unsubscribes)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: 356adb62-a1eb-4477-ae6d-7c0073612f56

	measure 'cYOY SG Unsubscribe_rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Unsubscribe_rate = [cSG_Unsubscribe_rate]
			VAR PY_Unsubscribe_rate = [cPYSG Unsubscribe_rate]
			VAR Growth = DIVIDE(current_Unsubscribe_rate - PY_Unsubscribe_rate,PY_Unsubscribe_rate)
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Segment Data
		lineageTag: f09cf385-702d-4ea4-b6fb-4c2c79f9ebf4

	measure 'cColor PM SG Click_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Click_rate] - [cPPSG Click_rate],[cPPSG Click_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: c91eca5a-171f-4a8c-a779-f74a97ddb28b

	measure 'cColor PM SG Conversion_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Conversion_rate] - [cPPSG Conversion_rate],[cPPSG Conversion_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: c3531142-1821-484d-b9f6-24c87103f39e

	measure 'cColor PM SG Email_Bounces' =
			
			VAR mom_growth = DIVIDE([cSG_Email_Bounces] - [cPPSG Email_Bounces],[cPPSG Email_Bounces])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: fed1a1a7-9bc9-446b-9db8-6505e679f652

	measure 'cColor PM SG Email_bounces_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Email_bounces_rate] - [cPPSG Email_bounces_rate],[cPPSG Email_bounces_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 53c3abbe-517e-4292-ab6c-0c93ce39644a

	measure 'cColor PM SG Open_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Open_rate] - [cPPSG Open_rate],[cPPSG Open_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: fc086fea-d4ed-432b-9ee0-4d12b5d3ecf7

	measure 'cColor PM SG Orders' =
			
			VAR mom_growth = DIVIDE([cSG_Orders] - [cPPSG Orders],[cPPSG Orders])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 5e7059d1-ca30-4eda-8304-09a8de74ac51

	measure 'cColor PM SG Recipients' =
			
			VAR mom_growth = DIVIDE([cSG_Recipients] - [cPPSG Recipients],[cPPSG Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 2f8d5c13-33ad-4aee-9c63-47ced4a23f78

	measure 'cColor PM SG Revenue' =
			
			VAR mom_growth = DIVIDE([cSG_Revenue] - [cPPSG Revenue],[cPPSG Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 6205dff8-8874-4cbf-9072-902f3b3af9bf

	measure 'cColor PM SG Spam_Complaints' =
			
			VAR mom_growth = DIVIDE([cSG_Spam_Complaints] - [cPPSG Spam_Complaints],[cPPSG Spam_Complaints])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 16a4c2c0-2770-49c8-861f-bf52201d5bd6

	measure 'cColor PM SG Spam_complaints_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Spam_complaints_rate] - [cPPSG Spam_complaints_rate],[cPPSG Spam_complaints_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 36c2ccdd-4cec-4b0f-8dfe-fadc563c89d4

	measure 'cColor PM SG Unique_Clicks' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Clicks] - [cPPSG Unique_Clicks],[cPPSG Unique_Clicks])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 0558f67a-c4d4-4029-96d9-90eb0226835e

	measure 'cColor PM SG Unique_Opens' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Opens] - [cPPSG Unique_Opens],[cPPSG Unique_Opens])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 5ba7b298-6dea-4f98-a4b2-3dd4956bb794

	measure 'cColor PM SG Unique_Unsubscribes' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Unsubscribes] - [cPPSG Unique_Unsubscribes],[cPPSG Unique_Unsubscribes])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: d500e66f-617a-4fad-b05f-ae3128941cb0

	measure 'cColor PM SG Unsubscribe_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Unsubscribe_rate] - [cPPSG Unsubscribe_rate],[cPPSG Unsubscribe_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: a16b49ab-996d-4eeb-a23b-5cdec2534ee2

	measure 'cColor PY SG Unsubscribe_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Unsubscribe_rate] - [cPYSG Unsubscribe_rate],[cPYSG Unsubscribe_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 749c52bb-b0b0-4512-8c51-4a4b9537d283

	measure 'cColor PY SG Click_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Click_rate] - [cPYSG Click_rate],[cPYSG Click_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 1408c3b8-5857-4cde-b623-2f374544634e

	measure 'cColor PY SG Conversion_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Conversion_rate] - [cPYSG Conversion_rate],[cPYSG Conversion_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 38d05fc2-0504-4d51-b290-dc0ded5ef0a9

	measure 'cColor PY SG Email_Bounces' =
			
			VAR mom_growth = DIVIDE([cSG_Email_Bounces] - [cPYSG Email_Bounces],[cPYSG Email_Bounces])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 0a1db69e-c96e-42ab-b7a9-a3bd74f9c3ac

	measure 'cColor PY SG Email_bounces_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Email_bounces_rate] - [cPYSG Email_bounces_rate],[cPYSG Email_bounces_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 7727ea34-770e-4c28-9672-339245072205

	measure 'cColor PY SG Open_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Open_rate] - [cPYSG Open_rate],[cPYSG Open_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 1049f80f-01be-4cca-91c1-75c15f97e98f

	measure 'cColor PY SG Orders' =
			
			VAR mom_growth = DIVIDE([cSG_Orders] - [cPYSG Orders],[cPYSG Orders])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: dd039ecc-b138-4cb9-91b5-64c21410a135

	measure 'cColor PY SG Recipients' =
			
			VAR mom_growth = DIVIDE([cSG_Recipients] - [cPYSG Recipients],[cPYSG Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 5f994fb5-54be-4f42-a6d3-cf186e94ad7a

	measure 'cColor PY SG Revenue' =
			
			VAR mom_growth = DIVIDE([cSG_Revenue] - [cPYSG Revenue],[cPYSG Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: c820886b-3ff8-470f-bafa-5372f1beebc3

	measure 'cColor PY SG Spam_Complaints' =
			
			VAR mom_growth = DIVIDE([cSG_Spam_Complaints] - [cPYSG Spam_Complaints],[cPYSG Spam_Complaints])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 53c71160-9211-40f1-9a28-91b9cf2dd8b7

	measure 'cColor PY SG Spam_complaints_rate' =
			
			VAR mom_growth = DIVIDE([cSG_Spam_complaints_rate] - [cPYSG Spam_complaints_rate],[cPYSG Spam_complaints_rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 8fb6716d-547d-4097-a9e6-e766d3d57eb6

	measure 'cColor PY SG Unique_Clicks' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Clicks] - [cPYSG Unique_Clicks],[cPYSG Unique_Clicks])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: b83db30e-1ed6-4e39-9504-0547aff376db

	measure 'cColor PY SG Unique_Opens' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Opens] - [cPYSG Unique_Opens],[cPYSG Unique_Opens])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 11d19649-0562-4c0e-a523-49a0f2ba1a14

	measure 'cColor PY SG Unique_Unsubscribes' =
			
			VAR mom_growth = DIVIDE([cSG_Unique_Unsubscribes] - [cPYSG Unique_Unsubscribes],[cPYSG Unique_Unsubscribes])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Segment Data
		lineageTag: 5a4ef7e9-2a46-4267-9e68-e5ffae93f6ec

	measure cSGW_Recipients = SUM('Segment data weekly'[Total Recipients])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: 4de91040-38e9-48df-89c7-bbc7fd946439

	measure cSGW_Unique_Clicks = SUM('Segment data weekly'[Unique Clicks])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: b0f81d89-4f3b-4ec5-99a2-75d53cdacbe4

	measure cSGW_Unique_Opens = SUM('Segment data weekly'[Unique Opens])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: 404507f5-fedd-49c8-b4c7-2c1efd306e9f

	measure cSGW_Unique_Unsubscribes = SUM('Segment data weekly'[Unique Unsubscribes])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: a3ed75e9-a923-414e-b1a4-973a64b5b1f9

	measure cSGW_Email_Bounces = SUM('Segment data weekly'[Bounces])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: 49150b7d-b914-48dc-997a-7023027c25d5

	measure cSGW_Spam_Complaints = SUM('Segment data weekly'[Spam Complaints])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: a9b48053-61d1-4abc-ae48-fb170158e8a5

	measure cSGW_Orders = SUM('Segment data weekly'[Total Placed Order])
		formatString: #,0
		displayFolder: Segment Data Weekly
		lineageTag: 37dd0a0a-b924-4786-8fa6-9a1987179eb8

	measure cSGW_Revenue = SUM('Segment data weekly'[Total Placed Order Value])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: Segment Data Weekly
		lineageTag: 5fb7f126-3cf3-4790-af2d-49a49c625755

	measure cSGW_Click_rate = DIVIDE([cSGW_Unique_Clicks],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: fd98dc43-f44b-4ce5-bdef-75d5cebb9137

	measure cSGW_Conversion_rate = DIVIDE([cSGW_Orders],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: 630b2d6b-abd1-4568-94ee-7f9639407253

	measure cSGW_Email_bounces_rate = DIVIDE([cSGW_Email_Bounces],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: b69a9fc4-6b99-4751-92cc-e680cdedc1d0

	measure cSGW_Open_rate = DIVIDE([cSGW_Unique_Opens],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: b1500210-e5a9-484f-bdca-e698dfd6b22d

	measure cSGW_Spam_complaints_rate = DIVIDE([cSGW_Spam_Complaints],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: a9c7f5bd-c414-4a44-8f0d-091873890f69

	measure cSGW_Unsubscribe_rate = DIVIDE([cSGW_Unique_Unsubscribes],[cSGW_Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Segment Data Weekly
		lineageTag: 14a0dfd4-3d9f-4563-840a-e4c14044440e

	measure CampaignUnqRecipients = SUM('campaign unique recipients'[unique_recipients])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 7b3782db-af4a-47fd-bb7c-b8e758ab708d

	measure FlowUnqRecipients = SUM('flow unique recipients'[unique_recipients])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 9989a524-1cdd-464c-b726-91bb782966ff

	measure FlowUnqUnsubscribes = SUM('flow'[Unique Unsubscribes])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 554b56db-a376-4e64-953a-3d28e0733d58

	measure 'CUnqRecip 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(AVERAGE('campaign unique recipients'[unique_recipients]),FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: Campaign 4 WA
		lineageTag: 2564ac9f-ba87-45d7-abd9-4c46d2e643b1

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FCurrent Week UnqRecipients' = CALCULATE([FlowUnqRecipients],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: 50318e23-16d8-42a6-bd53-6b53026786a7

	measure 'FCurrent Week UnqUnsubscribes' = CALCULATE([FlowUnqUnsubscribes],FILTER(DailyDimDate,DailyDimDate[Current Week] = "Current Week"))
		formatString: #,0
		displayFolder: Flow Current Week
		lineageTag: e9f7fcbd-4308-4363-aa02-ba8580f724e3

	measure 'FlowUnique Recip 4WA' = CALCULATE(AVERAGE('flow unique recipients'[unique_recipients]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: 2a7ff8fa-2bc9-4b20-bfcf-1f638706d4fe

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FlowUnique Unsubscribes 4WA' = CALCULATE(AVERAGE('flow'[Unique Unsubscribes]),FILTER(DailyDimDate,DailyDimDate[Date]>=TODAY()-28))
		formatString: #,0
		displayFolder: FLow 4 Week Average
		lineageTag: 9bc22659-02f5-46d1-93dd-d63ce181fb35

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Flow UnqRecipMTD' = CALCULATE([FlowUnqRecipients],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 933a20c9-af98-468b-8557-268490747a3f

	measure 'Flow UnqUnsubscribesMTD' = CALCULATE([FlowUnqUnsubscribes],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: 7edd7de5-67c8-4e9c-b2d4-8e4ccdff35d9

	measure 'Flow NoofFlowsMTD' = CALCULATE([FlowNo of Flows],DATESMTD(DailyDimDate[Date]))
		formatString: 0
		displayFolder: Flow MTD
		lineageTag: f36268b9-81fa-421b-aef4-eae82312e190

	measure 'FUnqRecip 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM('flow unique recipients'[unique_recipients]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: 4bdeb6e5-2cd3-4cd4-a152-3311058c98d9

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'FUnqUnsubscribes 4WA' =
			var a = MAX(DailyDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE(SUM('flow unique recipients'[unique_unsubscribers]),FILTER(ALL(DailyDimDate),DailyDimDate[Date]>=b&&DailyDimDate[Date]<=c)),4)
		formatString: #,0
		displayFolder: Flow 4 WA
		lineageTag: bb7bd063-be01-4620-b718-299e5e93d294

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CCNF Unique Recipients' = [FlowUnqRecipients] + [CampaignUnqRecipients]
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: 35217fd4-4963-4c31-adf4-5899f6d931f5

	measure 'CCNF Unique Unsubscribes' = [FlowUnqUnsubscribes] + [CampaignUnqUnsubscribe]
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: 86311989-d9dd-4f3e-aeba-2b491429bf49

	measure 'MTD No of Mailings' = CALCULATE([CCNF No of Mailings],DATESMTD(DailyDimDate[Date]))
		formatString: 0
		displayFolder: CCNF MTD
		lineageTag: 0c91d837-493a-442b-ad1b-eebaf21ffa97

	measure 'MTD Unique Recipients' = CALCULATE([CCNF Unique Recipients],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: d572806f-10f1-484c-8154-99757cf929ae

	measure 'MTD Unique Unsubscribes' = CALCULATE([CCNF Unique Unsubscribes],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: 6761db38-a60f-435a-8ae4-64a5a039e02e

	measure 'CCNFUnique Recip 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Unique Recipients],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: 675355e6-9c6a-48d7-94ea-aa5e43076f75

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'CCNFUnique Unsubscribes 4WA' =
			var a = MAX(CampaignDimDate[Start of Week])
			var b = a-28
			var c = b+27
			Return DIVIDE(CALCULATE([CCNF Unique Unsubscribes],FILTER(ALL(CampaignDimDate),CampaignDimDate[Send Date]>=b&&CampaignDimDate[Send Date]<=c)),4)
		formatString: #,0
		displayFolder: CCNF 4 Week Average
		lineageTag: 9a67a376-f7f8-4779-9469-48b26826d920

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CampaignUnqUnsubscribe = SUM('campaign'[Unique Unsubscribes])
		formatString: 0
		displayFolder: CampaignMeasures
		lineageTag: f6f39da9-b8f4-4e34-a768-f43a220bf1d2

	measure CampaignUnsubscribe = SUM('campaign'[Total Unsubscribes])
		formatString: 0
		displayFolder: CampaignMeasures
		lineageTag: dad37607-740e-4d2c-b931-be6a2f84b97d

	measure CampaignAvgRecipients = DIVIDE([CampaignRecip],[No of Campaigns])
		formatString: #,0
		displayFolder: CampaignMeasures
		lineageTag: 0e8b2bf8-5d5b-41a1-82f5-a5345fe75347

		annotation PBI_FormatHint = {"isDecimal":true}

	measure FlowAvgRecipients = DIVIDE([FlowRecip],[FlowNo of Flows])
		formatString: #,0
		displayFolder: FlowMeasures
		lineageTag: 21c8989b-2ad9-42de-89b8-2cea113b9e33

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Campaign NoofcampaignsMTD' = CALCULATE([No of Campaigns],DATESMTD(CampaignDimDate[Send Date]))
		formatString: 0
		displayFolder: Campaign MTD
		lineageTag: 104e5424-6fc1-43dc-bb41-511702ec3d20

	measure 'Campaign AvgRecipientsMTD' = CALCULATE([CampaignAvgRecipients],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: 3258fbd6-4845-4b01-b559-ee65cdc5dc29

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Campaign UnqRecipientsMTD' = CALCULATE([CampaignUnqRecipients],DATESMTD(CampaignDimDate[Send Date]))
		formatString: #,0
		displayFolder: Campaign MTD
		lineageTag: ec59b968-ac4b-4802-a592-2518747ab3b1

	measure 'Campaign UnsubscribeRateMTD' = CALCULATE([CampaignUnsubscribeRate],DATESMTD(CampaignDimDate[Send Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Campaign MTD
		lineageTag: 03080aa5-7691-441d-b6d0-736d3581b5d7

	measure 'Flow OpenRateMTD' = CALCULATE([FlowOpenRate],DATESMTD(DailyDimDate[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow MTD
		lineageTag: 67f51ffe-f556-44d6-bb9b-938b6cd2edf3

	measure 'Flow AvgRecipientsMTD' = CALCULATE([FlowAvgRecipients],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: Flow MTD
		lineageTag: c6acdb20-ab71-4102-9381-b363d6d9cd22

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Flow UnsubscribeRateMTD' = CALCULATE([FlowUnsubscribe rate],DATESMTD(DailyDimDate[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Flow MTD
		lineageTag: 57602ca4-2c75-4045-96a0-4efea0f2182e

	measure 'CCNF Avg. Recipients' = DIVIDE([CCNF Recp], [CCNF No of Mailings])
		formatString: #,0
		displayFolder: CCNF Measures
		lineageTag: be5411ee-41f9-4509-9d28-190ea341748b

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'MTD Avg. Recipients' = CALCULATE([CCNF Avg. Recipients],DATESMTD(DailyDimDate[Date]))
		formatString: #,0
		displayFolder: CCNF MTD
		lineageTag: fc0b9200-8322-421a-b56b-3b6d7a8b18e2

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'MTD Unsubscribed Rate' = CALCULATE([CCNF Unsubscribed Rate],DATESMTD(DailyDimDate[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF MTD
		lineageTag: f472b702-7a7d-4824-bfef-ab1e0912106c

	measure 'MTD OpenRate' = CALCULATE([CCNF OpenRate],DATESMTD(DailyDimDate[Date]))
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: CCNF MTD
		lineageTag: b729d3ff-2934-4221-b9ba-2ffd56b7768a

	measure 'UP No of Maillings' = SUM('Unique Profile''s Data'[Number of Mailings])
		formatString: #,0
		displayFolder: Unique Profiles
		lineageTag: fd168ac8-afc1-4f8a-ab82-23f0b8559618

	measure 'UP Unique Profiles' = SUM('Unique Profile''s Data'[Unique Profiles])
		formatString: #,0
		displayFolder: Unique Profiles
		lineageTag: 3b9fb85a-a36f-437b-93ef-d30b0f63e9f0

	measure 'UP Total Recipients' = SUM('Unique Profile''s Data'[Total Delivered])
		formatString: #,0
		displayFolder: Unique Profiles
		lineageTag: 4b708cf1-ebb5-4e1d-a6e6-08aaeb627601

	measure 'UP Avg. Recipients' = SUM('Unique Profile''s Data'[Ave Recpient/Mailing])
		formatString: #,0
		displayFolder: Unique Profiles
		lineageTag: 45b51ccb-125d-4960-ac61-9574f67a76ac

	measure 'UP Unsubscribes' = SUM('Unique Profile''s Data'[Unsubscribes])
		formatString: #,0
		displayFolder: Unique Profiles
		lineageTag: c4532fa3-79aa-47eb-9c6a-6ee68c217f24

	measure 'UP Unsubscribes Rate' = DIVIDE([UP Unsubscribes],[UP Total Recipients])
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Unique Profiles
		lineageTag: 8aca0eaf-3780-4753-9fc1-a306947e6577

	measure 'UP Conversion' = SUM('Unique Profile''s Data'[Conversion])
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: 52f6f3e5-d90f-49d6-84b0-9622f82df56c

	measure 'UP Revenue' = SUM('Unique Profile''s Data'[Revenue ])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Unique Profiles
		lineageTag: 4b7560b3-7727-4359-a51f-35a3820b4a54

	measure 'UP Conversion Rate' = DIVIDE([UP Conversion],[UP Total Recipients])
		formatString: 0.000%;-0.000%;0.000%
		displayFolder: Unique Profiles
		lineageTag: 04e91cc9-a34e-4e5d-b14f-e9456414b663

	measure 'PPUP Recipients' = CALCULATE([UP Total Recipients],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: ba6e1b2d-fb37-47f8-9c42-c19960c8e028

	measure 'PPUP Avg. Recipients' = CALCULATE([UP Avg. Recipients],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Unique Profiles
		lineageTag: 9cda5056-28c3-4b27-97b6-31d0665c3206

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PPUP Conversion Rate' = CALCULATE([UP Conversion Rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Unique Profiles
		lineageTag: 0893c91a-f642-492f-ab71-d5a82647b05d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PPUP Conversion' = CALCULATE([UP Conversion],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Unique Profiles
		lineageTag: d6579899-846b-42b1-9f4d-8cc699ea5254

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PPUP No of Maillings' = CALCULATE([UP No of Maillings],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: 19b15da8-2f3e-44fa-95c2-20063aaf18bb

	measure 'PPUP Revenue' = CALCULATE([UP Revenue],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: e940240c-726f-4640-8f98-2606932ef62d

	measure 'PPUP Unique Profiles' = CALCULATE([UP Unique Profiles],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: b47e1979-1f41-40f9-84e3-67bc8b93d881

	measure 'PPUP Unsubscribes' = CALCULATE([UP Unsubscribes],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: d4f5ab90-4354-4341-9a2d-053daaeedd4a

	measure 'PPUP Unsubscribes Rate' = CALCULATE([UP Unsubscribes Rate],DATESBETWEEN(CampaignDimDate[Send Date],[campaignstartofpreviousperiod],[campaignendofpreviousperiod]))
		displayFolder: Unique Profiles
		lineageTag: 1a1d0e11-0164-418b-9cf0-fd28c2771545

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PYUP Recipients' = CALCULATE([UP Total Recipients],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: f3a66ad1-bd2f-45d4-8ede-1dbe32f61cb8

	measure 'PYUP Avg. Recipients' = CALCULATE([UP Avg. Recipients],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Unique Profiles
		lineageTag: f30290f0-67d4-4b67-8eeb-e593bb0504e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PYUP Conversion Rate' = CALCULATE([UP Conversion Rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Unique Profiles
		lineageTag: 45db1a6a-4a22-4db8-ae7f-413059a3566c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PYUP Conversion' = ```
			CALCULATE([UP Conversion],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
			
			```
		displayFolder: Unique Profiles
		lineageTag: 28135027-634e-4760-a20b-6e5bbd328fb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PYUP No of Maillings' = CALCULATE([UP No of Maillings],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: fbe1280f-9d14-4f3b-86a6-a329ba826018

	measure 'PYUP Revenue' = CALCULATE([UP Revenue],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: 735b0136-082d-4140-8b8a-89ccbf9567b1

	measure 'PYUP Unique Profiles' = CALCULATE([UP Unique Profiles],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: 00afe6e7-1ae1-4089-a98b-93b79449cf25

	measure 'PYUP Unsubscribes Rate' = CALCULATE([UP Unsubscribes Rate],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		displayFolder: Unique Profiles
		lineageTag: b06a1e52-994f-40bd-bffe-9c3f9ffc00fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'PYUP Unsubscribes' = CALCULATE([UP Unsubscribes],DATEADD(CampaignDimDate[Send Date],-1,YEAR))
		formatString: 0
		displayFolder: Unique Profiles
		lineageTag: 4127f5a4-e8d9-455b-9b75-d790ca59dae6

	measure 'cMOM UP Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Total Recipients] 
			VAR PP_Recipients = [PPUP Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: c449d8a5-9289-4480-a9a7-577806997a5e

	measure 'cMOM UP Avg. Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Avg. Recipients] 
			VAR PP_Recipients = [PPUP Avg. Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: f54d8edb-019e-4601-b0f2-9a9ab650ece6

	measure 'cMOM UP Conversion Rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Conversion Rate] 
			VAR PP_Recipients = [PPUP Conversion Rate]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 934da91a-431d-4fff-8e23-af32e933b59e

	measure 'cMOM UP Conversion growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Conversion] 
			VAR PP_Recipients = [PPUP Conversion]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: bd524d6d-85f9-4e53-9423-c1ce6934c25f

	measure 'cMOM UP No of Maillings growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP No of Maillings] 
			VAR PP_Recipients = [PPUP No of Maillings]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 977d227b-cbbc-429c-982a-7aebee56cb04

	measure 'cMOM UP Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Revenue] 
			VAR PP_Recipients = [PPUP Revenue]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 75159904-75da-4e29-a1a7-8307b103bbc3

	measure 'cMOM UP Unique Profiles growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unique Profiles] 
			VAR PP_Recipients = [PPUP Unique Profiles]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 9db640d2-5178-4b49-a074-70ee6415d776

	measure 'cMOM UP Unsubscribes Rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unsubscribes Rate] 
			VAR PP_Recipients = [PPUP Unsubscribes Rate]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 9e575062-5b3f-4ea3-b901-bf1dc74da238

	measure 'cMOM UP Unsubscribes growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unsubscribes] 
			VAR PP_Recipients = [PPUP Unsubscribes]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: d47f7448-31d8-4605-89e4-73401504819b

	measure 'cYOY UP Avg. Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Avg. Recipients] 
			VAR PP_Recipients = [PYUP Avg. Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 913862e1-d9b2-4c4f-b9aa-268b9d34e848

	measure 'cYOY UP Conversion growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Conversion] 
			VAR PP_Recipients = [PYUP Conversion]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: ef30058f-4b55-48b3-9195-7934a03d6897

	measure 'cYOY UP Conversion Rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Conversion Rate] 
			VAR PP_Recipients = [PYUP Conversion Rate]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 32370562-05f5-4773-a94a-2853a545e010

	measure 'cYOY UP No of Maillings growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP No of Maillings] 
			VAR PP_Recipients = [PYUP No of Maillings]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: a2f073ce-b4e3-441c-8cef-6ed420ae7c19

	measure 'cYOY UP Recipients growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Total Recipients] 
			VAR PP_Recipients = [PYUP Recipients]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 25579022-6b2d-4b16-b028-9f7df3b111d6

	measure 'cYOY UP Revenue growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Revenue] 
			VAR PP_Recipients = [PYUP Revenue]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: cbcac051-ba22-4131-a35e-6f8062afb99b

	measure 'cYOY UP Unique Profiles growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unique Profiles] 
			VAR PP_Recipients = [PYUP Unique Profiles]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: bd84c6e0-fdd2-4fb8-9819-1671628df446

	measure 'cYOY UP Unsubscribes growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unsubscribes] 
			VAR PP_Recipients = [PYUP Unsubscribes]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 92f56807-143f-4414-8beb-ce90c03b059a

	measure 'cYOY UP Unsubscribes Rate growth%' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR current_Recipients = [UP Unsubscribes Rate] 
			VAR PP_Recipients = [PYUP Unsubscribes Rate]
			VAR Growth = DIVIDE(current_Recipients - PP_Recipients,PP_Recipients)
			
			RETURN 
			    IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )
			```
		displayFolder: Unique Profiles
		lineageTag: 23ebae83-7208-4463-8a91-08fc2cdaab1d

	measure 'cColor PM UP Avg. Recipients' =
			
			VAR mom_growth = DIVIDE([UP Avg. Recipients] - [PPUP Avg. Recipients],[PPUP Avg. Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 168f181d-0622-4bcf-a40f-43bf7edd412d

	measure 'cColor PM UP Recipients' =
			
			VAR mom_growth = DIVIDE([UP Total Recipients] - [PPUP Recipients],[PPUP Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: d154f978-6cf3-446a-8e3a-8e0fc283984a

	measure 'cColor PM UP Conversion Rate' =
			
			VAR mom_growth = DIVIDE([UP Conversion Rate] - [PPUP Conversion Rate],[PPUP Conversion Rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 26cdbd70-e3eb-420f-ac1d-99fa605c929d

	measure 'cColor PM UP Conversion' =
			
			VAR mom_growth = DIVIDE([UP Conversion] - [PPUP Conversion],[PPUP Conversion])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: d4a17236-6430-4204-8a8f-37ad155d665d

	measure 'cColor PM UP No of Maillings' =
			
			VAR mom_growth = DIVIDE([UP No of Maillings] - [PPUP No of Maillings],[PPUP No of Maillings])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 597f5709-b45c-4104-88ae-5f6cc6448ff1

	measure 'cColor PM UP Revenue' =
			
			VAR mom_growth = DIVIDE([UP Revenue] - [PPUP Revenue],[PPUP Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 073de931-d76d-4939-89bf-79c3ce1b7b65

	measure 'cColor PM UP Unique Profiles' =
			
			VAR mom_growth = DIVIDE([UP Unique Profiles] - [PPUP Unique Profiles],[PPUP Unique Profiles])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: fe163c2b-fa6b-4662-8a35-f17866f1e30b

	measure 'cColor PM UP Unsubscribes Rate' =
			
			VAR mom_growth = DIVIDE([UP Unsubscribes Rate] - [PPUP Unsubscribes Rate],[PPUP Unsubscribes Rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 9060b8d4-a4ba-4d21-8f90-d4b39f785851

	measure 'cColor PM UP Unsubscribes' =
			
			VAR mom_growth = DIVIDE([UP Unsubscribes] - [PPUP Unsubscribes],[PPUP Unsubscribes])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: fa781427-bdeb-4f1a-b841-e7e8de711c71

	measure 'cColor PY UP Avg. Recipients' =
			
			VAR mom_growth = DIVIDE([UP Avg. Recipients] - [PYUP Avg. Recipients],[PYUP Avg. Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 05c83bab-968a-4ee2-b675-c54b11798347

	measure 'cColor PY UP Conversion' =
			
			VAR mom_growth = DIVIDE([UP Conversion] - [PYUP Conversion],[PYUP Conversion])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: ef6f505e-a990-4447-9866-9d70d3b6fec7

	measure 'cColor PY UP Conversion Rate' =
			
			VAR mom_growth = DIVIDE([UP Conversion Rate] - [PYUP Conversion Rate],[PYUP Conversion Rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: ff620867-8a78-43ce-a0ed-9ed5e24d8c65

	measure 'cColor PY UP No of Maillings' =
			
			VAR mom_growth = DIVIDE([UP No of Maillings] - [PYUP No of Maillings],[PYUP No of Maillings])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 6cb9c99e-f7fd-4ee0-8c32-c16ef381c44b

	measure 'cColor PY UP Recipients' =
			
			VAR mom_growth = DIVIDE([UP Total Recipients] - [PYUP Recipients],[PYUP Recipients])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: c3c7fa1a-8f85-4eab-89b5-4ec6bd3f16c1

	measure 'cColor PY UP Revenue' =
			
			VAR mom_growth = DIVIDE([UP Revenue] - [PYUP Revenue],[PYUP Revenue])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 17748852-1e29-4a5c-aa0d-1c795aa9c65e

	measure 'cColor PY UP Unique Profiles' =
			
			VAR mom_growth = DIVIDE([UP Unique Profiles] - [PYUP Unique Profiles],[PYUP Unique Profiles])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 19c3d80f-fba7-48c8-979d-c56c9ac9967e

	measure 'cColor PY UP Unsubscribes' =
			
			VAR mom_growth = DIVIDE([UP Unsubscribes] - [PYUP Unsubscribes],[PYUP Unsubscribes])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: fec810b2-3150-4309-85b2-e10ae0162d17

	measure 'cColor PY UP Unsubscribes Rate' =
			
			VAR mom_growth = DIVIDE([UP Unsubscribes Rate] - [PYUP Unsubscribes Rate],[PYUP Unsubscribes Rate])
			RETURN
			    IF(mom_growth<0, "red","green")
		displayFolder: Unique Profiles
		lineageTag: 91cf685a-9d68-4496-8949-ae44be0d342d

	measure 'ccnfYoY Recipients change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Recp] 
			VAR PYRecipients = [ccnfPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			VAR Change = CurrentRecipients-PYRecipients
			RETURN 
			    FORMAT(Change, "#,##0")& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		formatString: #,##0
		displayFolder: CCNF Recip
		lineageTag: 34e290a2-b97c-47e7-a9d9-45279b585f0b

	measure 'ccnfYoY UnqOp Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Unique Opens] 
			VAR PYUNQOP= [ccnfPYUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			VAR Change = CurrentOpens-PYUNQOP
			RETURN 
			       FORMAT(Change, "#,##0")& " (" &IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unique Opens
		lineageTag: c561fcd3-c508-4688-a99d-2c877ebb9d27

	measure 'ccnfYoY OpRt Change' = ```
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PYUNQOP= [ccnfPYUnqOpRt]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			VAR Change = CurrentOpens-PYUNQOP
			RETURN 
			    ROUND(Change*100,1)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unique Opens
		lineageTag: bf129ae2-6cac-4690-a99f-058c6fc68cbe

	measure 'ccnfYOY Revenue Change' = ```
			
			
			
			VAR up_arrow   = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			
			VAR CurrentRevenue = [CCNF Revenue]
			VAR PYRevenue      = [ccnfPYTotalRevenue]
			
			VAR Change = CurrentRevenue - PYRevenue
			VAR Growth = DIVIDE(Change, PYRevenue)
			
			RETURN
			FORMAT(Change, "$#,##0") &
			" (" &
			IF(
			    Growth < 0,
			    FORMAT(Growth, "0.0%") & " " & down_arrow,
			    FORMAT(Growth, "0.0%") & " " & up_arrow
			)
			& ")"
			
			```
		formatString: $ #,##0
		displayFolder: CCNF Revenue
		lineageTag: 3cb65cbd-cefd-4ed7-b180-d8314199582f

	measure 'ccnfYOY Unsub Rate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [CCNF Unsubscribed Rate] 
			VAR PYUnsubRate = [ccnfPYTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PYUnsubRate,PYUnsubRate)
			VAR Change = CurrentUnsubRate -PYUnsubRate
			RETURN 
			ROUND(Change*100,1)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 3761dd82-66e0-4700-8fc0-57ef38b32355

	measure 'CCNF source color' =
			SWITCH(
			    SELECTEDVALUE(Source[Source]),
			    "Campaigns", "#8180CA",
			    "Flows",  "#FF6E2E")
		displayFolder: CCNF Revenue
		lineageTag: 4dcd7322-3740-4e40-aec6-666292d4ef0b

	measure 'ccnfMOM Unsub Rate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsubRate = [CCNF Conversion Rate] 
			VAR PPUnsubRate = [ccnfPPTotalUnsubRate]
			VAR Growth = DIVIDE(CurrentUnsubRate -PPUnsubRate,PPUnsubRate)
			VAR Change = CurrentUnsubRate -PPUnsubRate
			RETURN 
			ROUND(Change*100,2)&"% " & " ("   & IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 39150142-a31a-4ae1-875e-9dde33d0882e

	measure 'ccnfMOM Recipients change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Recp] 
			VAR PPRecipients = [ccnfPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients-PPRecipients,PPRecipients)
			VAR Change = CurrentRecipients-PPRecipients
			RETURN 
			        FORMAT(Change, "#,##0")& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Recip
		lineageTag: d468a389-130a-4b04-be07-d66abaaed252

	measure 'ccnfMOM UnqOp Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Unique Opens]
			VAR PPUNQOP= [ccnfPPUnqOp]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			VAR Change = CurrentOpens-PPUNQOP
			RETURN 
			       FORMAT(Change, "#,##0")& " (" &IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unique Opens
		lineageTag: ce503db0-6124-4d5b-913b-0fcfec3ba8b6

	measure ccnfPYUnqOpTEST = ```
			
			
			CALCULATE(
			    [CCNF Unique Opens],
			    ALL(CampaignDimDate),
			    YEAR(CampaignDimDate[Send Date])
			        = YEAR(MAX(CampaignDimDate[Send Date])) - 1
			)
			
			
			```
		formatString: 0
		displayFolder: CCNF Unique Opens
		lineageTag: 2f8a0f02-40af-4626-a137-ded9e5c7e3cd

	measure 'ccnfMOM OpRt Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PPUNQOP= [ccnfPPUnqOpRt]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			VAR Change = CurrentOpens-PPUNQOP
			RETURN 
			    ROUND(Change*100,1)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unique Opens
		lineageTag: c5bf6578-bd4d-42a6-bbc7-1610971f14df

	measure 'ccnfMOM DailyClickRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Click to receive rate]
			VAR PPUNQOP= [ccnfPPDailyClickRate]
			VAR Growth = DIVIDE(CurrentOpens-PPUNQOP,PPUNQOP)
			VAR Change = CurrentOpens-PPUNQOP
			RETURN 
			       ROUND(Change*100,2)&"% " & " (" &IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		formatString: #,##0.00 %
		displayFolder: CCNF Click to receive rate
		lineageTag: 702c29eb-51fc-45c3-a98d-6b069bb47a7c

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'ccnfMOM DailyConversionRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversionsRate = [CCNF Conversion Rate] 
			VAR PPConversionsRate = [ccnfPPTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentConversionsRate -PPConversionsRate,PPConversionsRate)
			VAR Change = CurrentConversionsRate-PPConversionsRate
			RETURN 
			    ROUND(Change*100,3)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Conversion Rate
		lineageTag: 33df8ee6-2464-4e65-8f0b-d374cc0f5f87

	measure 'ccnfMOM Revenue Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRevenue = [CCNF Revenue]
			VAR PPRevenue = [ccnfPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue -PPRevenue,PPRevenue)
			VAR Change = CurrentRevenue-PPRevenue
			RETURN 
			    FORMAT(Change, "$#,0") & 
			    " (" &
			    IF(
			        Growth < 0,
			        FORMAT(Growth, "0.0%") & " " & down_arrow,
			        FORMAT(Growth, "0.0%") & " " & up_arrow
			    ) &
			    ")"
			```
		displayFolder: CCNF Revenue
		lineageTag: 4e490be1-759e-4a4f-aa07-b48d694e1577

	measure 'ccnfMOM TotalConversions Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentConversions = [CCNF Conversion] 
			VAR PPConversions = [ccnfPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions -PPConversions,PPConversions)
			VAR Change = CurrentConversions-PPConversions
			RETURN 
			       ROUND(Change,0)& " (" &IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Conversion
		lineageTag: 35bb702f-0d49-4c9d-a1a7-8875d593d553

	measure 'ccnfMOM UnqClicks Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR TotalUnqClick = [CCNF Unique Clicks] 
			VAR PPClick = [ccnfPPTotalUnqClick]
			// VAR PPClick = [ccnfPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick,PPClick)
			VAR Change = TotalUnqClick-PPClick
			RETURN 
			    FORMAT(Change, "#,##0")& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unique Clicks
		lineageTag: aede1539-ab0c-4f27-b371-f2e3eec25a47

	measure 'ccnfMOM Unsub Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentUnsub = [CCNF Unsubscribe] 
			VAR PPUnsub = [ccnfPPTotalUnsub]
			VAR Growth = DIVIDE(CurrentUnsub -PPUnsub,PPUnsub)
			VAR Change = CurrentUnsub-PPUnsub
			RETURN 
			       FORMAT(Change, "#,##0")& " (" &IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			```
		displayFolder: CCNF Unsubscribed
		lineageTag: b3ca430d-8c63-453f-a8e4-44c569e78c80

	measure 'ccnfYOY DailyClickRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Click to receive rate]
			VAR PYUNQOP= [ccnfPYDailyClickRate]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			VAR Change = CurrentOpens-PYUNQOP
			RETURN 
			    ROUND(Change*100,2)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			
			// VAR CurrentDailyClickRate = [CCNF Click to receive rate] 
			// VAR PYDailyClickRate = [ccnfPYDailyClickRate]
			
			// RETURN 
			// CurrentDailyClickRate -PYDailyClickRate
			```
		formatString: #,##0.00 %
		displayFolder: CCNF Click to receive rate
		lineageTag: 7a75c9e6-2e61-4b3a-aeeb-f2a216cb5547

	measure 'ccnfYOY DailyConversionRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentOpens = [CCNF Conversion Rate]
			VAR PYUNQOP= [ccnfPYTotalConversionsRate]
			VAR Growth = DIVIDE(CurrentOpens-PYUNQOP,PYUNQOP)
			VAR Change = CurrentOpens-PYUNQOP
			RETURN 
			    ROUND(Change*100,3)&"% " & " ("& IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			// VAR CurrentConversionsRate = [CCNF Conversion Rate]
			// VAR PYConversionsRate = [ccnfPYTotalConversionsRate]
			
			// RETURN 
			// CurrentConversionsRate - PYConversionsRate
			```
		displayFolder: CCNF Conversion Rate
		lineageTag: 9a06fa76-fea0-4731-8508-83a28078f8b7

	measure 'ccnfYOY TotalConversions Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Conversion] 
			VAR PYRecipients = [ccnfPYTotalConversions]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			VAR Change = CurrentRecipients-PYRecipients
			RETURN 
			    ROUND(Change,0)& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			
			
			// VAR CurrentConversions = [CCNF Conversion] 
			// VAR PYConversions = [ccnfPYTotalConversions]
			
			// RETURN 
			// CurrentConversions -PYConversions
			```
		displayFolder: CCNF Conversion
		lineageTag: 85a07fd9-70c4-453e-8940-58935612a963

	measure 'ccnfYOY TotalUnqClick Change' = ```
			
			 VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Unique Clicks] 
			VAR PYRecipients = [ccnfPYTotalUnqClick]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			VAR Change = CurrentRecipients-PYRecipients
			RETURN 
			    FORMAT(Change, "#,##0")& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			
			// VAR TotalUnqClick = [CCNF Unique Clicks] 
			// VAR PYClick = [ccnfPYTotalUnqClick]
			
			// RETURN 
			// TotalUnqClick - PYClick
			```
		displayFolder: CCNF Unique Clicks
		lineageTag: bd5bc25c-4637-42bc-8ac0-7c7802da1fde

	measure 'ccnfYOY Unsub Change' = ```
			
			VAR up_arrow = UNICHAR(129137) 
			VAR down_arrow = UNICHAR(129139) 
			VAR CurrentRecipients = [CCNF Unsubscribe] 
			VAR PYRecipients = [ccnfPYTotalUnsub]
			VAR Growth = DIVIDE(CurrentRecipients-PYRecipients,PYRecipients)
			VAR Change = CurrentRecipients-PYRecipients
			RETURN 
			    FORMAT(Change, "#,##0")& " ("&IF(
			        Growth<0, ROUND(Growth*100,1)&"% "& down_arrow,
			        ROUND(Growth*100,1)&"% "& up_arrow
			    )&")"
			
			// VAR CurrentUnsub = [CCNF Unsubscribe] 
			// VAR PYUnsub = [ccnfPYTotalUnsub]
			
			// RETURN 
			// CurrentUnsub -PYUnsub
			```
		displayFolder: CCNF Unsubscribed
		lineageTag: e2900e1b-0b2f-4359-8c0b-c42abe7f1efb

	measure 'cUNIQUE CLICKS PY' = ```
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cUNIQUE CLICKS],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			
			// CALCULATE(
			//     [cUNIQUE CLICKS],
			//     DATEADD(CampaignDimDate[Send Date], -1, YEAR)
			// )
			
			```
		formatString: 0
		displayFolder: CUNQCLICK
		lineageTag: cdff4cd2-9c54-4ec2-b023-ff37a562900d

	measure 'cCONVERSIONS PY' = ```
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cCONVERSIONS],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE(
			//     [cCONVERSIONS],
			//     DATEADD(CampaignDimDate[Send Date], -1, YEAR)
			// )
			
			```
		formatString: 0
		displayFolder: CTOTALCONV
		lineageTag: 56b5e12e-be2f-4839-b859-089e06e3d913

	measure 'cAOV PY' = ```
			
			VAR CurrentDates =
			    VALUES ( CampaignDimDate[Send Date] )
			
			VAR PYDates =
			    SELECTCOLUMNS (
			        CurrentDates,
			        "Send Date",
			        DATE (
			            YEAR ( [Send Date] ) - 1,
			            MONTH ( [Send Date] ),
			            DAY ( [Send Date] )
			        )
			    )
			RETURN
			CALCULATE (
			    [cAOV],
			    TREATAS ( PYDates, CampaignDimDate[Send Date] )
			)
			// CALCULATE(
			//     [cAOV],
			//     DATEADD(CampaignDimDate[Send Date], -1, YEAR)
			// )
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: CCONVRATE
		lineageTag: 33f3d49e-9fe6-407d-8917-79d82bc309cc

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'ccnfMOM Recipients change1' = ```
			
			VAR CurrentRecipients = [CCNF Recp]
			VAR PPRecipients = [ccnfPPRecipients]
			VAR Change = CurrentRecipients - PPRecipients
			RETURN
			    FORMAT(Change, "#,##0")
			
			```
		displayFolder: CCNF Recip
		lineageTag: f6b11dd3-6b37-4520-bf8e-cd5fe3b4ed61

	measure 'ccnfMOM UnqOp Change1' = ```
			
			VAR CurrentOpens = [CCNF Unique Opens]
			VAR PPUNQOP = [ccnfPPUnqOp]
			VAR Change = CurrentOpens - PPUNQOP
			RETURN
			    FORMAT(Change, "#,##0")
			
			```
		displayFolder: CCNF Unique Opens
		lineageTag: 831761b7-08bd-4b43-a79c-7226ca820328

	measure 'ccnfMOM OpRt Change1' = ```
			
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PPUNQOP = [ccnfPPUnqOpRt]
			VAR Change = CurrentOpens - PPUNQOP
			RETURN
			    ROUND(Change * 100, 1) & "%"
			
			```
		displayFolder: CCNF Unique Opens
		lineageTag: e8ef632a-4727-43c8-88ab-c54263d40547

	measure 'ccnfMOM UnqClicks Change1' = ```
			
			VAR TotalUnqClick = [CCNF Unique Clicks]
			VAR PPClick = [ccnfPPTotalUnqClick]
			VAR Change = TotalUnqClick - PPClick
			RETURN
			    FORMAT(Change, "#,##0")
			
			```
		displayFolder: CCNF Unique Clicks
		lineageTag: 9a1a5469-0efb-4fd7-ae5a-022936c8d338

	measure 'ccnfMOM Revenue Change1' = ```
			
			VAR CurrentRevenue = [CCNF Revenue]
			VAR PPRevenue = [ccnfPPTotalRevenue]
			VAR Change = CurrentRevenue - PPRevenue
			RETURN
			    FORMAT(Change, "$#,0")
			
			```
		displayFolder: CCNF Revenue
		lineageTag: e9a9e6dd-108d-4082-97d1-1c98d1f14fc6

	measure 'ccnfMOM DailyClickRate Change1' = ```
			
			VAR CurrentRate = [CCNF Click to receive rate]
			VAR PPRate = [ccnfPPDailyClickRate]
			VAR Change = CurrentRate - PPRate
			RETURN
			    ROUND(Change * 100, 2) & "%"
			
			```
		displayFolder: CCNF Click to receive rate
		lineageTag: 0861b8f7-3311-4f34-a7d3-909101537ac6

	measure 'ccnfMOM TotalConversions Change1' = ```
			
			VAR CurrentConversions = [CCNF Conversion]
			VAR PPConversions = [ccnfPPTotalConversions]
			VAR Change = CurrentConversions - PPConversions
			RETURN
			    ROUND(Change, 0)
			
			```
		formatString: 0
		displayFolder: CCNF Conversion
		lineageTag: ec3173de-e4de-4e1b-93e8-21d6c5a23ad6

	measure 'ccnfMOM DailyConversionRate Change1' = ```
			
			VAR CurrentRate = [CCNF Conversion Rate]
			VAR PPRate = [ccnfPPTotalConversionsRate]
			VAR Change = CurrentRate - PPRate
			RETURN
			    ROUND(Change * 100, 3) & "%"
			
			```
		displayFolder: CCNF Conversion Rate
		lineageTag: 073f3da8-5802-460e-b8af-66793432bb5c

	measure 'ccnfMOM Unsub Change1' = ```
			
			VAR CurrentUnsub = [CCNF Unsubscribe]
			VAR PPUnsub = [ccnfPPTotalUnsub]
			VAR Change = CurrentUnsub - PPUnsub
			RETURN
			    FORMAT(Change, "#,##0")
			
			```
		displayFolder: CCNF Unsubscribed
		lineageTag: d0d87fb6-b504-4af9-9dfe-9ae9646ea8b0

	measure 'ccnfMOM Unsub Rate Change1' = ```
			
			VAR CurrentRate = [CCNF Unsubscribed Rate]
			VAR PPRate = [ccnfPPTotalUnsubRate]
			VAR Change = CurrentRate - PPRate
			RETURN
			    ROUND(Change * 100, 2) & "%"
			
			```
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: c9c606eb-85d3-4791-a1f9-2b14c52bb3b6

	measure 'ccnfMOM Recipients Growth1%' = ```
			
			VAR CurrentRecipients = [CCNF Recp] 
			VAR PPRecipients = [ccnfPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients - PPRecipients, PPRecipients)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Recip
		lineageTag: c109d512-bf7a-46f8-96f0-e4de789abd8a

	measure 'ccnfMOM UnqOp Growth1%' = ```
			
			VAR CurrentOpens = [CCNF Unique Opens]
			VAR PPUNQOP = [ccnfPPUnqOp]
			VAR Growth = DIVIDE(CurrentOpens - PPUNQOP, PPUNQOP)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Unique Opens
		lineageTag: 4c74d411-e55c-46a7-a212-09a632c7b303

	measure 'ccnfMOM OpRt Growth1%' = ```
			
			VAR CurrentOpens = [CCNF OpenRate]
			VAR PPUNQOP = [ccnfPPUnqOpRt]
			VAR Growth = DIVIDE(CurrentOpens - PPUNQOP, PPUNQOP)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Unique Opens
		lineageTag: 71be2367-c283-41aa-964a-7e713209d89e

	measure 'ccnfMOM TotalUnqClick Growth1%' = ```
			
			VAR TotalUnqClick = [CCNF Unique Clicks]
			VAR PPClick = [ccnfPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick, PPClick)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Unique Clicks
		lineageTag: 000891d1-7f72-463e-bebc-bb5982df9aa9

	measure 'ccnfMOM Revenue Growth1%' = ```
			
			VAR CurrentRevenue = [CCNF Revenue]
			VAR PPRevenue = [ccnfPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue - PPRevenue, PPRevenue)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Revenue
		lineageTag: 544cb781-13c7-4a34-8861-88d1f9a2277d

	measure 'ccnfMOM DailyClickRate Growth1%' = ```
			
			VAR CurrentDailyClickRate = [CCNF Click to receive rate]
			VAR PPDailyClickRate = [ccnfPPDailyClickRate]
			VAR Growth =
			    DIVIDE(
			        CurrentDailyClickRate - PPDailyClickRate,
			        PPDailyClickRate
			    )
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Click to receive rate
		lineageTag: df4b1937-6896-4f0d-bb37-f618f2957910

	measure 'ccnfMOM TotalConversions Growth1%' = ```
			
			VAR CurrentConversions = [CCNF Conversion]
			VAR PPConversions = [ccnfPPTotalConversions]
			VAR Growth = DIVIDE(CurrentConversions - PPConversions, PPConversions)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Conversion
		lineageTag: 011a0670-0bf1-427e-8505-5d9893859beb

	measure 'ccnfMOM DailyConversionRate Growth1%' = ```
			
			VAR CurrentConversionsRate = [CCNF Conversion Rate]
			VAR PPConversionsRate = [ccnfPPTotalConversionsRate]
			VAR Growth =
			    DIVIDE(
			        CurrentConversionsRate - PPConversionsRate,
			        PPConversionsRate
			    )
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Conversion Rate
		lineageTag: 0d7c787e-1ad6-4e11-8f90-91362f550c40

	measure 'ccnfMOM Unsub Growth1%' = ```
			
			VAR CurrentUnsub = [CCNF Unsubscribe]
			VAR PPUnsub = [ccnfPPTotalUnsub]
			VAR Growth =
			    DIVIDE(CurrentUnsub - PPUnsub, PPUnsub)
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Unsubscribed
		lineageTag: e577c9a3-05a7-4b43-9475-cc9dac9d9904

	measure 'ccnfMOM Unsub Rate Growth1%' = ```
			
			VAR CurrentUnsubRate = [CCNF Conversion Rate]
			VAR PPUnsubRate = [ccnfPPTotalUnsubRate]
			VAR Growth =
			    DIVIDE(
			        CurrentUnsubRate - PPUnsubRate,
			        PPUnsubRate
			    )
			RETURN
			    Growth
			
			```
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: CCNF Unsubscribed Rate
		lineageTag: 27f5b743-8ee3-4a0d-9fc2-c6475c2d541a

	measure 'fYoY Recipients Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentRecipients = [FlowRecip]
			VAR PYRecipients = [fPYRecipients]
			VAR Growth = DIVIDE(CurrentRecipients - PYRecipients, PYRecipients)
			VAR Change = CurrentRecipients - PYRecipients
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FRECP
		lineageTag: e7bdbf9a-55e4-488d-a982-37e9a67efa1a

	measure 'fMOM Recipients Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentRecipients = [FlowRecip]
			VAR PPRecipients = [fPPRecipients]
			VAR Growth = DIVIDE(CurrentRecipients - PPRecipients, PPRecipients)
			VAR Change = CurrentRecipients - PPRecipients
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FRECP
		lineageTag: 1090f33f-60db-4633-ac42-33a7203f0b08

	measure 'fMOM Unique Opens Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentOpens = [FlowUnqOpens]
			VAR PPUNQOP = [fPPUniqOpens]
			VAR Growth = DIVIDE(CurrentOpens - PPUNQOP, PPUNQOP)
			VAR Change = CurrentOpens - PPUNQOP
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQOP
		lineageTag: 7f834bbd-1a19-464b-851d-4389f0757449

	measure 'fYoY Unique Opens Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentOpens = [FlowUnqOpens]
			VAR PYOpens = [fPYUnqOpens]
			VAR Growth = DIVIDE(CurrentOpens - PYOpens, PYOpens)
			VAR Change = CurrentOpens - PYOpens
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQOP
		lineageTag: a8820d50-f8a7-4f01-8f8e-d6c10a27005d

	measure 'fYoY OpenRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentOpenRate = [FlowOpenRate]
			VAR PYOpenRate = [fPYUnqOpenRate]
			VAR Growth = DIVIDE(CurrentOpenRate - PYOpenRate, PYOpenRate)
			VAR Change = CurrentOpenRate - PYOpenRate
			RETURN
			    ROUND(Change * 100, 1) & "% (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQOP
		lineageTag: 7949c062-fbd9-4849-b2c7-833982a319b2

	measure 'fMOM TotalUnqClick Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR TotalUnqClick = [FlowUnqClicks]
			VAR PPClick = [fPPTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PPClick, PPClick)
			VAR Change = TotalUnqClick - PPClick
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQCLICKS
		lineageTag: 205c8749-1858-4334-aaab-3d397407531d

	measure 'fYOY TotalUnqClick Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR TotalUnqClick = [FlowUnqClicks]
			VAR PYClick = [fPYTotalUnqClick]
			VAR Growth = DIVIDE(TotalUnqClick - PYClick, PYClick)
			VAR Change = TotalUnqClick - PYClick
			RETURN
			    FORMAT(Change, "#,##0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQCLICKS
		lineageTag: db74a81b-3a73-459a-9718-3aafca28e1d0

	measure 'fMOM Revenue Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentRevenue = [flowREVENUE]
			VAR PPRevenue = [fPPTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue - PPRevenue, PPRevenue)
			VAR Change = CurrentRevenue - PPRevenue
			RETURN
			    FORMAT(Change, "$#,0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FTOTALREV
		lineageTag: 482ec2f4-826c-4712-8694-f7f321343997

	measure 'fYOY Revenue Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentRevenue = [flowREVENUE]
			VAR PYRevenue = [fPYTotalRevenue]
			VAR Growth = DIVIDE(CurrentRevenue - PYRevenue, PYRevenue)
			VAR Change = CurrentRevenue - PYRevenue
			RETURN
			    FORMAT(Change, "$#,0") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FTOTALREV
		lineageTag: b50455bc-4bb5-4169-afdb-f123770515df

	measure 'fMOM FlowClickRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentDailyClickRate = [FlowCLICK TO RECIEVE RATE]
			VAR PPDailyClickRate = [fPPFlowClickRate]
			VAR Growth = DIVIDE(CurrentDailyClickRate - PPDailyClickRate, PPDailyClickRate)
			VAR Change = CurrentDailyClickRate - PPDailyClickRate
			RETURN
			    FORMAT(Change, "0.0%") & " (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FCLKTORECVRATE
		lineageTag: 389b8e0e-5783-41e6-836c-b1714ed70ae4

	measure 'fYOY FlowClickRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentDailyClickRate = [FlowCLICK TO RECIEVE RATE]
			VAR PYDailyClickRate = [fPYFlowClickRate]
			VAR Change = CurrentDailyClickRate - PYDailyClickRate
			RETURN
			    IF(
			        Change < 0,
			        ROUND(Change, 3) & " " & down_arrow,
			        ROUND(Change, 3) & " " & up_arrow
			    )
			
			```
		displayFolder: FCLKTORECVRATE
		lineageTag: 609f63ad-d5c7-4ec2-9872-075d30e0e9a1

	measure 'fYOY TotalConversions Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentConversions = [FlowConversion]
			VAR PYConversions = [fPYTotalConversions]
			VAR Change = CurrentConversions - PYConversions
			RETURN
			    IF(
			        Change < 0,
			        ROUND(Change, 0) & " " & down_arrow,
			        ROUND(Change, 0) & " " & up_arrow
			    )
			
			```
		displayFolder: FTOTALCONV
		lineageTag: 3a732cdb-0caf-47e1-a728-1451012945ad

	measure 'fMOM TotalConversions Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentConversions = [FlowConversion]
			VAR PPConversions = [fPPTotalConversions]
			VAR Change = CurrentConversions - PPConversions
			RETURN
			    IF(
			        Change < 0,
			        ROUND(Change, 0) & " " & down_arrow,
			        ROUND(Change, 0) & " " & up_arrow
			    )
			
			```
		displayFolder: FTOTALCONV
		lineageTag: 79058968-8ed5-408a-90b5-66cad916ec2d

	measure 'fMOM DailyConversionRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentConversionsRate = [flowCONVERSION RATE]
			VAR PPConversionsRate = [fPPTotalConversionsRate]
			VAR Change = CurrentConversionsRate - PPConversionsRate
			RETURN
			    IF(
			        Change < 0,
			        ROUND(Change * 100, 1) & "% " & down_arrow,
			        ROUND(Change * 100, 1) & "% " & up_arrow
			    )
			
			```
		displayFolder: FCONVRATE
		lineageTag: ca8676d4-8414-4da7-ba98-a8057bd8a675

	measure 'fYOY DailyConversionRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentConversionsRate = [flowCONVERSION RATE]
			VAR PYConversionsRate = [fPYTotalConversionsRate]
			VAR Change = CurrentConversionsRate - PYConversionsRate
			RETURN
			    IF(
			        Change < 0,
			        ROUND(Change * 100, 1) & "% " & down_arrow,
			        ROUND(Change * 100, 1) & "% " & up_arrow
			    )
			
			```
		displayFolder: FCONVRATE
		lineageTag: d88cb44b-05bb-436d-8b1f-c6df122bcea0

	measure 'fMOM Unsub Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentUnsub = [FlowUnsubscribed]
			VAR PPUnsub = [fPPTotalUnsub]
			VAR Change = CurrentUnsub - PPUnsub
			RETURN
			    IF(
			        Change < 0,
			        Change & " " & down_arrow,
			        Change & " " & up_arrow
			    )
			
			```
		displayFolder: FUNSUB
		lineageTag: f19659a6-fb02-44e1-8d87-cc021c6e4a95

	measure 'fYOY Unsub Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentUnsub = [FlowUnsubscribed]
			VAR PYUnsub = [fPYTotalUnsub]
			VAR Change = CurrentUnsub - PYUnsub
			RETURN
			    IF(
			        Change < 0,
			        Change & " " & down_arrow,
			        Change & " " & up_arrow
			    )
			
			```
		displayFolder: FUNSUB
		lineageTag: 50a289a4-14d0-4e35-9a78-dd10bd8cb036

	measure 'FlowAOV PY' = ```
			
			CALCULATE(
			    [FlowAOV],
			    DATEADD(DailyDimDate[Date], -1, YEAR)
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: FlowMeasures
		lineageTag: f278dc21-0822-4fe7-bfa1-8dad39319c9c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'fMOM OpensRate Change' = ```
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR CurrentOpenRate = [FlowOpenRate]
			VAR PPOpenRate = [fPPUniqOpenRate]
			VAR Growth = DIVIDE(CurrentOpenRate - PPOpenRate, PPOpenRate)
			VAR Change = CurrentOpenRate - PPOpenRate
			RETURN
			    ROUND(Change * 100, 1) & "% (" &
			        IF(
			            Growth < 0,
			            ROUND(Growth * 100, 1) & "% " & down_arrow,
			            ROUND(Growth * 100, 1) & "% " & up_arrow
			        )
			    & ")"
			
			```
		displayFolder: FUNQOP
		lineageTag: c0b911e0-5457-41f6-8524-fcf2f24d769b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition All_Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

