table CampaignDimDate
	lineageTag: b44116f9-3e34-47a1-a0e5-7b24928b1eeb

	column 'Send Date'
		dataType: dateTime
		formatString: m/d/yy
		lineageTag: ff5c4a13-5a5d-4a57-b738-46b06cf874f3
		summarizeBy: none
		sourceColumn: Send Date

		variation Variation
			isDefault
			relationship: 080162d7-2c30-4ebb-8ff8-85e5a7ba9e16
			defaultHierarchy: LocalDateTable_d5eaff61-33bb-4b9f-82ae-d1c090d65e94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Month
		dataType: int64
		formatString: 0
		lineageTag: a8d90d70-94db-4eb3-8b51-e2f141835ec9
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year-QTR
		dataType: string
		lineageTag: 5e0f69f6-8f44-4d74-8911-f653cda5e648
		summarizeBy: none
		sourceColumn: Year-QTR

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 037fc8bc-4832-401d-80e4-8a36dd1e9d82
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 94762582-639a-4350-b4b4-ee7b16c11e5e
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 4379eaee-011c-4d93-92aa-1a7fec33aa75
		summarizeBy: none
		sourceColumn: Year Month
		sortByColumn: 'YearMonth Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: afaf1039-fd05-4d8b-83c1-6135a66ece65
		summarizeBy: sum
		sourceColumn: Week of Year

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: 8ad98e98-b794-4103-92a4-f65e2c466325
		summarizeBy: none
		sourceColumn: Start of Week

		variation Variation
			isDefault
			relationship: c87a2e32-f597-4d2e-ae9a-967b9d7b7a63
			defaultHierarchy: LocalDateTable_1e173676-79fe-4358-adbb-6da419d93f13.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Month Name' = FORMAT(CampaignDimDate[Send Date],"MMMM")
		lineageTag: 35385359-aeaa-4cfd-b12b-00763f3e6a93
		summarizeBy: none
		sortByColumn: Month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'End of week' = [Start of Week]+ 6
		formatString: m/d/yyyy
		lineageTag: 7e957dfc-d141-4964-88ba-5d780d081297
		summarizeBy: none

		variation Variation
			isDefault
			relationship: e1485eb5-3758-4b14-9609-86119363f3cc
			defaultHierarchy: LocalDateTable_81161584-55b4-424e-92d8-f2044153a6f3.'Date Hierarchy'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Start & End Week' = CampaignDimDate[Start of Week] & " - " & CampaignDimDate[End of week]
		lineageTag: 179cdb7f-217c-4733-ba39-9f5a1d9ae981
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Year Week' = YEAR(CampaignDimDate[Send Date])&"-"&REPT("0",2-LEN(WEEKNUM(CampaignDimDate[Send Date])))&WEEKNUM(CampaignDimDate[Send Date])
		lineageTag: b5f99d95-58f7-45b7-8b7f-bb124ac80772
		summarizeBy: none
		sortByColumn: 'YearWeek Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'YearMonth Sort' = ```
			
			YEAR ( CampaignDimDate[Send Date] ) * 100
			+ MONTH ( CampaignDimDate[Send Date] )
			
			```
		formatString: 0
		lineageTag: e10bee8e-838d-4484-ae0a-e39924c6bdaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'YearWeek Sort' = ```
			
			YEAR ( CampaignDimDate[Send Date] ) * 100
			+ CampaignDimDate[Week of Year]
			
			```
		formatString: 0
		lineageTag: f57d1d56-5dc9-4438-a0ed-587e5275e638
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition CampaignDimDate = m
		mode: import
		source =
				let
				    Source = {cStartDate..cEndDate},
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Column1", Order.Ascending}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Sorted Rows",{{"Column1", "Send Date"}}),
				    #"Inserted Month" = Table.AddColumn(#"Renamed Columns", "Month", each Date.Month([Send Date]), Int64.Type),
				    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month", "Quarter", each Date.ToText([Send Date], "yyyy") & "-Q" & Text.From(Date.QuarterOfYear([Send Date]))),
				    #"Inserted Year" = Table.AddColumn(#"Inserted Quarter", "Year", each Date.Year([Send Date]), Int64.Type),
				    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Year", "Day of Week", each Date.ToText([Send Date],"dddd")),
				    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Day of Week", "Start of Week", each Date.StartOfWeek([Send Date]), type date),
				    #"Inserted Year1" = Table.AddColumn(#"Inserted Start of Week", "Year.1", each Date.ToText([Send Date],"MMM yy")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Year Month"}}),
				    #"Sorted Rows1" = Table.Sort(#"Renamed Columns1",{{"Send Date", Order.Descending}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows1",{{"Send Date", type date}}),
				    #"Inserted Week of Year" = Table.AddColumn(#"Changed Type1", "Week of Year", each Date.WeekOfYear([Send Date]), Int64.Type),
				    #"Sorted Rows2" = Table.Sort(#"Inserted Week of Year",{{"Send Date", Order.Ascending}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Sorted Rows2",{"Start of Week"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns",{{"Quarter", "Year-QTR"}}),
				    #"Inserted Start of Week1" = Table.AddColumn(#"Renamed Columns2", "Start of Week", each Date.StartOfWeek([Send Date]), type date),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Inserted Start of Week1",{{"Send Date", type date}}),
				    #"Sorted Rows3" = Table.Sort(#"Changed Type2",{{"Send Date", Order.Descending}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Sorted Rows3", "Merged", each Text.Combine({Text.From([Month], "en-IN"), Text.From([Year], "en-IN")}, ""), type text),
				    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "Year-Month"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns3",{{"Year-Month", Int64.Type}}),
				    #"Sorted Rows4" = Table.Sort(#"Changed Type3",{{"Send Date", Order.Descending}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Sorted Rows4",{"Year-Month"}),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Removed Columns1",{{"Send Date", type date}})
				in
				    #"Changed Type4"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

