table Klaviyo
	lineageTag: f1a197c2-6440-4e47-8410-ea49c62c9f0d

	column 'Flow Name'
		dataType: string
		lineageTag: 22c17c45-20bf-43ba-b769-8d0067b85437
		summarizeBy: none
		sourceColumn: Flow Name

		annotation SummarizationSetBy = Automatic

	column 'Matching Title'
		dataType: string
		lineageTag: 15f624d7-76e1-42a1-be4b-3c82b4646fee
		summarizeBy: none
		sourceColumn: Matching Title

		annotation SummarizationSetBy = Automatic

	partition Klaviyo = m
		mode: import
		source =
				let
				    Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/124kJpPan-_N5Un6vrQ3dNHfaYg8Rd9agX2gG3oNvXUY/edit?gid=884097271#gid=884097271"),
				    Klaviyo_Table = Source{[name="Klaviyo",ItemKind="Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Klaviyo_Table, [PromoteAllScalars=true]),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"Flow Name"}, "Attribute", "Value"),
				    #"Removed Columns" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Attribute"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Value", "Matching Title"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

