table 'SMS Campaigns'
	lineageTag: c542731e-4592-4a22-8254-0ec0cc8561a5

	column Date
		dataType: string
		lineageTag: 7bf700be-d81e-41ff-a829-9fb6832668e8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Campaign ID'
		dataType: string
		lineageTag: 607db6fc-3593-493d-bb46-af9c34b1d8f4
		summarizeBy: none
		sourceColumn: Campaign ID

		annotation SummarizationSetBy = Automatic

	column 'Campaign Name'
		dataType: string
		lineageTag: e6fcd3fb-0c3b-41f0-acaf-5a3f441b358d
		summarizeBy: none
		sourceColumn: Campaign Name

		annotation SummarizationSetBy = Automatic

	column 'Send Date'
		dataType: dateTime
		formatString: mm/dd/yyyy
		lineageTag: 9f3438ee-d437-4195-9fff-f44b32b0a12f
		summarizeBy: none
		sourceColumn: Send Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Send Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: f9bbba63-1fd2-4d13-a41f-bd339eae8c42
		summarizeBy: none
		sourceColumn: Send Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Total Recipients'
		dataType: int64
		formatString: 0
		lineageTag: c29da069-fa0d-4164-a1d8-b6af98b6ea9b
		summarizeBy: sum
		sourceColumn: Total Recipients

		annotation SummarizationSetBy = Automatic

	column 'Click Rate'
		dataType: double
		lineageTag: 04da3fda-a09b-4d58-b81a-f58483a1fd7a
		summarizeBy: sum
		sourceColumn: Click Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unsubscribe Rate'
		dataType: double
		lineageTag: d5383318-c267-47b7-82f9-c6bea4e083df
		summarizeBy: sum
		sourceColumn: Unsubscribe Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unique Clicks'
		dataType: int64
		formatString: 0
		lineageTag: 6de04ff8-b326-4214-8c4e-ac37934299f5
		summarizeBy: sum
		sourceColumn: Unique Clicks

		annotation SummarizationSetBy = Automatic

	column 'Unique Unsubscribes'
		dataType: int64
		formatString: 0
		lineageTag: 8e590c5a-4473-49c7-b6f4-b23272deddef
		summarizeBy: sum
		sourceColumn: Unique Unsubscribes

		annotation SummarizationSetBy = Automatic

	column 'Total Unsubscribes'
		dataType: int64
		formatString: 0
		lineageTag: 0fff431b-cbec-49e3-be67-29575afa6f5c
		summarizeBy: sum
		sourceColumn: Total Unsubscribes

		annotation SummarizationSetBy = Automatic

	column 'Failed to Deliver SMS'
		dataType: int64
		formatString: 0
		lineageTag: c534e46b-d6ea-4f91-8bdd-d7f13739ad79
		summarizeBy: sum
		sourceColumn: Failed to Deliver SMS

		annotation SummarizationSetBy = Automatic

	column 'Total Placed Order'
		dataType: int64
		formatString: 0
		lineageTag: 70a5ab9d-798c-4543-8a4d-7505a1c61f5c
		summarizeBy: sum
		sourceColumn: Total Placed Order

		annotation SummarizationSetBy = Automatic

	column 'Total Placed Order Value'
		dataType: double
		lineageTag: bab3b06c-f942-4384-9be3-2d76f8c8a297
		summarizeBy: sum
		sourceColumn: Total Placed Order Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tags
		dataType: string
		lineageTag: 1bc4bcc1-d5bc-4169-add5-ce756f7bb59f
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column Subject
		dataType: string
		lineageTag: 536283ea-1bd2-4861-a632-48e7c872aad1
		summarizeBy: none
		sourceColumn: Subject

		annotation SummarizationSetBy = Automatic

	column 'Preview Text'
		dataType: string
		lineageTag: 011d70ee-995f-4c05-9905-b46a707c640d
		summarizeBy: none
		sourceColumn: Preview Text

		annotation SummarizationSetBy = Automatic

	column List
		dataType: string
		lineageTag: 1b85d528-3e6b-43f1-939b-b6c37692d4c2
		summarizeBy: none
		sourceColumn: List

		annotation SummarizationSetBy = Automatic

	column 'Excluded List'
		dataType: string
		lineageTag: 87beef49-4849-4aa8-9fdf-c44554044756
		summarizeBy: none
		sourceColumn: Excluded List

		annotation SummarizationSetBy = Automatic

	column 'Day of Week'
		dataType: string
		lineageTag: 0fb1893d-ac4b-49ca-8ca0-6ff28e40a7db
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = Automatic

	column 'Campaign Channel'
		dataType: string
		lineageTag: c1216285-ac7b-439d-b693-d13741f42bc5
		summarizeBy: none
		sourceColumn: Campaign Channel

		annotation SummarizationSetBy = Automatic

	partition 'SMS Campaigns' = m
		mode: import
		source =
				let
				    Source = AzureStorage.Blobs("https://retrospecblob.blob.core.windows.net"),
				    gold = Source{[Name="gold"]}[Data],
				
				    // Filter to required file
				    #"Filtered Rows" =
				        Table.SelectRows(
				            gold,
				            each [Name] = "klaviyo_data/campaign_sms/campaign_sms.csv"
				        ),
				
				    #"Filtered Hidden Files" =
				        Table.SelectRows(
				            #"Filtered Rows",
				            each [Attributes]?[Hidden]? <> true
				        ),
				
				    // Read CSV directly (this replaces Transform File (2))
				    #"Parsed CSV" =
				        Table.AddColumn(
				            #"Filtered Hidden Files",
				            "Data",
				            each Csv.Document(
				                [Content],
				                [
				                    Delimiter = ",",
				                    Columns = 21,
				                    Encoding = 1252,
				                    QuoteStyle = QuoteStyle.None
				                ]
				            )
				        ),
				
				    // Promote headers
				    #"Promoted Headers" =
				        Table.TransformColumns(
				            #"Parsed CSV",
				            {
				                "Data",
				                each Table.PromoteHeaders(_, [PromoteAllScalars = true])
				            }
				        ),
				
				    // Keep only parsed table
				    #"Removed Other Columns" =
				        Table.SelectColumns(#"Promoted Headers", {"Data"}),
				
				    // Expand columns
				    #"Expanded Table" =
				        Table.ExpandTableColumn(
				            #"Removed Other Columns",
				            "Data",
				            Table.ColumnNames(
				                Table.PromoteHeaders(
				                    Csv.Document(
				                        #"Filtered Hidden Files"{0}[Content],
				                        [
				                            Delimiter = ",",
				                            Columns = 21,
				                            Encoding = 1252,
				                            QuoteStyle = QuoteStyle.None
				                        ]
				                    ),
				                    [PromoteAllScalars = true]
				                )
				            )
				        ),
				
				    // Data types
				    #"Changed Type" =
				        Table.TransformColumnTypes(
				            #"Expanded Table",
				            {
				                {"Date", type text},
				                {"Campaign ID", type text},
				                {"Campaign Name", type text},
				                {"Send Date", type date},
				                {"Send Time", type time},
				                {"Total Recipients", Int64.Type},
				                {"Click Rate", type number},
				                {"Unsubscribe Rate", type number},
				                {"Unique Clicks", Int64.Type},
				                {"Unique Unsubscribes", Int64.Type},
				                {"Total Unsubscribes", Int64.Type},
				                {"Failed to Deliver SMS", Int64.Type},
				                {"Total Placed Order", Int64.Type},
				                {"Total Placed Order Value", type number},
				                {"Tags", type text},
				                {"Subject", type text},
				                {"Preview Text", type text},
				                {"List", type text},
				                {"Excluded List", type text},
				                {"Day of Week", type text},
				                {"Campaign Channel", type text}
				            }
				        )
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

